/* Entities.c generated by valac 0.34.4, the Vala compiler
 * generated from Entities.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <Entitas.h>
#include <stdlib.h>
#include <string.h>


#define SHMUP_WARZ_TYPE_ENEMY (shmup_warz_enemy_get_type ())

#define SHMUP_WARZ_TYPE_LAYER (shmup_warz_layer_get_type ())

#define SHMUP_WARZ_TYPE_EFFECT (shmup_warz_effect_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

typedef enum  {
	SHMUP_WARZ_ENEMY_Enemy1,
	SHMUP_WARZ_ENEMY_Enemy2,
	SHMUP_WARZ_ENEMY_Enemy3
} ShmupWarzEnemy;

typedef enum  {
	SHMUP_WARZ_LAYER_DEFAULT,
	SHMUP_WARZ_LAYER_BACKGROUND,
	SHMUP_WARZ_LAYER_TEXT,
	SHMUP_WARZ_LAYER_LIVES,
	SHMUP_WARZ_LAYER_MINES,
	SHMUP_WARZ_LAYER_ACTORS_1,
	SHMUP_WARZ_LAYER_ACTORS_2,
	SHMUP_WARZ_LAYER_ACTORS_3,
	SHMUP_WARZ_LAYER_PLAYER,
	SHMUP_WARZ_LAYER_BULLET,
	SHMUP_WARZ_LAYER_PARTICLE,
	SHMUP_WARZ_LAYER_HUD
} ShmupWarzLayer;

typedef enum  {
	SHMUP_WARZ_EFFECT_PEW,
	SHMUP_WARZ_EFFECT_ASPLODE,
	SHMUP_WARZ_EFFECT_SMALLASPLODE
} ShmupWarzEffect;



#define SHMUP_WARZ_Tau (2 * G_PI)
GType shmup_warz_enemy_get_type (void) G_GNUC_CONST;
GType shmup_warz_layer_get_type (void) G_GNUC_CONST;
GType shmup_warz_effect_get_type (void) G_GNUC_CONST;
EntitasEntity* shmup_warz_createBackground (void);
EntitasEntity* shmup_warz_addPosition (EntitasEntity* e, gdouble x, gdouble y);
EntitasEntity* shmup_warz_addScale (EntitasEntity* e, gdouble x, gdouble y);
EntitasEntity* shmup_warz_addResource (EntitasEntity* e, const gchar* path, GObject* sprite, gboolean bgd);
#define SHMUP_WARZ_RES "/usr/local/share/shmupwarz"
EntitasEntity* shmup_warz_createPlayer (void);
EntitasEntity* shmup_warz_setPlayer (EntitasEntity* e, gboolean value);
EntitasEntity* shmup_warz_addBounds (EntitasEntity* e, gdouble radius);
EntitasEntity* shmup_warz_addHealth (EntitasEntity* e, gdouble health, gdouble maximumHealth);
EntitasEntity* shmup_warz_addVelocity (EntitasEntity* e, gdouble x, gdouble y);
EntitasEntity* shmup_warz_addLayer (EntitasEntity* e, gint ordinal);
#define SHMUP_WARZ_SCREEN_WIDTH 800
#define SHMUP_WARZ_SCREEN_HEIGHT 600
EntitasEntity* shmup_warz_createBullet (gdouble x, gdouble y);
EntitasEntity* shmup_warz_setBullet (EntitasEntity* e, gboolean value);
EntitasEntity* shmup_warz_addTint (EntitasEntity* e, gint r, gint g, gint b, gint a);
EntitasEntity* shmup_warz_addColorTween (EntitasEntity* e, gdouble redMin, gdouble redMax, gdouble redSpeed, gdouble greenMin, gdouble greenMax, gdouble greenSpeed, gdouble blueMin, gdouble blueMax, gdouble blueSpeed, gdouble alphaMin, gdouble alphaMax, gdouble alphaSpeed, gboolean redAnimate, gboolean greenAnimate, gboolean blueAnimate, gboolean alphaAnimate, gboolean repeat);
EntitasEntity* shmup_warz_addExpires (EntitasEntity* e, gdouble delay);
EntitasEntity* shmup_warz_addSoundEffect (EntitasEntity* e, gint effect);
EntitasEntity* shmup_warz_createParticle (gdouble x, gdouble y);
EntitasEntity* shmup_warz_createExplosion (gdouble x, gdouble y);
EntitasEntity* shmup_warz_addScaleTween (EntitasEntity* e, gdouble min, gdouble max, gdouble speed, gboolean repeat, gboolean active);
EntitasEntity* shmup_warz_createBang (gdouble x, gdouble y);
EntitasEntity* shmup_warz_createEnemy1 (void);
EntitasEntity* shmup_warz_setEnemy (EntitasEntity* e, gboolean value);
EntitasEntity* shmup_warz_addText (EntitasEntity* e, const gchar* text, GObject* sprite);
EntitasEntity* shmup_warz_createEnemy2 (void);
EntitasEntity* shmup_warz_createEnemy3 (void);


GType shmup_warz_enemy_get_type (void) {
	static volatile gsize shmup_warz_enemy_type_id__volatile = 0;
	if (g_once_init_enter (&shmup_warz_enemy_type_id__volatile)) {
		static const GEnumValue values[] = {{SHMUP_WARZ_ENEMY_Enemy1, "SHMUP_WARZ_ENEMY_Enemy1", "enemy1"}, {SHMUP_WARZ_ENEMY_Enemy2, "SHMUP_WARZ_ENEMY_Enemy2", "enemy2"}, {SHMUP_WARZ_ENEMY_Enemy3, "SHMUP_WARZ_ENEMY_Enemy3", "enemy3"}, {0, NULL, NULL}};
		GType shmup_warz_enemy_type_id;
		shmup_warz_enemy_type_id = g_enum_register_static ("ShmupWarzEnemy", values);
		g_once_init_leave (&shmup_warz_enemy_type_id__volatile, shmup_warz_enemy_type_id);
	}
	return shmup_warz_enemy_type_id__volatile;
}


GType shmup_warz_layer_get_type (void) {
	static volatile gsize shmup_warz_layer_type_id__volatile = 0;
	if (g_once_init_enter (&shmup_warz_layer_type_id__volatile)) {
		static const GEnumValue values[] = {{SHMUP_WARZ_LAYER_DEFAULT, "SHMUP_WARZ_LAYER_DEFAULT", "default"}, {SHMUP_WARZ_LAYER_BACKGROUND, "SHMUP_WARZ_LAYER_BACKGROUND", "background"}, {SHMUP_WARZ_LAYER_TEXT, "SHMUP_WARZ_LAYER_TEXT", "text"}, {SHMUP_WARZ_LAYER_LIVES, "SHMUP_WARZ_LAYER_LIVES", "lives"}, {SHMUP_WARZ_LAYER_MINES, "SHMUP_WARZ_LAYER_MINES", "mines"}, {SHMUP_WARZ_LAYER_ACTORS_1, "SHMUP_WARZ_LAYER_ACTORS_1", "actors-1"}, {SHMUP_WARZ_LAYER_ACTORS_2, "SHMUP_WARZ_LAYER_ACTORS_2", "actors-2"}, {SHMUP_WARZ_LAYER_ACTORS_3, "SHMUP_WARZ_LAYER_ACTORS_3", "actors-3"}, {SHMUP_WARZ_LAYER_PLAYER, "SHMUP_WARZ_LAYER_PLAYER", "player"}, {SHMUP_WARZ_LAYER_BULLET, "SHMUP_WARZ_LAYER_BULLET", "bullet"}, {SHMUP_WARZ_LAYER_PARTICLE, "SHMUP_WARZ_LAYER_PARTICLE", "particle"}, {SHMUP_WARZ_LAYER_HUD, "SHMUP_WARZ_LAYER_HUD", "hud"}, {0, NULL, NULL}};
		GType shmup_warz_layer_type_id;
		shmup_warz_layer_type_id = g_enum_register_static ("ShmupWarzLayer", values);
		g_once_init_leave (&shmup_warz_layer_type_id__volatile, shmup_warz_layer_type_id);
	}
	return shmup_warz_layer_type_id__volatile;
}


GType shmup_warz_effect_get_type (void) {
	static volatile gsize shmup_warz_effect_type_id__volatile = 0;
	if (g_once_init_enter (&shmup_warz_effect_type_id__volatile)) {
		static const GEnumValue values[] = {{SHMUP_WARZ_EFFECT_PEW, "SHMUP_WARZ_EFFECT_PEW", "pew"}, {SHMUP_WARZ_EFFECT_ASPLODE, "SHMUP_WARZ_EFFECT_ASPLODE", "asplode"}, {SHMUP_WARZ_EFFECT_SMALLASPLODE, "SHMUP_WARZ_EFFECT_SMALLASPLODE", "smallasplode"}, {0, NULL, NULL}};
		GType shmup_warz_effect_type_id;
		shmup_warz_effect_type_id = g_enum_register_static ("ShmupWarzEffect", values);
		g_once_init_leave (&shmup_warz_effect_type_id__volatile, shmup_warz_effect_type_id);
	}
	return shmup_warz_effect_type_id__volatile;
}


/**
    *  Create Background
    */
static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


EntitasEntity* shmup_warz_createBackground (void) {
	EntitasEntity* result = NULL;
	EntitasEntity* entity = NULL;
	EntitasWorld* _tmp0_ = NULL;
	EntitasWorld* _tmp1_ = NULL;
	EntitasEntity* _tmp2_ = NULL;
	EntitasEntity* _tmp3_ = NULL;
	EntitasEntity* _tmp4_ = NULL;
	EntitasEntity* _tmp5_ = NULL;
	EntitasEntity* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	EntitasEntity* _tmp10_ = NULL;
	EntitasEntity* _tmp11_ = NULL;
	_tmp0_ = entitas_world_get_instance ();
	_tmp1_ = _tmp0_;
	_tmp2_ = entitas_world_createEntity (_tmp1_, "background");
	entity = _tmp2_;
	_tmp3_ = shmup_warz_addPosition (entity, (gdouble) 0, (gdouble) 0);
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp4_);
	_tmp5_ = shmup_warz_addScale (entity, (gdouble) 2, (gdouble) 1);
	_tmp6_ = _tmp5_;
	_g_object_unref0 (_tmp6_);
	_tmp7_ = string_to_string (SHMUP_WARZ_RES);
	_tmp8_ = g_strconcat (_tmp7_, "/images/background.png", NULL);
	_tmp9_ = _tmp8_;
	_tmp10_ = shmup_warz_addResource (entity, _tmp9_, NULL, TRUE);
	_tmp11_ = _tmp10_;
	_g_object_unref0 (_tmp11_);
	_g_free0 (_tmp9_);
	result = entity;
	return result;
}


/**
    *  Create Player
    */
EntitasEntity* shmup_warz_createPlayer (void) {
	EntitasEntity* result = NULL;
	EntitasEntity* entity = NULL;
	EntitasWorld* _tmp0_ = NULL;
	EntitasWorld* _tmp1_ = NULL;
	EntitasEntity* _tmp2_ = NULL;
	EntitasEntity* _tmp3_ = NULL;
	EntitasEntity* _tmp4_ = NULL;
	EntitasEntity* _tmp5_ = NULL;
	EntitasEntity* _tmp6_ = NULL;
	EntitasEntity* _tmp7_ = NULL;
	EntitasEntity* _tmp8_ = NULL;
	EntitasEntity* _tmp9_ = NULL;
	EntitasEntity* _tmp10_ = NULL;
	EntitasEntity* _tmp11_ = NULL;
	EntitasEntity* _tmp12_ = NULL;
	EntitasEntity* _tmp13_ = NULL;
	EntitasEntity* _tmp14_ = NULL;
	const gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	EntitasEntity* _tmp18_ = NULL;
	EntitasEntity* _tmp19_ = NULL;
	_tmp0_ = entitas_world_get_instance ();
	_tmp1_ = _tmp0_;
	_tmp2_ = entitas_world_createEntity (_tmp1_, "player");
	entity = _tmp2_;
	_tmp3_ = shmup_warz_setPlayer (entity, TRUE);
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp4_);
	_tmp5_ = shmup_warz_addBounds (entity, (gdouble) 43);
	_tmp6_ = _tmp5_;
	_g_object_unref0 (_tmp6_);
	_tmp7_ = shmup_warz_addHealth (entity, (gdouble) 100, (gdouble) 100);
	_tmp8_ = _tmp7_;
	_g_object_unref0 (_tmp8_);
	_tmp9_ = shmup_warz_addVelocity (entity, (gdouble) 0, (gdouble) 0);
	_tmp10_ = _tmp9_;
	_g_object_unref0 (_tmp10_);
	_tmp11_ = shmup_warz_addLayer (entity, (gint) SHMUP_WARZ_LAYER_PLAYER);
	_tmp12_ = _tmp11_;
	_g_object_unref0 (_tmp12_);
	_tmp13_ = shmup_warz_addPosition (entity, (gdouble) (SHMUP_WARZ_SCREEN_WIDTH / 2), (gdouble) (SHMUP_WARZ_SCREEN_HEIGHT - 80));
	_tmp14_ = _tmp13_;
	_g_object_unref0 (_tmp14_);
	_tmp15_ = string_to_string (SHMUP_WARZ_RES);
	_tmp16_ = g_strconcat (_tmp15_, "/images/fighter.png", NULL);
	_tmp17_ = _tmp16_;
	_tmp18_ = shmup_warz_addResource (entity, _tmp17_, NULL, FALSE);
	_tmp19_ = _tmp18_;
	_g_object_unref0 (_tmp19_);
	_g_free0 (_tmp17_);
	result = entity;
	return result;
}


/**
    *  Create Bullet
    */
EntitasEntity* shmup_warz_createBullet (gdouble x, gdouble y) {
	EntitasEntity* result = NULL;
	gdouble r = 0.0;
	gdouble g = 0.0;
	gdouble b = 0.0;
	gdouble m = 0.0;
	gdouble a = 0.0;
	gdouble s = 0.0;
	EntitasEntity* entity = NULL;
	EntitasWorld* _tmp0_ = NULL;
	EntitasWorld* _tmp1_ = NULL;
	EntitasEntity* _tmp2_ = NULL;
	EntitasEntity* _tmp3_ = NULL;
	EntitasEntity* _tmp4_ = NULL;
	EntitasEntity* _tmp5_ = NULL;
	EntitasEntity* _tmp6_ = NULL;
	gdouble _tmp7_ = 0.0;
	gdouble _tmp8_ = 0.0;
	EntitasEntity* _tmp9_ = NULL;
	EntitasEntity* _tmp10_ = NULL;
	EntitasEntity* _tmp11_ = NULL;
	EntitasEntity* _tmp12_ = NULL;
	EntitasEntity* _tmp13_ = NULL;
	EntitasEntity* _tmp14_ = NULL;
	EntitasEntity* _tmp15_ = NULL;
	EntitasEntity* _tmp16_ = NULL;
	EntitasEntity* _tmp17_ = NULL;
	EntitasEntity* _tmp18_ = NULL;
	EntitasEntity* _tmp19_ = NULL;
	EntitasEntity* _tmp20_ = NULL;
	EntitasEntity* _tmp21_ = NULL;
	EntitasEntity* _tmp22_ = NULL;
	const gchar* _tmp23_ = NULL;
	gchar* _tmp24_ = NULL;
	gchar* _tmp25_ = NULL;
	EntitasEntity* _tmp26_ = NULL;
	EntitasEntity* _tmp27_ = NULL;
	EntitasEntity* _tmp28_ = NULL;
	EntitasEntity* _tmp29_ = NULL;
	r = (gdouble) 0xad;
	g = (gdouble) 0xaf;
	b = (gdouble) 0x2f;
	m = 255.0;
	a = 255.0;
	s = 10.0;
	_tmp0_ = entitas_world_get_instance ();
	_tmp1_ = _tmp0_;
	_tmp2_ = entitas_world_createEntity (_tmp1_, "bullet");
	entity = _tmp2_;
	_tmp3_ = shmup_warz_setBullet (entity, TRUE);
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp4_);
	_tmp5_ = shmup_warz_addHealth (entity, 1.5, 1.5);
	_tmp6_ = _tmp5_;
	_g_object_unref0 (_tmp6_);
	_tmp7_ = x;
	_tmp8_ = y;
	_tmp9_ = shmup_warz_addPosition (entity, _tmp7_, _tmp8_);
	_tmp10_ = _tmp9_;
	_g_object_unref0 (_tmp10_);
	_tmp11_ = shmup_warz_addVelocity (entity, (gdouble) 0, (gdouble) (-800));
	_tmp12_ = _tmp11_;
	_g_object_unref0 (_tmp12_);
	_tmp13_ = shmup_warz_addTint (entity, 0xAD, 0xFF, 0x2F, 255);
	_tmp14_ = _tmp13_;
	_g_object_unref0 (_tmp14_);
	_tmp15_ = shmup_warz_addColorTween (entity, r, m, s, g, m, s, b, m, s, a, m, s, TRUE, TRUE, TRUE, TRUE, TRUE);
	_tmp16_ = _tmp15_;
	_g_object_unref0 (_tmp16_);
	_tmp17_ = shmup_warz_addBounds (entity, (gdouble) 5);
	_tmp18_ = _tmp17_;
	_g_object_unref0 (_tmp18_);
	_tmp19_ = shmup_warz_addExpires (entity, (gdouble) 1);
	_tmp20_ = _tmp19_;
	_g_object_unref0 (_tmp20_);
	_tmp21_ = shmup_warz_addLayer (entity, (gint) SHMUP_WARZ_LAYER_BULLET);
	_tmp22_ = _tmp21_;
	_g_object_unref0 (_tmp22_);
	_tmp23_ = string_to_string (SHMUP_WARZ_RES);
	_tmp24_ = g_strconcat (_tmp23_, "/images/bullet.png", NULL);
	_tmp25_ = _tmp24_;
	_tmp26_ = shmup_warz_addResource (entity, _tmp25_, NULL, FALSE);
	_tmp27_ = _tmp26_;
	_g_object_unref0 (_tmp27_);
	_g_free0 (_tmp25_);
	_tmp28_ = shmup_warz_addSoundEffect (entity, (gint) SHMUP_WARZ_EFFECT_PEW);
	_tmp29_ = _tmp28_;
	_g_object_unref0 (_tmp29_);
	result = entity;
	return result;
}


/**
    *  Create Particle
    */
EntitasEntity* shmup_warz_createParticle (gdouble x, gdouble y) {
	EntitasEntity* result = NULL;
	gdouble radians = 0.0;
	GRand* _tmp0_ = NULL;
	GRand* _tmp1_ = NULL;
	gdouble _tmp2_ = 0.0;
	gint32 magnitude = 0;
	GRand* _tmp3_ = NULL;
	GRand* _tmp4_ = NULL;
	gint32 _tmp5_ = 0;
	gdouble velocityX = 0.0;
	gdouble _tmp6_ = 0.0;
	gdouble velocityY = 0.0;
	gdouble _tmp7_ = 0.0;
	gdouble scale = 0.0;
	GRand* _tmp8_ = NULL;
	GRand* _tmp9_ = NULL;
	gdouble _tmp10_ = 0.0;
	EntitasEntity* entity = NULL;
	EntitasWorld* _tmp11_ = NULL;
	EntitasWorld* _tmp12_ = NULL;
	EntitasEntity* _tmp13_ = NULL;
	gdouble _tmp14_ = 0.0;
	gdouble _tmp15_ = 0.0;
	EntitasEntity* _tmp16_ = NULL;
	EntitasEntity* _tmp17_ = NULL;
	EntitasEntity* _tmp18_ = NULL;
	EntitasEntity* _tmp19_ = NULL;
	EntitasEntity* _tmp20_ = NULL;
	EntitasEntity* _tmp21_ = NULL;
	EntitasEntity* _tmp22_ = NULL;
	EntitasEntity* _tmp23_ = NULL;
	EntitasEntity* _tmp24_ = NULL;
	EntitasEntity* _tmp25_ = NULL;
	EntitasEntity* _tmp26_ = NULL;
	EntitasEntity* _tmp27_ = NULL;
	const gchar* _tmp28_ = NULL;
	gchar* _tmp29_ = NULL;
	gchar* _tmp30_ = NULL;
	EntitasEntity* _tmp31_ = NULL;
	EntitasEntity* _tmp32_ = NULL;
	_tmp0_ = entitas_world_get_random ();
	_tmp1_ = _tmp0_;
	_tmp2_ = g_rand_double (_tmp1_);
	radians = _tmp2_ * SHMUP_WARZ_Tau;
	_tmp3_ = entitas_world_get_random ();
	_tmp4_ = _tmp3_;
	_tmp5_ = g_rand_int_range (_tmp4_, (gint32) 0, (gint32) 200);
	magnitude = _tmp5_;
	_tmp6_ = cos (radians);
	velocityX = magnitude * _tmp6_;
	_tmp7_ = sin (radians);
	velocityY = magnitude * _tmp7_;
	_tmp8_ = entitas_world_get_random ();
	_tmp9_ = _tmp8_;
	_tmp10_ = g_rand_double_range (_tmp9_, 0.1, 1.0);
	scale = _tmp10_;
	_tmp11_ = entitas_world_get_instance ();
	_tmp12_ = _tmp11_;
	_tmp13_ = entitas_world_createEntity (_tmp12_, "particle");
	entity = _tmp13_;
	_tmp14_ = x;
	_tmp15_ = y;
	_tmp16_ = shmup_warz_addPosition (entity, _tmp14_, _tmp15_);
	_tmp17_ = _tmp16_;
	_g_object_unref0 (_tmp17_);
	_tmp18_ = shmup_warz_addVelocity (entity, velocityX, velocityY);
	_tmp19_ = _tmp18_;
	_g_object_unref0 (_tmp19_);
	_tmp20_ = shmup_warz_addExpires (entity, (gdouble) 1);
	_tmp21_ = _tmp20_;
	_g_object_unref0 (_tmp21_);
	_tmp22_ = shmup_warz_addLayer (entity, (gint) SHMUP_WARZ_LAYER_PARTICLE);
	_tmp23_ = _tmp22_;
	_g_object_unref0 (_tmp23_);
	_tmp24_ = shmup_warz_addScale (entity, scale, scale);
	_tmp25_ = _tmp24_;
	_g_object_unref0 (_tmp25_);
	_tmp26_ = shmup_warz_addTint (entity, 0xFA, 0xFA, 0xD2, 255);
	_tmp27_ = _tmp26_;
	_g_object_unref0 (_tmp27_);
	_tmp28_ = string_to_string (SHMUP_WARZ_RES);
	_tmp29_ = g_strconcat (_tmp28_, "/images/star.png", NULL);
	_tmp30_ = _tmp29_;
	_tmp31_ = shmup_warz_addResource (entity, _tmp30_, NULL, FALSE);
	_tmp32_ = _tmp31_;
	_g_object_unref0 (_tmp32_);
	_g_free0 (_tmp30_);
	result = entity;
	return result;
}


/**
    *  Create Explosion
    */
EntitasEntity* shmup_warz_createExplosion (gdouble x, gdouble y) {
	EntitasEntity* result = NULL;
	gdouble r = 0.0;
	gdouble g = 0.0;
	gdouble b = 0.0;
	gdouble m = 0.0;
	gdouble a = 0.0;
	gdouble s = 0.0;
	EntitasEntity* entity = NULL;
	EntitasWorld* _tmp0_ = NULL;
	EntitasWorld* _tmp1_ = NULL;
	EntitasEntity* _tmp2_ = NULL;
	gdouble _tmp3_ = 0.0;
	gdouble _tmp4_ = 0.0;
	EntitasEntity* _tmp5_ = NULL;
	EntitasEntity* _tmp6_ = NULL;
	EntitasEntity* _tmp7_ = NULL;
	EntitasEntity* _tmp8_ = NULL;
	EntitasEntity* _tmp9_ = NULL;
	EntitasEntity* _tmp10_ = NULL;
	EntitasEntity* _tmp11_ = NULL;
	EntitasEntity* _tmp12_ = NULL;
	EntitasEntity* _tmp13_ = NULL;
	EntitasEntity* _tmp14_ = NULL;
	EntitasEntity* _tmp15_ = NULL;
	EntitasEntity* _tmp16_ = NULL;
	EntitasEntity* _tmp17_ = NULL;
	EntitasEntity* _tmp18_ = NULL;
	EntitasEntity* _tmp19_ = NULL;
	EntitasEntity* _tmp20_ = NULL;
	const gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	EntitasEntity* _tmp24_ = NULL;
	EntitasEntity* _tmp25_ = NULL;
	r = (gdouble) 0xaa;
	g = (gdouble) 0xaa;
	b = (gdouble) 0xa2;
	m = 255.0;
	a = 255.0;
	s = 10.0;
	_tmp0_ = entitas_world_get_instance ();
	_tmp1_ = _tmp0_;
	_tmp2_ = entitas_world_createEntity (_tmp1_, "explosion");
	entity = _tmp2_;
	_tmp3_ = x;
	_tmp4_ = y;
	_tmp5_ = shmup_warz_addPosition (entity, _tmp3_, _tmp4_);
	_tmp6_ = _tmp5_;
	_g_object_unref0 (_tmp6_);
	_tmp7_ = shmup_warz_addExpires (entity, 1.0);
	_tmp8_ = _tmp7_;
	_g_object_unref0 (_tmp8_);
	_tmp9_ = shmup_warz_addLayer (entity, (gint) SHMUP_WARZ_LAYER_PARTICLE);
	_tmp10_ = _tmp9_;
	_g_object_unref0 (_tmp10_);
	_tmp11_ = shmup_warz_addScale (entity, 0.5, 0.5);
	_tmp12_ = _tmp11_;
	_g_object_unref0 (_tmp12_);
	_tmp13_ = shmup_warz_addSoundEffect (entity, (gint) SHMUP_WARZ_EFFECT_ASPLODE);
	_tmp14_ = _tmp13_;
	_g_object_unref0 (_tmp14_);
	_tmp15_ = shmup_warz_addScaleTween (entity, 0.001, 0.5, (gdouble) (-3), FALSE, TRUE);
	_tmp16_ = _tmp15_;
	_g_object_unref0 (_tmp16_);
	_tmp17_ = shmup_warz_addTint (entity, 0xFA, 0xFA, 0xD2, 255);
	_tmp18_ = _tmp17_;
	_g_object_unref0 (_tmp18_);
	_tmp19_ = shmup_warz_addColorTween (entity, r, m, s, g, m, s, b, m, s, a, m, s, TRUE, TRUE, TRUE, TRUE, TRUE);
	_tmp20_ = _tmp19_;
	_g_object_unref0 (_tmp20_);
	_tmp21_ = string_to_string (SHMUP_WARZ_RES);
	_tmp22_ = g_strconcat (_tmp21_, "/images/explosion.png", NULL);
	_tmp23_ = _tmp22_;
	_tmp24_ = shmup_warz_addResource (entity, _tmp23_, NULL, FALSE);
	_tmp25_ = _tmp24_;
	_g_object_unref0 (_tmp25_);
	_g_free0 (_tmp23_);
	result = entity;
	return result;
}


/**
    *  Create Small Explosion
    */
EntitasEntity* shmup_warz_createBang (gdouble x, gdouble y) {
	EntitasEntity* result = NULL;
	gdouble r = 0.0;
	gdouble g = 0.0;
	gdouble b = 0.0;
	gdouble m = 0.0;
	gdouble a = 0.0;
	gdouble s = 0.0;
	EntitasEntity* entity = NULL;
	EntitasWorld* _tmp0_ = NULL;
	EntitasWorld* _tmp1_ = NULL;
	EntitasEntity* _tmp2_ = NULL;
	gdouble _tmp3_ = 0.0;
	gdouble _tmp4_ = 0.0;
	EntitasEntity* _tmp5_ = NULL;
	EntitasEntity* _tmp6_ = NULL;
	EntitasEntity* _tmp7_ = NULL;
	EntitasEntity* _tmp8_ = NULL;
	EntitasEntity* _tmp9_ = NULL;
	EntitasEntity* _tmp10_ = NULL;
	EntitasEntity* _tmp11_ = NULL;
	EntitasEntity* _tmp12_ = NULL;
	EntitasEntity* _tmp13_ = NULL;
	EntitasEntity* _tmp14_ = NULL;
	EntitasEntity* _tmp15_ = NULL;
	EntitasEntity* _tmp16_ = NULL;
	EntitasEntity* _tmp17_ = NULL;
	EntitasEntity* _tmp18_ = NULL;
	EntitasEntity* _tmp19_ = NULL;
	EntitasEntity* _tmp20_ = NULL;
	const gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	EntitasEntity* _tmp24_ = NULL;
	EntitasEntity* _tmp25_ = NULL;
	r = (gdouble) 0xae;
	g = (gdouble) 0xa8;
	b = (gdouble) 0xaa;
	m = 255.0;
	a = 255.0;
	s = 10.0;
	_tmp0_ = entitas_world_get_instance ();
	_tmp1_ = _tmp0_;
	_tmp2_ = entitas_world_createEntity (_tmp1_, "explosion");
	entity = _tmp2_;
	_tmp3_ = x;
	_tmp4_ = y;
	_tmp5_ = shmup_warz_addPosition (entity, _tmp3_, _tmp4_);
	_tmp6_ = _tmp5_;
	_g_object_unref0 (_tmp6_);
	_tmp7_ = shmup_warz_addExpires (entity, 1.0);
	_tmp8_ = _tmp7_;
	_g_object_unref0 (_tmp8_);
	_tmp9_ = shmup_warz_addLayer (entity, (gint) SHMUP_WARZ_LAYER_PARTICLE);
	_tmp10_ = _tmp9_;
	_g_object_unref0 (_tmp10_);
	_tmp11_ = shmup_warz_addScale (entity, 1.0, 1.0);
	_tmp12_ = _tmp11_;
	_g_object_unref0 (_tmp12_);
	_tmp13_ = shmup_warz_addSoundEffect (entity, (gint) SHMUP_WARZ_EFFECT_SMALLASPLODE);
	_tmp14_ = _tmp13_;
	_g_object_unref0 (_tmp14_);
	_tmp15_ = shmup_warz_addScaleTween (entity, 0.001, 1.0, (gdouble) (-3), FALSE, TRUE);
	_tmp16_ = _tmp15_;
	_g_object_unref0 (_tmp16_);
	_tmp17_ = shmup_warz_addTint (entity, 0xEE, 0xE8, 0xAA, 255);
	_tmp18_ = _tmp17_;
	_g_object_unref0 (_tmp18_);
	_tmp19_ = shmup_warz_addColorTween (entity, r, m, s, g, m, s, b, m, s, a, m, s, TRUE, TRUE, TRUE, TRUE, TRUE);
	_tmp20_ = _tmp19_;
	_g_object_unref0 (_tmp20_);
	_tmp21_ = string_to_string (SHMUP_WARZ_RES);
	_tmp22_ = g_strconcat (_tmp21_, "/images/bang.png", NULL);
	_tmp23_ = _tmp22_;
	_tmp24_ = shmup_warz_addResource (entity, _tmp23_, NULL, FALSE);
	_tmp25_ = _tmp24_;
	_g_object_unref0 (_tmp25_);
	_g_free0 (_tmp23_);
	result = entity;
	return result;
}


/**
    *  Create Small Enemy
    */
EntitasEntity* shmup_warz_createEnemy1 (void) {
	EntitasEntity* result = NULL;
	gint32 x = 0;
	GRand* _tmp0_ = NULL;
	GRand* _tmp1_ = NULL;
	gint32 _tmp2_ = 0;
	gint y = 0;
	EntitasEntity* entity = NULL;
	EntitasWorld* _tmp3_ = NULL;
	EntitasWorld* _tmp4_ = NULL;
	EntitasEntity* _tmp5_ = NULL;
	EntitasEntity* _tmp6_ = NULL;
	EntitasEntity* _tmp7_ = NULL;
	EntitasEntity* _tmp8_ = NULL;
	EntitasEntity* _tmp9_ = NULL;
	EntitasEntity* _tmp10_ = NULL;
	EntitasEntity* _tmp11_ = NULL;
	EntitasEntity* _tmp12_ = NULL;
	EntitasEntity* _tmp13_ = NULL;
	EntitasEntity* _tmp14_ = NULL;
	EntitasEntity* _tmp15_ = NULL;
	EntitasEntity* _tmp16_ = NULL;
	EntitasEntity* _tmp17_ = NULL;
	EntitasEntity* _tmp18_ = NULL;
	EntitasEntity* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	EntitasEntity* _tmp23_ = NULL;
	EntitasEntity* _tmp24_ = NULL;
	_tmp0_ = entitas_world_get_random ();
	_tmp1_ = _tmp0_;
	_tmp2_ = g_rand_int_range (_tmp1_, (gint32) 0, (gint32) SHMUP_WARZ_SCREEN_WIDTH);
	x = _tmp2_;
	y = (SHMUP_WARZ_SCREEN_HEIGHT / 2) - 200;
	_tmp3_ = entitas_world_get_instance ();
	_tmp4_ = _tmp3_;
	_tmp5_ = entitas_world_createEntity (_tmp4_, "enemy1");
	entity = _tmp5_;
	_tmp6_ = shmup_warz_setEnemy (entity, TRUE);
	_tmp7_ = _tmp6_;
	_g_object_unref0 (_tmp7_);
	_tmp8_ = shmup_warz_addBounds (entity, (gdouble) 20);
	_tmp9_ = _tmp8_;
	_g_object_unref0 (_tmp9_);
	_tmp10_ = shmup_warz_addHealth (entity, (gdouble) 10, (gdouble) 10);
	_tmp11_ = _tmp10_;
	_g_object_unref0 (_tmp11_);
	_tmp12_ = shmup_warz_addVelocity (entity, (gdouble) 0, (gdouble) 40);
	_tmp13_ = _tmp12_;
	_g_object_unref0 (_tmp13_);
	_tmp14_ = shmup_warz_addLayer (entity, (gint) SHMUP_WARZ_LAYER_ACTORS_1);
	_tmp15_ = _tmp14_;
	_g_object_unref0 (_tmp15_);
	_tmp16_ = shmup_warz_addPosition (entity, (gdouble) x, (gdouble) y);
	_tmp17_ = _tmp16_;
	_g_object_unref0 (_tmp17_);
	_tmp18_ = shmup_warz_addText (entity, "", NULL);
	_tmp19_ = _tmp18_;
	_g_object_unref0 (_tmp19_);
	_tmp20_ = string_to_string (SHMUP_WARZ_RES);
	_tmp21_ = g_strconcat (_tmp20_, "/images/enemy1.png", NULL);
	_tmp22_ = _tmp21_;
	_tmp23_ = shmup_warz_addResource (entity, _tmp22_, NULL, FALSE);
	_tmp24_ = _tmp23_;
	_g_object_unref0 (_tmp24_);
	_g_free0 (_tmp22_);
	result = entity;
	return result;
}


/**
    *  Create Medium Sized Enemy
    */
EntitasEntity* shmup_warz_createEnemy2 (void) {
	EntitasEntity* result = NULL;
	gint32 x = 0;
	GRand* _tmp0_ = NULL;
	GRand* _tmp1_ = NULL;
	gint32 _tmp2_ = 0;
	gint y = 0;
	EntitasEntity* entity = NULL;
	EntitasWorld* _tmp3_ = NULL;
	EntitasWorld* _tmp4_ = NULL;
	EntitasEntity* _tmp5_ = NULL;
	EntitasEntity* _tmp6_ = NULL;
	EntitasEntity* _tmp7_ = NULL;
	EntitasEntity* _tmp8_ = NULL;
	EntitasEntity* _tmp9_ = NULL;
	EntitasEntity* _tmp10_ = NULL;
	EntitasEntity* _tmp11_ = NULL;
	EntitasEntity* _tmp12_ = NULL;
	EntitasEntity* _tmp13_ = NULL;
	EntitasEntity* _tmp14_ = NULL;
	EntitasEntity* _tmp15_ = NULL;
	EntitasEntity* _tmp16_ = NULL;
	EntitasEntity* _tmp17_ = NULL;
	EntitasEntity* _tmp18_ = NULL;
	EntitasEntity* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	EntitasEntity* _tmp23_ = NULL;
	EntitasEntity* _tmp24_ = NULL;
	_tmp0_ = entitas_world_get_random ();
	_tmp1_ = _tmp0_;
	_tmp2_ = g_rand_int_range (_tmp1_, (gint32) 0, (gint32) SHMUP_WARZ_SCREEN_WIDTH);
	x = _tmp2_;
	y = (SHMUP_WARZ_SCREEN_HEIGHT / 2) - 100;
	_tmp3_ = entitas_world_get_instance ();
	_tmp4_ = _tmp3_;
	_tmp5_ = entitas_world_createEntity (_tmp4_, "enemy2");
	entity = _tmp5_;
	_tmp6_ = shmup_warz_setEnemy (entity, TRUE);
	_tmp7_ = _tmp6_;
	_g_object_unref0 (_tmp7_);
	_tmp8_ = shmup_warz_addBounds (entity, (gdouble) 40);
	_tmp9_ = _tmp8_;
	_g_object_unref0 (_tmp9_);
	_tmp10_ = shmup_warz_addHealth (entity, (gdouble) 20, (gdouble) 20);
	_tmp11_ = _tmp10_;
	_g_object_unref0 (_tmp11_);
	_tmp12_ = shmup_warz_addVelocity (entity, (gdouble) 0, (gdouble) 30);
	_tmp13_ = _tmp12_;
	_g_object_unref0 (_tmp13_);
	_tmp14_ = shmup_warz_addLayer (entity, (gint) SHMUP_WARZ_LAYER_ACTORS_2);
	_tmp15_ = _tmp14_;
	_g_object_unref0 (_tmp15_);
	_tmp16_ = shmup_warz_addPosition (entity, (gdouble) x, (gdouble) y);
	_tmp17_ = _tmp16_;
	_g_object_unref0 (_tmp17_);
	_tmp18_ = shmup_warz_addText (entity, "", NULL);
	_tmp19_ = _tmp18_;
	_g_object_unref0 (_tmp19_);
	_tmp20_ = string_to_string (SHMUP_WARZ_RES);
	_tmp21_ = g_strconcat (_tmp20_, "/images/enemy2.png", NULL);
	_tmp22_ = _tmp21_;
	_tmp23_ = shmup_warz_addResource (entity, _tmp22_, NULL, FALSE);
	_tmp24_ = _tmp23_;
	_g_object_unref0 (_tmp24_);
	_g_free0 (_tmp22_);
	result = entity;
	return result;
}


/**
    *  Create Large Enemy
    */
EntitasEntity* shmup_warz_createEnemy3 (void) {
	EntitasEntity* result = NULL;
	gint32 x = 0;
	GRand* _tmp0_ = NULL;
	GRand* _tmp1_ = NULL;
	gint32 _tmp2_ = 0;
	gint y = 0;
	EntitasEntity* entity = NULL;
	EntitasWorld* _tmp3_ = NULL;
	EntitasWorld* _tmp4_ = NULL;
	EntitasEntity* _tmp5_ = NULL;
	EntitasEntity* _tmp6_ = NULL;
	EntitasEntity* _tmp7_ = NULL;
	EntitasEntity* _tmp8_ = NULL;
	EntitasEntity* _tmp9_ = NULL;
	EntitasEntity* _tmp10_ = NULL;
	EntitasEntity* _tmp11_ = NULL;
	EntitasEntity* _tmp12_ = NULL;
	EntitasEntity* _tmp13_ = NULL;
	EntitasEntity* _tmp14_ = NULL;
	EntitasEntity* _tmp15_ = NULL;
	EntitasEntity* _tmp16_ = NULL;
	EntitasEntity* _tmp17_ = NULL;
	EntitasEntity* _tmp18_ = NULL;
	EntitasEntity* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	EntitasEntity* _tmp23_ = NULL;
	EntitasEntity* _tmp24_ = NULL;
	_tmp0_ = entitas_world_get_random ();
	_tmp1_ = _tmp0_;
	_tmp2_ = g_rand_int_range (_tmp1_, (gint32) 0, (gint32) SHMUP_WARZ_SCREEN_WIDTH);
	x = _tmp2_;
	y = (SHMUP_WARZ_SCREEN_HEIGHT / 2) - 50;
	_tmp3_ = entitas_world_get_instance ();
	_tmp4_ = _tmp3_;
	_tmp5_ = entitas_world_createEntity (_tmp4_, "enemy3");
	entity = _tmp5_;
	_tmp6_ = shmup_warz_setEnemy (entity, TRUE);
	_tmp7_ = _tmp6_;
	_g_object_unref0 (_tmp7_);
	_tmp8_ = shmup_warz_addBounds (entity, (gdouble) 70);
	_tmp9_ = _tmp8_;
	_g_object_unref0 (_tmp9_);
	_tmp10_ = shmup_warz_addHealth (entity, (gdouble) 60, (gdouble) 60);
	_tmp11_ = _tmp10_;
	_g_object_unref0 (_tmp11_);
	_tmp12_ = shmup_warz_addVelocity (entity, (gdouble) 0, (gdouble) 20);
	_tmp13_ = _tmp12_;
	_g_object_unref0 (_tmp13_);
	_tmp14_ = shmup_warz_addLayer (entity, (gint) SHMUP_WARZ_LAYER_ACTORS_3);
	_tmp15_ = _tmp14_;
	_g_object_unref0 (_tmp15_);
	_tmp16_ = shmup_warz_addPosition (entity, (gdouble) x, (gdouble) y);
	_tmp17_ = _tmp16_;
	_g_object_unref0 (_tmp17_);
	_tmp18_ = shmup_warz_addText (entity, "", NULL);
	_tmp19_ = _tmp18_;
	_g_object_unref0 (_tmp19_);
	_tmp20_ = string_to_string (SHMUP_WARZ_RES);
	_tmp21_ = g_strconcat (_tmp20_, "/images/enemy3.png", NULL);
	_tmp22_ = _tmp21_;
	_tmp23_ = shmup_warz_addResource (entity, _tmp22_, NULL, FALSE);
	_tmp24_ = _tmp23_;
	_g_object_unref0 (_tmp24_);
	_g_free0 (_tmp22_);
	result = entity;
	return result;
}



