/* Game.c generated by valac 0.34.4, the Vala compiler
 * generated from Game.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <Bosco.h>
#include <Entitas.h>
#include <SDL2/SDL_ttf.h>
#include <float.h>
#include <math.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_events.h>
#include <SDL2/SDL_keyboard.h>
#include <SDL2/SDL_mouse.h>
#include <SDL2/SDL_image.h>


#define SHMUP_WARZ_TYPE_GAME (shmup_warz_game_get_type ())
#define SHMUP_WARZ_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGame))
#define SHMUP_WARZ_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))
#define SHMUP_WARZ_IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))

typedef struct _ShmupWarzGame ShmupWarzGame;
typedef struct _ShmupWarzGameClass ShmupWarzGameClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ShmupWarzGamePrivate ShmupWarzGamePrivate;

#define SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM (shmup_warz_player_input_system_get_type ())
#define SHMUP_WARZ_PLAYER_INPUT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM, ShmupWarzPlayerInputSystem))
#define SHMUP_WARZ_PLAYER_INPUT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM, ShmupWarzPlayerInputSystemClass))
#define SHMUP_WARZ_IS_PLAYER_INPUT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM))
#define SHMUP_WARZ_IS_PLAYER_INPUT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM))
#define SHMUP_WARZ_PLAYER_INPUT_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM, ShmupWarzPlayerInputSystemClass))

typedef struct _ShmupWarzPlayerInputSystem ShmupWarzPlayerInputSystem;
typedef struct _ShmupWarzPlayerInputSystemClass ShmupWarzPlayerInputSystemClass;
#define _TTF_CloseFont0(var) ((var == NULL) ? NULL : (var = (TTF_CloseFont (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define SHMUP_WARZ_TYPE_MOVEMENT_SYSTEM (shmup_warz_movement_system_get_type ())
#define SHMUP_WARZ_MOVEMENT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_MOVEMENT_SYSTEM, ShmupWarzMovementSystem))
#define SHMUP_WARZ_MOVEMENT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_MOVEMENT_SYSTEM, ShmupWarzMovementSystemClass))
#define SHMUP_WARZ_IS_MOVEMENT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_MOVEMENT_SYSTEM))
#define SHMUP_WARZ_IS_MOVEMENT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_MOVEMENT_SYSTEM))
#define SHMUP_WARZ_MOVEMENT_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_MOVEMENT_SYSTEM, ShmupWarzMovementSystemClass))

typedef struct _ShmupWarzMovementSystem ShmupWarzMovementSystem;
typedef struct _ShmupWarzMovementSystemClass ShmupWarzMovementSystemClass;

#define SHMUP_WARZ_TYPE_SOUND_EFFECT_SYSTEM (shmup_warz_sound_effect_system_get_type ())
#define SHMUP_WARZ_SOUND_EFFECT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_SOUND_EFFECT_SYSTEM, ShmupWarzSoundEffectSystem))
#define SHMUP_WARZ_SOUND_EFFECT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_SOUND_EFFECT_SYSTEM, ShmupWarzSoundEffectSystemClass))
#define SHMUP_WARZ_IS_SOUND_EFFECT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_SOUND_EFFECT_SYSTEM))
#define SHMUP_WARZ_IS_SOUND_EFFECT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_SOUND_EFFECT_SYSTEM))
#define SHMUP_WARZ_SOUND_EFFECT_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_SOUND_EFFECT_SYSTEM, ShmupWarzSoundEffectSystemClass))

typedef struct _ShmupWarzSoundEffectSystem ShmupWarzSoundEffectSystem;
typedef struct _ShmupWarzSoundEffectSystemClass ShmupWarzSoundEffectSystemClass;

#define SHMUP_WARZ_TYPE_COLLISION_SYSTEM (shmup_warz_collision_system_get_type ())
#define SHMUP_WARZ_COLLISION_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_COLLISION_SYSTEM, ShmupWarzCollisionSystem))
#define SHMUP_WARZ_COLLISION_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_COLLISION_SYSTEM, ShmupWarzCollisionSystemClass))
#define SHMUP_WARZ_IS_COLLISION_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_COLLISION_SYSTEM))
#define SHMUP_WARZ_IS_COLLISION_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_COLLISION_SYSTEM))
#define SHMUP_WARZ_COLLISION_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_COLLISION_SYSTEM, ShmupWarzCollisionSystemClass))

typedef struct _ShmupWarzCollisionSystem ShmupWarzCollisionSystem;
typedef struct _ShmupWarzCollisionSystemClass ShmupWarzCollisionSystemClass;

#define SHMUP_WARZ_TYPE_EXPIRING_SYSTEM (shmup_warz_expiring_system_get_type ())
#define SHMUP_WARZ_EXPIRING_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_EXPIRING_SYSTEM, ShmupWarzExpiringSystem))
#define SHMUP_WARZ_EXPIRING_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_EXPIRING_SYSTEM, ShmupWarzExpiringSystemClass))
#define SHMUP_WARZ_IS_EXPIRING_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_EXPIRING_SYSTEM))
#define SHMUP_WARZ_IS_EXPIRING_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_EXPIRING_SYSTEM))
#define SHMUP_WARZ_EXPIRING_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_EXPIRING_SYSTEM, ShmupWarzExpiringSystemClass))

typedef struct _ShmupWarzExpiringSystem ShmupWarzExpiringSystem;
typedef struct _ShmupWarzExpiringSystemClass ShmupWarzExpiringSystemClass;

#define SHMUP_WARZ_TYPE_ENTITY_SPAWNING_TIMER_SYSTEM (shmup_warz_entity_spawning_timer_system_get_type ())
#define SHMUP_WARZ_ENTITY_SPAWNING_TIMER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_ENTITY_SPAWNING_TIMER_SYSTEM, ShmupWarzEntitySpawningTimerSystem))
#define SHMUP_WARZ_ENTITY_SPAWNING_TIMER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_ENTITY_SPAWNING_TIMER_SYSTEM, ShmupWarzEntitySpawningTimerSystemClass))
#define SHMUP_WARZ_IS_ENTITY_SPAWNING_TIMER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_ENTITY_SPAWNING_TIMER_SYSTEM))
#define SHMUP_WARZ_IS_ENTITY_SPAWNING_TIMER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_ENTITY_SPAWNING_TIMER_SYSTEM))
#define SHMUP_WARZ_ENTITY_SPAWNING_TIMER_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_ENTITY_SPAWNING_TIMER_SYSTEM, ShmupWarzEntitySpawningTimerSystemClass))

typedef struct _ShmupWarzEntitySpawningTimerSystem ShmupWarzEntitySpawningTimerSystem;
typedef struct _ShmupWarzEntitySpawningTimerSystemClass ShmupWarzEntitySpawningTimerSystemClass;

#define SHMUP_WARZ_TYPE_COLOR_TWEEN_SYSTEM (shmup_warz_color_tween_system_get_type ())
#define SHMUP_WARZ_COLOR_TWEEN_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_COLOR_TWEEN_SYSTEM, ShmupWarzColorTweenSystem))
#define SHMUP_WARZ_COLOR_TWEEN_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_COLOR_TWEEN_SYSTEM, ShmupWarzColorTweenSystemClass))
#define SHMUP_WARZ_IS_COLOR_TWEEN_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_COLOR_TWEEN_SYSTEM))
#define SHMUP_WARZ_IS_COLOR_TWEEN_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_COLOR_TWEEN_SYSTEM))
#define SHMUP_WARZ_COLOR_TWEEN_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_COLOR_TWEEN_SYSTEM, ShmupWarzColorTweenSystemClass))

typedef struct _ShmupWarzColorTweenSystem ShmupWarzColorTweenSystem;
typedef struct _ShmupWarzColorTweenSystemClass ShmupWarzColorTweenSystemClass;

#define SHMUP_WARZ_TYPE_SCALE_TWEEN_SYSTEM (shmup_warz_scale_tween_system_get_type ())
#define SHMUP_WARZ_SCALE_TWEEN_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_SCALE_TWEEN_SYSTEM, ShmupWarzScaleTweenSystem))
#define SHMUP_WARZ_SCALE_TWEEN_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_SCALE_TWEEN_SYSTEM, ShmupWarzScaleTweenSystemClass))
#define SHMUP_WARZ_IS_SCALE_TWEEN_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_SCALE_TWEEN_SYSTEM))
#define SHMUP_WARZ_IS_SCALE_TWEEN_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_SCALE_TWEEN_SYSTEM))
#define SHMUP_WARZ_SCALE_TWEEN_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_SCALE_TWEEN_SYSTEM, ShmupWarzScaleTweenSystemClass))

typedef struct _ShmupWarzScaleTweenSystem ShmupWarzScaleTweenSystem;
typedef struct _ShmupWarzScaleTweenSystemClass ShmupWarzScaleTweenSystemClass;

#define SHMUP_WARZ_TYPE_REMOVE_OFFSCREEN_SHIPS_SYSTEM (shmup_warz_remove_offscreen_ships_system_get_type ())
#define SHMUP_WARZ_REMOVE_OFFSCREEN_SHIPS_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_REMOVE_OFFSCREEN_SHIPS_SYSTEM, ShmupWarzRemoveOffscreenShipsSystem))
#define SHMUP_WARZ_REMOVE_OFFSCREEN_SHIPS_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_REMOVE_OFFSCREEN_SHIPS_SYSTEM, ShmupWarzRemoveOffscreenShipsSystemClass))
#define SHMUP_WARZ_IS_REMOVE_OFFSCREEN_SHIPS_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_REMOVE_OFFSCREEN_SHIPS_SYSTEM))
#define SHMUP_WARZ_IS_REMOVE_OFFSCREEN_SHIPS_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_REMOVE_OFFSCREEN_SHIPS_SYSTEM))
#define SHMUP_WARZ_REMOVE_OFFSCREEN_SHIPS_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_REMOVE_OFFSCREEN_SHIPS_SYSTEM, ShmupWarzRemoveOffscreenShipsSystemClass))

typedef struct _ShmupWarzRemoveOffscreenShipsSystem ShmupWarzRemoveOffscreenShipsSystem;
typedef struct _ShmupWarzRemoveOffscreenShipsSystemClass ShmupWarzRemoveOffscreenShipsSystemClass;

#define SHMUP_WARZ_TYPE_VIEW_MANAGER_SYSTEM (shmup_warz_view_manager_system_get_type ())
#define SHMUP_WARZ_VIEW_MANAGER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_VIEW_MANAGER_SYSTEM, ShmupWarzViewManagerSystem))
#define SHMUP_WARZ_VIEW_MANAGER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_VIEW_MANAGER_SYSTEM, ShmupWarzViewManagerSystemClass))
#define SHMUP_WARZ_IS_VIEW_MANAGER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_VIEW_MANAGER_SYSTEM))
#define SHMUP_WARZ_IS_VIEW_MANAGER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_VIEW_MANAGER_SYSTEM))
#define SHMUP_WARZ_VIEW_MANAGER_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_VIEW_MANAGER_SYSTEM, ShmupWarzViewManagerSystemClass))

typedef struct _ShmupWarzViewManagerSystem ShmupWarzViewManagerSystem;
typedef struct _ShmupWarzViewManagerSystemClass ShmupWarzViewManagerSystemClass;

#define SHMUP_WARZ_TYPE_RENDER_POSITION_SYSTEM (shmup_warz_render_position_system_get_type ())
#define SHMUP_WARZ_RENDER_POSITION_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_RENDER_POSITION_SYSTEM, ShmupWarzRenderPositionSystem))
#define SHMUP_WARZ_RENDER_POSITION_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_RENDER_POSITION_SYSTEM, ShmupWarzRenderPositionSystemClass))
#define SHMUP_WARZ_IS_RENDER_POSITION_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_RENDER_POSITION_SYSTEM))
#define SHMUP_WARZ_IS_RENDER_POSITION_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_RENDER_POSITION_SYSTEM))
#define SHMUP_WARZ_RENDER_POSITION_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_RENDER_POSITION_SYSTEM, ShmupWarzRenderPositionSystemClass))

typedef struct _ShmupWarzRenderPositionSystem ShmupWarzRenderPositionSystem;
typedef struct _ShmupWarzRenderPositionSystemClass ShmupWarzRenderPositionSystemClass;

#define SHMUP_WARZ_TYPE_HEALTH_RENDER_SYSTEM (shmup_warz_health_render_system_get_type ())
#define SHMUP_WARZ_HEALTH_RENDER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_HEALTH_RENDER_SYSTEM, ShmupWarzHealthRenderSystem))
#define SHMUP_WARZ_HEALTH_RENDER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_HEALTH_RENDER_SYSTEM, ShmupWarzHealthRenderSystemClass))
#define SHMUP_WARZ_IS_HEALTH_RENDER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_HEALTH_RENDER_SYSTEM))
#define SHMUP_WARZ_IS_HEALTH_RENDER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_HEALTH_RENDER_SYSTEM))
#define SHMUP_WARZ_HEALTH_RENDER_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_HEALTH_RENDER_SYSTEM, ShmupWarzHealthRenderSystemClass))

typedef struct _ShmupWarzHealthRenderSystem ShmupWarzHealthRenderSystem;
typedef struct _ShmupWarzHealthRenderSystemClass ShmupWarzHealthRenderSystemClass;

#define SHMUP_WARZ_TYPE_HUD_RENDER_SYSTEM (shmup_warz_hud_render_system_get_type ())
#define SHMUP_WARZ_HUD_RENDER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_HUD_RENDER_SYSTEM, ShmupWarzHudRenderSystem))
#define SHMUP_WARZ_HUD_RENDER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_HUD_RENDER_SYSTEM, ShmupWarzHudRenderSystemClass))
#define SHMUP_WARZ_IS_HUD_RENDER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_HUD_RENDER_SYSTEM))
#define SHMUP_WARZ_IS_HUD_RENDER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_HUD_RENDER_SYSTEM))
#define SHMUP_WARZ_HUD_RENDER_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_HUD_RENDER_SYSTEM, ShmupWarzHudRenderSystemClass))

typedef struct _ShmupWarzHudRenderSystem ShmupWarzHudRenderSystem;
typedef struct _ShmupWarzHudRenderSystemClass ShmupWarzHudRenderSystemClass;

#define SHMUP_WARZ_TYPE_DESTROY_SYSTEM (shmup_warz_destroy_system_get_type ())
#define SHMUP_WARZ_DESTROY_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_DESTROY_SYSTEM, ShmupWarzDestroySystem))
#define SHMUP_WARZ_DESTROY_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_DESTROY_SYSTEM, ShmupWarzDestroySystemClass))
#define SHMUP_WARZ_IS_DESTROY_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_DESTROY_SYSTEM))
#define SHMUP_WARZ_IS_DESTROY_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_DESTROY_SYSTEM))
#define SHMUP_WARZ_DESTROY_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_DESTROY_SYSTEM, ShmupWarzDestroySystemClass))

typedef struct _ShmupWarzDestroySystem ShmupWarzDestroySystem;
typedef struct _ShmupWarzDestroySystemClass ShmupWarzDestroySystemClass;

struct _ShmupWarzGame {
	BoscoAbstractGame parent_instance;
	ShmupWarzGamePrivate * priv;
	EntitasWorld* world;
	ShmupWarzPlayerInputSystem* player;
	TTF_Font* arial;
};

struct _ShmupWarzGameClass {
	BoscoAbstractGameClass parent_class;
};


static gpointer shmup_warz_game_parent_class = NULL;

void _vala_main (gchar** args, int args_length1);
GType shmup_warz_game_get_type (void) G_GNUC_CONST;
ShmupWarzGame* shmup_warz_game_new (void);
ShmupWarzGame* shmup_warz_game_construct (GType object_type);
#define SHMUP_WARZ_SCREEN_WIDTH 800
#define SHMUP_WARZ_SCREEN_HEIGHT 600
#define SHMUP_WARZ_RES "/usr/local/share/shmupwarz"
GType shmup_warz_player_input_system_get_type (void) G_GNUC_CONST;
enum  {
	SHMUP_WARZ_GAME_DUMMY_PROPERTY
};
void shmup_warz_initializePools (void);
static void shmup_warz_game_real_Update (BoscoAbstractGame* base, gdouble delta);
static gboolean shmup_warz_game_real_Initialize (BoscoAbstractGame* base);
ShmupWarzMovementSystem* shmup_warz_movement_system_new (ShmupWarzGame* game);
ShmupWarzMovementSystem* shmup_warz_movement_system_construct (GType object_type, ShmupWarzGame* game);
GType shmup_warz_movement_system_get_type (void) G_GNUC_CONST;
ShmupWarzPlayerInputSystem* shmup_warz_player_input_system_new (ShmupWarzGame* game);
ShmupWarzPlayerInputSystem* shmup_warz_player_input_system_construct (GType object_type, ShmupWarzGame* game);
ShmupWarzSoundEffectSystem* shmup_warz_sound_effect_system_new (ShmupWarzGame* game);
ShmupWarzSoundEffectSystem* shmup_warz_sound_effect_system_construct (GType object_type, ShmupWarzGame* game);
GType shmup_warz_sound_effect_system_get_type (void) G_GNUC_CONST;
ShmupWarzCollisionSystem* shmup_warz_collision_system_new (ShmupWarzGame* game);
ShmupWarzCollisionSystem* shmup_warz_collision_system_construct (GType object_type, ShmupWarzGame* game);
GType shmup_warz_collision_system_get_type (void) G_GNUC_CONST;
ShmupWarzExpiringSystem* shmup_warz_expiring_system_new (ShmupWarzGame* game);
ShmupWarzExpiringSystem* shmup_warz_expiring_system_construct (GType object_type, ShmupWarzGame* game);
GType shmup_warz_expiring_system_get_type (void) G_GNUC_CONST;
ShmupWarzEntitySpawningTimerSystem* shmup_warz_entity_spawning_timer_system_new (ShmupWarzGame* game);
ShmupWarzEntitySpawningTimerSystem* shmup_warz_entity_spawning_timer_system_construct (GType object_type, ShmupWarzGame* game);
GType shmup_warz_entity_spawning_timer_system_get_type (void) G_GNUC_CONST;
ShmupWarzColorTweenSystem* shmup_warz_color_tween_system_new (ShmupWarzGame* game);
ShmupWarzColorTweenSystem* shmup_warz_color_tween_system_construct (GType object_type, ShmupWarzGame* game);
GType shmup_warz_color_tween_system_get_type (void) G_GNUC_CONST;
ShmupWarzScaleTweenSystem* shmup_warz_scale_tween_system_new (ShmupWarzGame* game);
ShmupWarzScaleTweenSystem* shmup_warz_scale_tween_system_construct (GType object_type, ShmupWarzGame* game);
GType shmup_warz_scale_tween_system_get_type (void) G_GNUC_CONST;
ShmupWarzRemoveOffscreenShipsSystem* shmup_warz_remove_offscreen_ships_system_new (ShmupWarzGame* game);
ShmupWarzRemoveOffscreenShipsSystem* shmup_warz_remove_offscreen_ships_system_construct (GType object_type, ShmupWarzGame* game);
GType shmup_warz_remove_offscreen_ships_system_get_type (void) G_GNUC_CONST;
ShmupWarzViewManagerSystem* shmup_warz_view_manager_system_new (ShmupWarzGame* game);
ShmupWarzViewManagerSystem* shmup_warz_view_manager_system_construct (GType object_type, ShmupWarzGame* game);
GType shmup_warz_view_manager_system_get_type (void) G_GNUC_CONST;
ShmupWarzRenderPositionSystem* shmup_warz_render_position_system_new (ShmupWarzGame* game);
ShmupWarzRenderPositionSystem* shmup_warz_render_position_system_construct (GType object_type, ShmupWarzGame* game);
GType shmup_warz_render_position_system_get_type (void) G_GNUC_CONST;
ShmupWarzHealthRenderSystem* shmup_warz_health_render_system_new (ShmupWarzGame* game);
ShmupWarzHealthRenderSystem* shmup_warz_health_render_system_construct (GType object_type, ShmupWarzGame* game);
GType shmup_warz_health_render_system_get_type (void) G_GNUC_CONST;
ShmupWarzHudRenderSystem* shmup_warz_hud_render_system_new (ShmupWarzGame* game);
ShmupWarzHudRenderSystem* shmup_warz_hud_render_system_construct (GType object_type, ShmupWarzGame* game);
GType shmup_warz_hud_render_system_get_type (void) G_GNUC_CONST;
ShmupWarzDestroySystem* shmup_warz_destroy_system_new (ShmupWarzGame* game);
ShmupWarzDestroySystem* shmup_warz_destroy_system_construct (GType object_type, ShmupWarzGame* game);
GType shmup_warz_destroy_system_get_type (void) G_GNUC_CONST;
EntitasEntity* shmup_warz_createBackground (void);
EntitasEntity* shmup_warz_createPlayer (void);
static void shmup_warz_game_real_Events (BoscoAbstractGame* base, SDL_Event e);
void shmup_warz_player_input_system_onMouseEvent (ShmupWarzPlayerInputSystem* self, SDL_EventType e, gint x, gint y);
static void shmup_warz_game_real_Dispose (BoscoAbstractGame* base);
static void shmup_warz_game_finalize (GObject* obj);

extern const gchar* SHMUP_WARZ_components[23];

/**
 * Game.gs
 *
 * 
 *
 */
void _vala_main (gchar** args, int args_length1) {
	ShmupWarzGame* game = NULL;
	ShmupWarzGame* _tmp0_ = NULL;
	_tmp0_ = shmup_warz_game_new ();
	game = _tmp0_;
	bosco_abstract_game_Run ((BoscoAbstractGame*) game);
	_g_object_unref0 (game);
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	_vala_main (argv, argc);
	return 0;
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


ShmupWarzGame* shmup_warz_game_construct (GType object_type) {
	ShmupWarzGame * self = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	self = (ShmupWarzGame*) bosco_abstract_game_construct (object_type);
	shmup_warz_initializePools ();
	_tmp0_ = g_strdup ("Shmup Warz");
	_g_free0 (((BoscoAbstractGame*) self)->name);
	((BoscoAbstractGame*) self)->name = _tmp0_;
	((BoscoAbstractGame*) self)->width = SHMUP_WARZ_SCREEN_WIDTH;
	((BoscoAbstractGame*) self)->height = SHMUP_WARZ_SCREEN_HEIGHT;
	((BoscoAbstractGame*) self)->running = TRUE;
	_tmp1_ = string_to_string (SHMUP_WARZ_RES);
	_tmp2_ = g_strconcat (_tmp1_, "/fonts/TitanOne-Regular.ttf", NULL);
	_g_free0 (((BoscoAbstractGame*) self)->defaultFont);
	((BoscoAbstractGame*) self)->defaultFont = _tmp2_;
	return self;
}


ShmupWarzGame* shmup_warz_game_new (void) {
	return shmup_warz_game_construct (SHMUP_WARZ_TYPE_GAME);
}


/**
        *  OnLoop
        *
        * Process the game engine
        */
static void shmup_warz_game_real_Update (BoscoAbstractGame* base, gdouble delta) {
	ShmupWarzGame * self;
	EntitasWorld* _tmp0_ = NULL;
	self = (ShmupWarzGame*) base;
	_tmp0_ = self->world;
	entitas_world_execute (_tmp0_);
}


/**
        *  OnInit
        *
        * load assets
        */
static gboolean shmup_warz_game_real_Initialize (BoscoAbstractGame* base) {
	ShmupWarzGame * self;
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	self = (ShmupWarzGame*) base;
	_tmp0_ = BOSCO_ABSTRACT_GAME_CLASS (shmup_warz_game_parent_class)->Initialize (G_TYPE_CHECK_INSTANCE_CAST (self, BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGame));
	if (_tmp0_) {
		const gchar* _tmp1_ = NULL;
		TTF_Font* _tmp2_ = NULL;
		TTF_Font* _tmp3_ = NULL;
		EntitasWorld* _tmp5_ = NULL;
		EntitasWorld* _tmp6_ = NULL;
		ShmupWarzMovementSystem* _tmp7_ = NULL;
		ShmupWarzMovementSystem* _tmp8_ = NULL;
		EntitasWorld* _tmp9_ = NULL;
		EntitasWorld* _tmp10_ = NULL;
		ShmupWarzPlayerInputSystem* _tmp11_ = NULL;
		ShmupWarzPlayerInputSystem* _tmp12_ = NULL;
		EntitasWorld* _tmp13_ = NULL;
		EntitasWorld* _tmp14_ = NULL;
		ShmupWarzSoundEffectSystem* _tmp15_ = NULL;
		ShmupWarzSoundEffectSystem* _tmp16_ = NULL;
		EntitasWorld* _tmp17_ = NULL;
		EntitasWorld* _tmp18_ = NULL;
		ShmupWarzCollisionSystem* _tmp19_ = NULL;
		ShmupWarzCollisionSystem* _tmp20_ = NULL;
		EntitasWorld* _tmp21_ = NULL;
		EntitasWorld* _tmp22_ = NULL;
		ShmupWarzExpiringSystem* _tmp23_ = NULL;
		ShmupWarzExpiringSystem* _tmp24_ = NULL;
		EntitasWorld* _tmp25_ = NULL;
		EntitasWorld* _tmp26_ = NULL;
		ShmupWarzEntitySpawningTimerSystem* _tmp27_ = NULL;
		ShmupWarzEntitySpawningTimerSystem* _tmp28_ = NULL;
		EntitasWorld* _tmp29_ = NULL;
		EntitasWorld* _tmp30_ = NULL;
		ShmupWarzColorTweenSystem* _tmp31_ = NULL;
		ShmupWarzColorTweenSystem* _tmp32_ = NULL;
		EntitasWorld* _tmp33_ = NULL;
		EntitasWorld* _tmp34_ = NULL;
		ShmupWarzScaleTweenSystem* _tmp35_ = NULL;
		ShmupWarzScaleTweenSystem* _tmp36_ = NULL;
		EntitasWorld* _tmp37_ = NULL;
		EntitasWorld* _tmp38_ = NULL;
		ShmupWarzRemoveOffscreenShipsSystem* _tmp39_ = NULL;
		ShmupWarzRemoveOffscreenShipsSystem* _tmp40_ = NULL;
		EntitasWorld* _tmp41_ = NULL;
		EntitasWorld* _tmp42_ = NULL;
		ShmupWarzViewManagerSystem* _tmp43_ = NULL;
		ShmupWarzViewManagerSystem* _tmp44_ = NULL;
		EntitasWorld* _tmp45_ = NULL;
		EntitasWorld* _tmp46_ = NULL;
		ShmupWarzRenderPositionSystem* _tmp47_ = NULL;
		ShmupWarzRenderPositionSystem* _tmp48_ = NULL;
		EntitasWorld* _tmp49_ = NULL;
		EntitasWorld* _tmp50_ = NULL;
		ShmupWarzHealthRenderSystem* _tmp51_ = NULL;
		ShmupWarzHealthRenderSystem* _tmp52_ = NULL;
		EntitasWorld* _tmp53_ = NULL;
		EntitasWorld* _tmp54_ = NULL;
		ShmupWarzHudRenderSystem* _tmp55_ = NULL;
		ShmupWarzHudRenderSystem* _tmp56_ = NULL;
		EntitasWorld* _tmp57_ = NULL;
		EntitasWorld* _tmp58_ = NULL;
		ShmupWarzDestroySystem* _tmp59_ = NULL;
		ShmupWarzDestroySystem* _tmp60_ = NULL;
		EntitasWorld* _tmp61_ = NULL;
		EntitasWorld* _tmp62_ = NULL;
		EntitasWorld* _tmp63_ = NULL;
		EntitasEntity* _tmp64_ = NULL;
		EntitasEntity* _tmp65_ = NULL;
		EntitasEntity* _tmp66_ = NULL;
		EntitasEntity* _tmp67_ = NULL;
		_tmp1_ = ((BoscoAbstractGame*) self)->defaultFont;
		_tmp2_ = TTF_OpenFont (_tmp1_, 20);
		_TTF_CloseFont0 (self->arial);
		self->arial = _tmp2_;
		_tmp3_ = self->arial;
		if (_tmp3_ == NULL) {
			const gchar* _tmp4_ = NULL;
			_tmp4_ = SDL_GetError ();
			g_print ("Failed to load font! SDL Error: %s\n", _tmp4_);
		}
		_tmp5_ = entitas_world_new (SHMUP_WARZ_components, G_N_ELEMENTS (SHMUP_WARZ_components), 0);
		_tmp6_ = _tmp5_;
		_tmp7_ = shmup_warz_movement_system_new (self);
		_tmp8_ = _tmp7_;
		_tmp9_ = entitas_world_add (_tmp6_, (EntitasISystem*) _tmp8_);
		_tmp10_ = _tmp9_;
		_tmp11_ = shmup_warz_player_input_system_new (self);
		_g_object_unref0 (self->player);
		self->player = _tmp11_;
		_tmp12_ = self->player;
		_tmp13_ = entitas_world_add (_tmp10_, (EntitasISystem*) _tmp12_);
		_tmp14_ = _tmp13_;
		_tmp15_ = shmup_warz_sound_effect_system_new (self);
		_tmp16_ = _tmp15_;
		_tmp17_ = entitas_world_add (_tmp14_, (EntitasISystem*) _tmp16_);
		_tmp18_ = _tmp17_;
		_tmp19_ = shmup_warz_collision_system_new (self);
		_tmp20_ = _tmp19_;
		_tmp21_ = entitas_world_add (_tmp18_, (EntitasISystem*) _tmp20_);
		_tmp22_ = _tmp21_;
		_tmp23_ = shmup_warz_expiring_system_new (self);
		_tmp24_ = _tmp23_;
		_tmp25_ = entitas_world_add (_tmp22_, (EntitasISystem*) _tmp24_);
		_tmp26_ = _tmp25_;
		_tmp27_ = shmup_warz_entity_spawning_timer_system_new (self);
		_tmp28_ = _tmp27_;
		_tmp29_ = entitas_world_add (_tmp26_, (EntitasISystem*) _tmp28_);
		_tmp30_ = _tmp29_;
		_tmp31_ = shmup_warz_color_tween_system_new (self);
		_tmp32_ = _tmp31_;
		_tmp33_ = entitas_world_add (_tmp30_, (EntitasISystem*) _tmp32_);
		_tmp34_ = _tmp33_;
		_tmp35_ = shmup_warz_scale_tween_system_new (self);
		_tmp36_ = _tmp35_;
		_tmp37_ = entitas_world_add (_tmp34_, (EntitasISystem*) _tmp36_);
		_tmp38_ = _tmp37_;
		_tmp39_ = shmup_warz_remove_offscreen_ships_system_new (self);
		_tmp40_ = _tmp39_;
		_tmp41_ = entitas_world_add (_tmp38_, (EntitasISystem*) _tmp40_);
		_tmp42_ = _tmp41_;
		_tmp43_ = shmup_warz_view_manager_system_new (self);
		_tmp44_ = _tmp43_;
		_tmp45_ = entitas_world_add (_tmp42_, (EntitasISystem*) _tmp44_);
		_tmp46_ = _tmp45_;
		_tmp47_ = shmup_warz_render_position_system_new (self);
		_tmp48_ = _tmp47_;
		_tmp49_ = entitas_world_add (_tmp46_, (EntitasISystem*) _tmp48_);
		_tmp50_ = _tmp49_;
		_tmp51_ = shmup_warz_health_render_system_new (self);
		_tmp52_ = _tmp51_;
		_tmp53_ = entitas_world_add (_tmp50_, (EntitasISystem*) _tmp52_);
		_tmp54_ = _tmp53_;
		_tmp55_ = shmup_warz_hud_render_system_new (self);
		_tmp56_ = _tmp55_;
		_tmp57_ = entitas_world_add (_tmp54_, (EntitasISystem*) _tmp56_);
		_tmp58_ = _tmp57_;
		_tmp59_ = shmup_warz_destroy_system_new (self);
		_tmp60_ = _tmp59_;
		_tmp61_ = entitas_world_add (_tmp58_, (EntitasISystem*) _tmp60_);
		_tmp62_ = _tmp61_;
		_tmp63_ = entitas_world_initialize (_tmp62_);
		_g_object_unref0 (self->world);
		self->world = _tmp63_;
		_g_object_unref0 (_tmp62_);
		_g_object_unref0 (_tmp60_);
		_g_object_unref0 (_tmp58_);
		_g_object_unref0 (_tmp56_);
		_g_object_unref0 (_tmp54_);
		_g_object_unref0 (_tmp52_);
		_g_object_unref0 (_tmp50_);
		_g_object_unref0 (_tmp48_);
		_g_object_unref0 (_tmp46_);
		_g_object_unref0 (_tmp44_);
		_g_object_unref0 (_tmp42_);
		_g_object_unref0 (_tmp40_);
		_g_object_unref0 (_tmp38_);
		_g_object_unref0 (_tmp36_);
		_g_object_unref0 (_tmp34_);
		_g_object_unref0 (_tmp32_);
		_g_object_unref0 (_tmp30_);
		_g_object_unref0 (_tmp28_);
		_g_object_unref0 (_tmp26_);
		_g_object_unref0 (_tmp24_);
		_g_object_unref0 (_tmp22_);
		_g_object_unref0 (_tmp20_);
		_g_object_unref0 (_tmp18_);
		_g_object_unref0 (_tmp16_);
		_g_object_unref0 (_tmp14_);
		_g_object_unref0 (_tmp10_);
		_g_object_unref0 (_tmp8_);
		_g_object_unref0 (_tmp6_);
		_tmp64_ = shmup_warz_createBackground ();
		_tmp65_ = _tmp64_;
		_g_object_unref0 (_tmp65_);
		_tmp66_ = shmup_warz_createPlayer ();
		_tmp67_ = _tmp66_;
		_g_object_unref0 (_tmp67_);
	}
	result = TRUE;
	return result;
}


/**
        *  OnEvent
        *
        * Handle events
        */
static void shmup_warz_game_real_Events (BoscoAbstractGame* base, SDL_Event e) {
	ShmupWarzGame * self;
	guint8* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	guint8 _tmp1_ = 0U;
	SDL_Event _tmp2_ = {0};
	SDL_EventType _tmp3_ = 0;
	gboolean _tmp4_ = FALSE;
	gboolean _tmp5_ = FALSE;
	SDL_Event _tmp6_ = {0};
	SDL_EventType _tmp7_ = 0;
	gint x = 0;
	gint y = 0;
	ShmupWarzPlayerInputSystem* _tmp12_ = NULL;
	SDL_Event _tmp13_ = {0};
	SDL_EventType _tmp14_ = 0;
	gint _tmp15_ = 0;
	gint _tmp16_ = 0;
	self = (ShmupWarzGame*) base;
	_tmp0_ = ((BoscoAbstractGame*) self)->keys;
	_tmp0__length1 = ((BoscoAbstractGame*) self)->keys_length1;
	_tmp1_ = _tmp0_[SDLK_ESCAPE];
	if (((gint) _tmp1_) == 1) {
		((BoscoAbstractGame*) self)->running = FALSE;
	}
	_tmp2_ = e;
	_tmp3_ = _tmp2_.type;
	if (_tmp3_ == SDL_QUIT) {
		((BoscoAbstractGame*) self)->running = FALSE;
	}
	_tmp6_ = e;
	_tmp7_ = _tmp6_.type;
	if (_tmp7_ != SDL_MOUSEMOTION) {
		SDL_Event _tmp8_ = {0};
		SDL_EventType _tmp9_ = 0;
		_tmp8_ = e;
		_tmp9_ = _tmp8_.type;
		_tmp5_ = _tmp9_ != SDL_MOUSEBUTTONDOWN;
	} else {
		_tmp5_ = FALSE;
	}
	if (_tmp5_) {
		SDL_Event _tmp10_ = {0};
		SDL_EventType _tmp11_ = 0;
		_tmp10_ = e;
		_tmp11_ = _tmp10_.type;
		_tmp4_ = _tmp11_ != SDL_MOUSEBUTTONUP;
	} else {
		_tmp4_ = FALSE;
	}
	if (_tmp4_) {
		return;
	}
	x = 0;
	y = 0;
	SDL_GetMouseState (&x, &y);
	_tmp12_ = self->player;
	_tmp13_ = e;
	_tmp14_ = _tmp13_.type;
	_tmp15_ = x;
	_tmp16_ = y;
	shmup_warz_player_input_system_onMouseEvent (_tmp12_, _tmp14_, _tmp15_, _tmp16_);
}


/**
        *  OnCleanup
        *
        * release assets
        */
static void shmup_warz_game_real_Dispose (BoscoAbstractGame* base) {
	ShmupWarzGame * self;
	self = (ShmupWarzGame*) base;
	SDL_Quit ();
	IMG_Quit ();
}


static void shmup_warz_game_class_init (ShmupWarzGameClass * klass) {
	shmup_warz_game_parent_class = g_type_class_peek_parent (klass);
	((BoscoAbstractGameClass *) klass)->Update = shmup_warz_game_real_Update;
	((BoscoAbstractGameClass *) klass)->Initialize = shmup_warz_game_real_Initialize;
	((BoscoAbstractGameClass *) klass)->Events = shmup_warz_game_real_Events;
	((BoscoAbstractGameClass *) klass)->Dispose = shmup_warz_game_real_Dispose;
	G_OBJECT_CLASS (klass)->finalize = shmup_warz_game_finalize;
}


static void shmup_warz_game_instance_init (ShmupWarzGame * self) {
}


static void shmup_warz_game_finalize (GObject* obj) {
	ShmupWarzGame * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHMUP_WARZ_TYPE_GAME, ShmupWarzGame);
	_g_object_unref0 (self->world);
	_g_object_unref0 (self->player);
	_TTF_CloseFont0 (self->arial);
	G_OBJECT_CLASS (shmup_warz_game_parent_class)->finalize (obj);
}


/** 
    * Start the application
    */
GType shmup_warz_game_get_type (void) {
	static volatile gsize shmup_warz_game_type_id__volatile = 0;
	if (g_once_init_enter (&shmup_warz_game_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShmupWarzGameClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shmup_warz_game_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShmupWarzGame), 0, (GInstanceInitFunc) shmup_warz_game_instance_init, NULL };
		GType shmup_warz_game_type_id;
		shmup_warz_game_type_id = g_type_register_static (BOSCO_TYPE_ABSTRACT_GAME, "ShmupWarzGame", &g_define_type_info, 0);
		g_once_init_leave (&shmup_warz_game_type_id__volatile, shmup_warz_game_type_id);
	}
	return shmup_warz_game_type_id__volatile;
}



