/* HealthRenderSystem.c generated by valac 0.34.4, the Vala compiler
 * generated from HealthRenderSystem.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <Entitas.h>
#include <Bosco.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include <gee.h>


#define SHMUP_WARZ_TYPE_HEALTH_RENDER_SYSTEM (shmup_warz_health_render_system_get_type ())
#define SHMUP_WARZ_HEALTH_RENDER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_HEALTH_RENDER_SYSTEM, ShmupWarzHealthRenderSystem))
#define SHMUP_WARZ_HEALTH_RENDER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_HEALTH_RENDER_SYSTEM, ShmupWarzHealthRenderSystemClass))
#define SHMUP_WARZ_IS_HEALTH_RENDER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_HEALTH_RENDER_SYSTEM))
#define SHMUP_WARZ_IS_HEALTH_RENDER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_HEALTH_RENDER_SYSTEM))
#define SHMUP_WARZ_HEALTH_RENDER_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_HEALTH_RENDER_SYSTEM, ShmupWarzHealthRenderSystemClass))

typedef struct _ShmupWarzHealthRenderSystem ShmupWarzHealthRenderSystem;
typedef struct _ShmupWarzHealthRenderSystemClass ShmupWarzHealthRenderSystemClass;
typedef struct _ShmupWarzHealthRenderSystemPrivate ShmupWarzHealthRenderSystemPrivate;

#define SHMUP_WARZ_TYPE_GAME (shmup_warz_game_get_type ())
#define SHMUP_WARZ_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGame))
#define SHMUP_WARZ_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))
#define SHMUP_WARZ_IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))

typedef struct _ShmupWarzGame ShmupWarzGame;
typedef struct _ShmupWarzGameClass ShmupWarzGameClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define SHMUP_WARZ_TYPE_COMPONENT (shmup_warz_component_get_type ())

#define SHMUP_WARZ_TYPE_POSITION_COMPONENT (shmup_warz_position_component_get_type ())
#define SHMUP_WARZ_POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_POSITION_COMPONENT, ShmupWarzPositionComponent))
#define SHMUP_WARZ_POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_POSITION_COMPONENT, ShmupWarzPositionComponentClass))
#define SHMUP_WARZ_IS_POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_POSITION_COMPONENT))
#define SHMUP_WARZ_IS_POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_POSITION_COMPONENT))
#define SHMUP_WARZ_POSITION_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_POSITION_COMPONENT, ShmupWarzPositionComponentClass))

typedef struct _ShmupWarzPositionComponent ShmupWarzPositionComponent;
typedef struct _ShmupWarzPositionComponentClass ShmupWarzPositionComponentClass;

#define SHMUP_WARZ_TYPE_HEALTH_COMPONENT (shmup_warz_health_component_get_type ())
#define SHMUP_WARZ_HEALTH_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_HEALTH_COMPONENT, ShmupWarzHealthComponent))
#define SHMUP_WARZ_HEALTH_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_HEALTH_COMPONENT, ShmupWarzHealthComponentClass))
#define SHMUP_WARZ_IS_HEALTH_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_HEALTH_COMPONENT))
#define SHMUP_WARZ_IS_HEALTH_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_HEALTH_COMPONENT))
#define SHMUP_WARZ_HEALTH_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_HEALTH_COMPONENT, ShmupWarzHealthComponentClass))

typedef struct _ShmupWarzHealthComponent ShmupWarzHealthComponent;
typedef struct _ShmupWarzHealthComponentClass ShmupWarzHealthComponentClass;

#define SHMUP_WARZ_TYPE_TEXT_COMPONENT (shmup_warz_text_component_get_type ())
#define SHMUP_WARZ_TEXT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_TEXT_COMPONENT, ShmupWarzTextComponent))
#define SHMUP_WARZ_TEXT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_TEXT_COMPONENT, ShmupWarzTextComponentClass))
#define SHMUP_WARZ_IS_TEXT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_TEXT_COMPONENT))
#define SHMUP_WARZ_IS_TEXT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_TEXT_COMPONENT))
#define SHMUP_WARZ_TEXT_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_TEXT_COMPONENT, ShmupWarzTextComponentClass))

typedef struct _ShmupWarzTextComponent ShmupWarzTextComponent;
typedef struct _ShmupWarzTextComponentClass ShmupWarzTextComponentClass;
typedef struct _ShmupWarzHealthComponentPrivate ShmupWarzHealthComponentPrivate;
typedef struct _ShmupWarzTextComponentPrivate ShmupWarzTextComponentPrivate;
typedef struct _ShmupWarzGamePrivate ShmupWarzGamePrivate;

#define SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM (shmup_warz_player_input_system_get_type ())
#define SHMUP_WARZ_PLAYER_INPUT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM, ShmupWarzPlayerInputSystem))
#define SHMUP_WARZ_PLAYER_INPUT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM, ShmupWarzPlayerInputSystemClass))
#define SHMUP_WARZ_IS_PLAYER_INPUT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM))
#define SHMUP_WARZ_IS_PLAYER_INPUT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM))
#define SHMUP_WARZ_PLAYER_INPUT_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM, ShmupWarzPlayerInputSystemClass))

typedef struct _ShmupWarzPlayerInputSystem ShmupWarzPlayerInputSystem;
typedef struct _ShmupWarzPlayerInputSystemClass ShmupWarzPlayerInputSystemClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _ShmupWarzPositionComponentPrivate ShmupWarzPositionComponentPrivate;

struct _ShmupWarzHealthRenderSystem {
	GObject parent_instance;
	ShmupWarzHealthRenderSystemPrivate * priv;
};

struct _ShmupWarzHealthRenderSystemClass {
	GObjectClass parent_class;
};

struct _ShmupWarzHealthRenderSystemPrivate {
	ShmupWarzGame* _game;
	EntitasWorld* _world;
	EntitasGroup* _group;
};

typedef enum  {
	SHMUP_WARZ_COMPONENT_Bounds,
	SHMUP_WARZ_COMPONENT_Bullet,
	SHMUP_WARZ_COMPONENT_ColorTween,
	SHMUP_WARZ_COMPONENT_Destroy,
	SHMUP_WARZ_COMPONENT_Enemy,
	SHMUP_WARZ_COMPONENT_Expires,
	SHMUP_WARZ_COMPONENT_Firing,
	SHMUP_WARZ_COMPONENT_Health,
	SHMUP_WARZ_COMPONENT_Layer,
	SHMUP_WARZ_COMPONENT_Life,
	SHMUP_WARZ_COMPONENT_Mine,
	SHMUP_WARZ_COMPONENT_Mouse,
	SHMUP_WARZ_COMPONENT_Player,
	SHMUP_WARZ_COMPONENT_Position,
	SHMUP_WARZ_COMPONENT_Resource,
	SHMUP_WARZ_COMPONENT_ScaleTween,
	SHMUP_WARZ_COMPONENT_Scale,
	SHMUP_WARZ_COMPONENT_Score,
	SHMUP_WARZ_COMPONENT_SoundEffect,
	SHMUP_WARZ_COMPONENT_Text,
	SHMUP_WARZ_COMPONENT_Tint,
	SHMUP_WARZ_COMPONENT_Velocity,
	SHMUP_WARZ_COMPONENT_ComponentsCount
} ShmupWarzComponent;

struct _ShmupWarzHealthComponent {
	GObject parent_instance;
	ShmupWarzHealthComponentPrivate * priv;
	gdouble health;
	gdouble maximumHealth;
};

struct _ShmupWarzHealthComponentClass {
	GObjectClass parent_class;
};

struct _ShmupWarzTextComponent {
	GObject parent_instance;
	ShmupWarzTextComponentPrivate * priv;
	gchar* text;
	GObject* sprite;
};

struct _ShmupWarzTextComponentClass {
	GObjectClass parent_class;
};

struct _ShmupWarzGame {
	BoscoAbstractGame parent_instance;
	ShmupWarzGamePrivate * priv;
	EntitasWorld* world;
	BoscoFont* arial;
	ShmupWarzPlayerInputSystem* player;
};

struct _ShmupWarzGameClass {
	BoscoAbstractGameClass parent_class;
};

struct _ShmupWarzPositionComponent {
	GObject parent_instance;
	ShmupWarzPositionComponentPrivate * priv;
	gdouble x;
	gdouble y;
};

struct _ShmupWarzPositionComponentClass {
	GObjectClass parent_class;
};


static gpointer shmup_warz_health_render_system_parent_class = NULL;
static EntitasISetWorldIface* shmup_warz_health_render_system_entitas_iset_world_parent_iface = NULL;
static EntitasIExecuteSystemIface* shmup_warz_health_render_system_entitas_iexecute_system_parent_iface = NULL;
static EntitasIInitializeSystemIface* shmup_warz_health_render_system_entitas_iinitialize_system_parent_iface = NULL;
static EntitasISystemIface* shmup_warz_health_render_system_entitas_isystem_parent_iface = NULL;

GType shmup_warz_health_render_system_get_type (void) G_GNUC_CONST;
GType shmup_warz_game_get_type (void) G_GNUC_CONST;
#define SHMUP_WARZ_HEALTH_RENDER_SYSTEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SHMUP_WARZ_TYPE_HEALTH_RENDER_SYSTEM, ShmupWarzHealthRenderSystemPrivate))
enum  {
	SHMUP_WARZ_HEALTH_RENDER_SYSTEM_DUMMY_PROPERTY
};
ShmupWarzHealthRenderSystem* shmup_warz_health_render_system_new (ShmupWarzGame* game);
ShmupWarzHealthRenderSystem* shmup_warz_health_render_system_construct (GType object_type, ShmupWarzGame* game);
static void shmup_warz_health_render_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world);
static void shmup_warz_health_render_system_real_initialize (EntitasIInitializeSystem* base);
GType shmup_warz_component_get_type (void) G_GNUC_CONST;
static void shmup_warz_health_render_system_real_execute (EntitasIExecuteSystem* base);
GType shmup_warz_position_component_get_type (void) G_GNUC_CONST;
ShmupWarzPositionComponent* shmup_warz_getPosition (EntitasEntity* e);
GType shmup_warz_health_component_get_type (void) G_GNUC_CONST;
ShmupWarzHealthComponent* shmup_warz_getHealth (EntitasEntity* e);
GType shmup_warz_text_component_get_type (void) G_GNUC_CONST;
ShmupWarzTextComponent* shmup_warz_getText (EntitasEntity* e);
GType shmup_warz_player_input_system_get_type (void) G_GNUC_CONST;
static void shmup_warz_health_render_system_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


ShmupWarzHealthRenderSystem* shmup_warz_health_render_system_construct (GType object_type, ShmupWarzGame* game) {
	ShmupWarzHealthRenderSystem * self = NULL;
	ShmupWarzGame* _tmp0_ = NULL;
	ShmupWarzGame* _tmp1_ = NULL;
	g_return_val_if_fail (game != NULL, NULL);
	self = (ShmupWarzHealthRenderSystem*) g_object_new (object_type, NULL);
	_tmp0_ = game;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_game);
	self->priv->_game = _tmp1_;
	return self;
}


ShmupWarzHealthRenderSystem* shmup_warz_health_render_system_new (ShmupWarzGame* game) {
	return shmup_warz_health_render_system_construct (SHMUP_WARZ_TYPE_HEALTH_RENDER_SYSTEM, game);
}


static void shmup_warz_health_render_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world) {
	ShmupWarzHealthRenderSystem * self;
	EntitasWorld* _tmp0_ = NULL;
	EntitasWorld* _tmp1_ = NULL;
	self = (ShmupWarzHealthRenderSystem*) base;
	g_return_if_fail (world != NULL);
	_tmp0_ = world;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_world);
	self->priv->_world = _tmp1_;
}


static void shmup_warz_health_render_system_real_initialize (EntitasIInitializeSystem* base) {
	ShmupWarzHealthRenderSystem * self;
	EntitasWorld* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	EntitasIMatcher* _tmp3_ = NULL;
	EntitasIMatcher* _tmp4_ = NULL;
	EntitasGroup* _tmp5_ = NULL;
	self = (ShmupWarzHealthRenderSystem*) base;
	_tmp0_ = self->priv->_world;
	_tmp1_ = g_new0 (gint, 3);
	_tmp1_[0] = (gint) SHMUP_WARZ_COMPONENT_Position;
	_tmp1_[1] = (gint) SHMUP_WARZ_COMPONENT_Health;
	_tmp1_[2] = (gint) SHMUP_WARZ_COMPONENT_Text;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = 3;
	_tmp3_ = entitas_matcher_AllOf (_tmp2_, 3);
	_tmp4_ = _tmp3_;
	_tmp5_ = entitas_world_getGroup (_tmp0_, _tmp4_);
	_g_object_unref0 (self->priv->_group);
	self->priv->_group = _tmp5_;
	_g_object_unref0 (_tmp4_);
	_tmp2_ = (g_free (_tmp2_), NULL);
}


static void shmup_warz_health_render_system_real_execute (EntitasIExecuteSystem* base) {
	ShmupWarzHealthRenderSystem * self;
	BoscoSprite* sprite = NULL;
	EntitasGroup* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	EntitasEntity** _tmp2_ = NULL;
	self = (ShmupWarzHealthRenderSystem*) base;
	sprite = NULL;
	_tmp0_ = self->priv->_group;
	_tmp2_ = entitas_group_getEntities (_tmp0_, &_tmp1_);
	{
		EntitasEntity** entity_collection = NULL;
		gint entity_collection_length1 = 0;
		gint _entity_collection_size_ = 0;
		gint entity_it = 0;
		entity_collection = _tmp2_;
		entity_collection_length1 = _tmp1_;
		for (entity_it = 0; entity_it < _tmp1_; entity_it = entity_it + 1) {
			EntitasEntity* _tmp3_ = NULL;
			EntitasEntity* entity = NULL;
			_tmp3_ = _g_object_ref0 (entity_collection[entity_it]);
			entity = _tmp3_;
			{
				ShmupWarzPositionComponent* position = NULL;
				EntitasEntity* _tmp4_ = NULL;
				ShmupWarzPositionComponent* _tmp5_ = NULL;
				ShmupWarzHealthComponent* health = NULL;
				EntitasEntity* _tmp6_ = NULL;
				ShmupWarzHealthComponent* _tmp7_ = NULL;
				ShmupWarzTextComponent* text = NULL;
				EntitasEntity* _tmp8_ = NULL;
				ShmupWarzTextComponent* _tmp9_ = NULL;
				gchar* pct = NULL;
				ShmupWarzHealthComponent* _tmp10_ = NULL;
				gdouble _tmp11_ = 0.0;
				ShmupWarzHealthComponent* _tmp12_ = NULL;
				gdouble _tmp13_ = 0.0;
				gdouble _tmp14_ = 0.0;
				gchar* _tmp15_ = NULL;
				const gchar* _tmp16_ = NULL;
				ShmupWarzTextComponent* _tmp17_ = NULL;
				const gchar* _tmp18_ = NULL;
				BoscoSprite* _tmp51_ = NULL;
				ShmupWarzPositionComponent* _tmp52_ = NULL;
				gdouble _tmp53_ = 0.0;
				BoscoSprite* _tmp54_ = NULL;
				ShmupWarzPositionComponent* _tmp55_ = NULL;
				gdouble _tmp56_ = 0.0;
				ShmupWarzGame* _tmp57_ = NULL;
				GeeArrayList* _tmp58_ = NULL;
				BoscoSprite* _tmp59_ = NULL;
				_tmp4_ = entity;
				_tmp5_ = shmup_warz_getPosition (_tmp4_);
				position = _tmp5_;
				_tmp6_ = entity;
				_tmp7_ = shmup_warz_getHealth (_tmp6_);
				health = _tmp7_;
				_tmp8_ = entity;
				_tmp9_ = shmup_warz_getText (_tmp8_);
				text = _tmp9_;
				_tmp10_ = health;
				_tmp11_ = _tmp10_->health;
				_tmp12_ = health;
				_tmp13_ = _tmp12_->maximumHealth;
				_tmp14_ = fmin ((gdouble) 100, (_tmp11_ / _tmp13_) * 100.0);
				_tmp15_ = g_strdup_printf ("%d%%", (gint) _tmp14_);
				pct = _tmp15_;
				_tmp16_ = pct;
				_tmp17_ = text;
				_tmp18_ = _tmp17_->text;
				if (g_strcmp0 (_tmp16_, _tmp18_) == 0) {
					ShmupWarzTextComponent* _tmp19_ = NULL;
					GObject* _tmp20_ = NULL;
					BoscoSprite* _tmp21_ = NULL;
					BoscoSprite* _tmp22_ = NULL;
					_tmp19_ = text;
					_tmp20_ = _tmp19_->sprite;
					_tmp21_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp20_, BOSCO_TYPE_SPRITE, BoscoSprite));
					_g_object_unref0 (sprite);
					sprite = _tmp21_;
					_tmp22_ = sprite;
					if (_tmp22_ == NULL) {
						ShmupWarzGame* _tmp23_ = NULL;
						SDL_Renderer* _tmp24_ = NULL;
						ShmupWarzGame* _tmp25_ = NULL;
						BoscoFont* _tmp26_ = NULL;
						ShmupWarzTextComponent* _tmp27_ = NULL;
						const gchar* _tmp28_ = NULL;
						SDL_Color _tmp29_ = {0};
						BoscoSprite* _tmp30_ = NULL;
						BoscoSprite* _tmp31_ = NULL;
						ShmupWarzTextComponent* _tmp32_ = NULL;
						BoscoSprite* _tmp33_ = NULL;
						GObject* _tmp34_ = NULL;
						_tmp23_ = self->priv->_game;
						_tmp24_ = ((BoscoAbstractGame*) _tmp23_)->renderer;
						_tmp25_ = self->priv->_game;
						_tmp26_ = _tmp25_->arial;
						_tmp27_ = text;
						_tmp28_ = _tmp27_->text;
						_tmp29_ = bosco_color_Lime;
						_tmp30_ = bosco_sprite_fromRenderedText (_tmp24_, _tmp26_, _tmp28_, _tmp29_);
						_g_object_unref0 (sprite);
						sprite = _tmp30_;
						_tmp31_ = sprite;
						_tmp31_->centered = FALSE;
						_tmp32_ = text;
						_tmp33_ = sprite;
						_tmp34_ = _g_object_ref0 ((GObject*) _tmp33_);
						_g_object_unref0 (_tmp32_->sprite);
						_tmp32_->sprite = _tmp34_;
					}
				} else {
					ShmupWarzTextComponent* _tmp35_ = NULL;
					const gchar* _tmp36_ = NULL;
					gchar* _tmp37_ = NULL;
					ShmupWarzTextComponent* _tmp38_ = NULL;
					ShmupWarzGame* _tmp39_ = NULL;
					SDL_Renderer* _tmp40_ = NULL;
					ShmupWarzGame* _tmp41_ = NULL;
					BoscoFont* _tmp42_ = NULL;
					ShmupWarzTextComponent* _tmp43_ = NULL;
					const gchar* _tmp44_ = NULL;
					SDL_Color _tmp45_ = {0};
					BoscoSprite* _tmp46_ = NULL;
					BoscoSprite* _tmp47_ = NULL;
					ShmupWarzTextComponent* _tmp48_ = NULL;
					BoscoSprite* _tmp49_ = NULL;
					GObject* _tmp50_ = NULL;
					_tmp35_ = text;
					_tmp36_ = pct;
					_tmp37_ = g_strdup (_tmp36_);
					_g_free0 (_tmp35_->text);
					_tmp35_->text = _tmp37_;
					_tmp38_ = text;
					_g_object_unref0 (_tmp38_->sprite);
					_tmp38_->sprite = NULL;
					_tmp39_ = self->priv->_game;
					_tmp40_ = ((BoscoAbstractGame*) _tmp39_)->renderer;
					_tmp41_ = self->priv->_game;
					_tmp42_ = _tmp41_->arial;
					_tmp43_ = text;
					_tmp44_ = _tmp43_->text;
					_tmp45_ = bosco_color_LimeGreen;
					_tmp46_ = bosco_sprite_fromRenderedText (_tmp40_, _tmp42_, _tmp44_, _tmp45_);
					_g_object_unref0 (sprite);
					sprite = _tmp46_;
					_tmp47_ = sprite;
					_tmp47_->centered = FALSE;
					_tmp48_ = text;
					_tmp49_ = sprite;
					_tmp50_ = _g_object_ref0 ((GObject*) _tmp49_);
					_g_object_unref0 (_tmp48_->sprite);
					_tmp48_->sprite = _tmp50_;
				}
				_tmp51_ = sprite;
				_tmp52_ = position;
				_tmp53_ = _tmp52_->x;
				_tmp51_->x = (gint) _tmp53_;
				_tmp54_ = sprite;
				_tmp55_ = position;
				_tmp56_ = _tmp55_->y;
				_tmp54_->y = (gint) _tmp56_;
				_tmp57_ = self->priv->_game;
				_tmp58_ = ((BoscoAbstractGame*) _tmp57_)->onetime;
				_tmp59_ = sprite;
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp58_, _tmp59_);
				_g_free0 (pct);
				_g_object_unref0 (text);
				_g_object_unref0 (health);
				_g_object_unref0 (position);
				_g_object_unref0 (entity);
			}
		}
		entity_collection = (_vala_array_free (entity_collection, entity_collection_length1, (GDestroyNotify) g_object_unref), NULL);
	}
	_g_object_unref0 (sprite);
}


static void shmup_warz_health_render_system_class_init (ShmupWarzHealthRenderSystemClass * klass) {
	shmup_warz_health_render_system_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ShmupWarzHealthRenderSystemPrivate));
	G_OBJECT_CLASS (klass)->finalize = shmup_warz_health_render_system_finalize;
}


static void shmup_warz_health_render_system_entitas_iset_world_interface_init (EntitasISetWorldIface * iface) {
	shmup_warz_health_render_system_entitas_iset_world_parent_iface = g_type_interface_peek_parent (iface);
	iface->setWorld = (void (*)(EntitasISetWorld*, EntitasWorld*)) shmup_warz_health_render_system_real_setWorld;
}


static void shmup_warz_health_render_system_entitas_iexecute_system_interface_init (EntitasIExecuteSystemIface * iface) {
	shmup_warz_health_render_system_entitas_iexecute_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->execute = (void (*)(EntitasIExecuteSystem*)) shmup_warz_health_render_system_real_execute;
}


static void shmup_warz_health_render_system_entitas_iinitialize_system_interface_init (EntitasIInitializeSystemIface * iface) {
	shmup_warz_health_render_system_entitas_iinitialize_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->initialize = (void (*)(EntitasIInitializeSystem*)) shmup_warz_health_render_system_real_initialize;
}


static void shmup_warz_health_render_system_entitas_isystem_interface_init (EntitasISystemIface * iface) {
	shmup_warz_health_render_system_entitas_isystem_parent_iface = g_type_interface_peek_parent (iface);
}


static void shmup_warz_health_render_system_instance_init (ShmupWarzHealthRenderSystem * self) {
	self->priv = SHMUP_WARZ_HEALTH_RENDER_SYSTEM_GET_PRIVATE (self);
}


static void shmup_warz_health_render_system_finalize (GObject* obj) {
	ShmupWarzHealthRenderSystem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHMUP_WARZ_TYPE_HEALTH_RENDER_SYSTEM, ShmupWarzHealthRenderSystem);
	_g_object_unref0 (self->priv->_game);
	_g_object_unref0 (self->priv->_world);
	_g_object_unref0 (self->priv->_group);
	G_OBJECT_CLASS (shmup_warz_health_render_system_parent_class)->finalize (obj);
}


GType shmup_warz_health_render_system_get_type (void) {
	static volatile gsize shmup_warz_health_render_system_type_id__volatile = 0;
	if (g_once_init_enter (&shmup_warz_health_render_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShmupWarzHealthRenderSystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shmup_warz_health_render_system_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShmupWarzHealthRenderSystem), 0, (GInstanceInitFunc) shmup_warz_health_render_system_instance_init, NULL };
		static const GInterfaceInfo entitas_iset_world_info = { (GInterfaceInitFunc) shmup_warz_health_render_system_entitas_iset_world_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iexecute_system_info = { (GInterfaceInitFunc) shmup_warz_health_render_system_entitas_iexecute_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iinitialize_system_info = { (GInterfaceInitFunc) shmup_warz_health_render_system_entitas_iinitialize_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_isystem_info = { (GInterfaceInitFunc) shmup_warz_health_render_system_entitas_isystem_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType shmup_warz_health_render_system_type_id;
		shmup_warz_health_render_system_type_id = g_type_register_static (G_TYPE_OBJECT, "ShmupWarzHealthRenderSystem", &g_define_type_info, 0);
		g_type_add_interface_static (shmup_warz_health_render_system_type_id, ENTITAS_TYPE_ISET_WORLD, &entitas_iset_world_info);
		g_type_add_interface_static (shmup_warz_health_render_system_type_id, ENTITAS_TYPE_IEXECUTE_SYSTEM, &entitas_iexecute_system_info);
		g_type_add_interface_static (shmup_warz_health_render_system_type_id, ENTITAS_TYPE_IINITIALIZE_SYSTEM, &entitas_iinitialize_system_info);
		g_type_add_interface_static (shmup_warz_health_render_system_type_id, ENTITAS_TYPE_ISYSTEM, &entitas_isystem_info);
		g_once_init_leave (&shmup_warz_health_render_system_type_id__volatile, shmup_warz_health_render_system_type_id);
	}
	return shmup_warz_health_render_system_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



