/* Main.c generated by valac 0.34.4, the Vala compiler
 * generated from Main.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>
#include <gio/gio.h>
#include <Bosco.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define SHMUP_WARZ_TYPE_GAME (shmup_warz_game_get_type ())
#define SHMUP_WARZ_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGame))
#define SHMUP_WARZ_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))
#define SHMUP_WARZ_IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))

typedef struct _ShmupWarzGame ShmupWarzGame;
typedef struct _ShmupWarzGameClass ShmupWarzGameClass;



void _vala_main (gchar** args, int args_length1);
#define CONSTANTS_DATADIR "/usr/local/share"
GType shmup_warz_game_get_type (void) G_GNUC_CONST;
ShmupWarzGame* shmup_warz_game_new (const gchar* rootPath);
ShmupWarzGame* shmup_warz_game_construct (GType object_type, const gchar* rootPath);


/**
 *  Main.gs
 *
 * Program entry point. 
 * Calculate the resource root location.
 *
 */
static gint string_index_of (const gchar* self, const gchar* needle, gint start_index) {
	gint result = 0;
	gchar* _result_ = NULL;
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (needle != NULL, 0);
	_tmp0_ = start_index;
	_tmp1_ = needle;
	_tmp2_ = strstr (((gchar*) self) + _tmp0_, (gchar*) _tmp1_);
	_result_ = _tmp2_;
	_tmp3_ = _result_;
	if (_tmp3_ != NULL) {
		gchar* _tmp4_ = NULL;
		_tmp4_ = _result_;
		result = (gint) (_tmp4_ - ((gchar*) self));
		return result;
	} else {
		result = -1;
		return result;
	}
}


void _vala_main (gchar** args, int args_length1) {
	gchar* root = NULL;
	gchar* _tmp0_ = NULL;
	gchar* path = NULL;
	gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	ShmupWarzGame* game = NULL;
	const gchar* _tmp26_ = NULL;
	ShmupWarzGame* _tmp27_ = NULL;
	ShmupWarzGame* _tmp28_ = NULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = g_strdup ("");
	root = _tmp0_;
	_tmp1_ = g_file_read_link ("/proc/self/exe", &_inner_error_);
	path = _tmp1_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (root);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = string_index_of (path, "/usr/bin", 0);
	if (_tmp2_ == 0) {
		gchar* _tmp3_ = NULL;
		_tmp3_ = g_strdup (CONSTANTS_DATADIR);
		_g_free0 (root);
		root = _tmp3_;
	} else {
		gint _tmp4_ = 0;
		_tmp4_ = string_index_of (path, "/usr/local/bin", 0);
		if (_tmp4_ == 0) {
			gchar* _tmp5_ = NULL;
			_tmp5_ = g_strdup (CONSTANTS_DATADIR);
			_g_free0 (root);
			root = _tmp5_;
		} else {
			gint _tmp6_ = 0;
			_tmp6_ = string_index_of (path, "/tmp/", 0);
			if (_tmp6_ == 0) {
				gboolean _tmp7_ = FALSE;
				_tmp7_ = g_regex_match_simple ("\\/tmp\\/.*\\/usr/bin", path, 0, 0);
				if (_tmp7_) {
					GFile* _tmp8_ = NULL;
					GFile* _tmp9_ = NULL;
					GFile* _tmp10_ = NULL;
					GFile* _tmp11_ = NULL;
					gchar* _tmp12_ = NULL;
					_tmp8_ = g_file_new_for_path (path);
					_tmp9_ = _tmp8_;
					_tmp10_ = g_file_resolve_relative_path (_tmp9_, "../../../");
					_tmp11_ = _tmp10_;
					_tmp12_ = g_file_get_path (_tmp11_);
					_g_free0 (root);
					root = _tmp12_;
					_g_object_unref0 (_tmp11_);
					_g_object_unref0 (_tmp9_);
				} else {
					g_print ("Invalid /tmp/ path %s\n", path);
				}
			} else {
				GFile* check = NULL;
				GFile* _tmp13_ = NULL;
				GFile* _tmp14_ = NULL;
				GFile* _tmp15_ = NULL;
				GFile* _tmp16_ = NULL;
				GFile* _tmp17_ = NULL;
				gboolean _tmp18_ = FALSE;
				_tmp13_ = g_file_new_for_path (path);
				_tmp14_ = _tmp13_;
				_tmp15_ = g_file_resolve_relative_path (_tmp14_, "../../../data/local/");
				_tmp16_ = _tmp15_;
				_g_object_unref0 (_tmp14_);
				check = _tmp16_;
				_tmp17_ = check;
				_tmp18_ = g_file_query_exists (_tmp17_, NULL);
				if (_tmp18_) {
					GFile* _tmp19_ = NULL;
					gchar* _tmp20_ = NULL;
					_tmp19_ = check;
					_tmp20_ = g_file_get_path (_tmp19_);
					_g_free0 (root);
					root = _tmp20_;
				} else {
					GFile* _tmp21_ = NULL;
					GFile* _tmp22_ = NULL;
					GFile* _tmp23_ = NULL;
					GFile* _tmp24_ = NULL;
					gchar* _tmp25_ = NULL;
					_tmp21_ = g_file_new_for_path (path);
					_tmp22_ = _tmp21_;
					_tmp23_ = g_file_resolve_relative_path (_tmp22_, "../../../");
					_tmp24_ = _tmp23_;
					_tmp25_ = g_file_get_path (_tmp24_);
					_g_free0 (root);
					root = _tmp25_;
					_g_object_unref0 (_tmp24_);
					_g_object_unref0 (_tmp22_);
				}
				_g_object_unref0 (check);
			}
		}
	}
	_tmp26_ = root;
	_tmp27_ = shmup_warz_game_new (_tmp26_);
	game = _tmp27_;
	_tmp28_ = game;
	bosco_abstract_game_Run ((BoscoAbstractGame*) _tmp28_);
	_g_object_unref0 (game);
	_g_free0 (path);
	_g_free0 (root);
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	_vala_main (argv, argc);
	return 0;
}



