/* EntitySpawningTimerSystem.c generated by valac 0.34.4, the Vala compiler
 * generated from EntitySpawningTimerSystem.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <entitas.h>
#include <bosco.h>
#include <float.h>
#include <math.h>


#define SHMUP_WARZ_TYPE_ENTITY_SPAWNING_TIMER_SYSTEM (shmup_warz_entity_spawning_timer_system_get_type ())
#define SHMUP_WARZ_ENTITY_SPAWNING_TIMER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_ENTITY_SPAWNING_TIMER_SYSTEM, ShmupWarzEntitySpawningTimerSystem))
#define SHMUP_WARZ_ENTITY_SPAWNING_TIMER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_ENTITY_SPAWNING_TIMER_SYSTEM, ShmupWarzEntitySpawningTimerSystemClass))
#define SHMUP_WARZ_IS_ENTITY_SPAWNING_TIMER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_ENTITY_SPAWNING_TIMER_SYSTEM))
#define SHMUP_WARZ_IS_ENTITY_SPAWNING_TIMER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_ENTITY_SPAWNING_TIMER_SYSTEM))
#define SHMUP_WARZ_ENTITY_SPAWNING_TIMER_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_ENTITY_SPAWNING_TIMER_SYSTEM, ShmupWarzEntitySpawningTimerSystemClass))

typedef struct _ShmupWarzEntitySpawningTimerSystem ShmupWarzEntitySpawningTimerSystem;
typedef struct _ShmupWarzEntitySpawningTimerSystemClass ShmupWarzEntitySpawningTimerSystemClass;
typedef struct _ShmupWarzEntitySpawningTimerSystemPrivate ShmupWarzEntitySpawningTimerSystemPrivate;

#define SHMUP_WARZ_TYPE_GAME (shmup_warz_game_get_type ())
#define SHMUP_WARZ_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGame))
#define SHMUP_WARZ_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))
#define SHMUP_WARZ_IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))

typedef struct _ShmupWarzGame ShmupWarzGame;
typedef struct _ShmupWarzGameClass ShmupWarzGameClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define SHMUP_WARZ_TYPE_ENEMY (shmup_warz_enemy_get_type ())

struct _ShmupWarzEntitySpawningTimerSystem {
	GObject parent_instance;
	ShmupWarzEntitySpawningTimerSystemPrivate * priv;
};

struct _ShmupWarzEntitySpawningTimerSystemClass {
	GObjectClass parent_class;
};

struct _ShmupWarzEntitySpawningTimerSystemPrivate {
	ShmupWarzGame* _game;
	EntitasWorld* _world;
	gdouble _timer1;
	gdouble _timer2;
	gdouble _timer3;
};

typedef enum  {
	SHMUP_WARZ_ENEMY_Enemy1,
	SHMUP_WARZ_ENEMY_Enemy2,
	SHMUP_WARZ_ENEMY_Enemy3
} ShmupWarzEnemy;


static gpointer shmup_warz_entity_spawning_timer_system_parent_class = NULL;
static EntitasISystemIface* shmup_warz_entity_spawning_timer_system_entitas_isystem_parent_iface = NULL;
static EntitasISetWorldIface* shmup_warz_entity_spawning_timer_system_entitas_iset_world_parent_iface = NULL;
static EntitasIInitializeSystemIface* shmup_warz_entity_spawning_timer_system_entitas_iinitialize_system_parent_iface = NULL;
static EntitasIExecuteSystemIface* shmup_warz_entity_spawning_timer_system_entitas_iexecute_system_parent_iface = NULL;

GType shmup_warz_entity_spawning_timer_system_get_type (void) G_GNUC_CONST;
GType shmup_warz_game_get_type (void) G_GNUC_CONST;
#define SHMUP_WARZ_ENTITY_SPAWNING_TIMER_SYSTEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SHMUP_WARZ_TYPE_ENTITY_SPAWNING_TIMER_SYSTEM, ShmupWarzEntitySpawningTimerSystemPrivate))
enum  {
	SHMUP_WARZ_ENTITY_SPAWNING_TIMER_SYSTEM_DUMMY_PROPERTY
};
ShmupWarzEntitySpawningTimerSystem* shmup_warz_entity_spawning_timer_system_new (ShmupWarzGame* game);
ShmupWarzEntitySpawningTimerSystem* shmup_warz_entity_spawning_timer_system_construct (GType object_type, ShmupWarzGame* game);
static void shmup_warz_entity_spawning_timer_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world);
static void shmup_warz_entity_spawning_timer_system_real_initialize (EntitasIInitializeSystem* base);
static void shmup_warz_entity_spawning_timer_system_real_execute (EntitasIExecuteSystem* base);
GType shmup_warz_enemy_get_type (void) G_GNUC_CONST;
gdouble shmup_warz_entity_spawning_timer_system_spawnEnemy (ShmupWarzEntitySpawningTimerSystem* self, gdouble t, ShmupWarzEnemy enemy);
EntitasEntity* shmup_warz_createEnemy1 (void);
EntitasEntity* shmup_warz_createEnemy2 (void);
EntitasEntity* shmup_warz_createEnemy3 (void);
static void shmup_warz_entity_spawning_timer_system_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


ShmupWarzEntitySpawningTimerSystem* shmup_warz_entity_spawning_timer_system_construct (GType object_type, ShmupWarzGame* game) {
	ShmupWarzEntitySpawningTimerSystem * self = NULL;
	ShmupWarzGame* _tmp0_ = NULL;
	ShmupWarzGame* _tmp1_ = NULL;
	g_return_val_if_fail (game != NULL, NULL);
	self = (ShmupWarzEntitySpawningTimerSystem*) g_object_new (object_type, NULL);
	_tmp0_ = game;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_game);
	self->priv->_game = _tmp1_;
	return self;
}


ShmupWarzEntitySpawningTimerSystem* shmup_warz_entity_spawning_timer_system_new (ShmupWarzGame* game) {
	return shmup_warz_entity_spawning_timer_system_construct (SHMUP_WARZ_TYPE_ENTITY_SPAWNING_TIMER_SYSTEM, game);
}


static void shmup_warz_entity_spawning_timer_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world) {
	ShmupWarzEntitySpawningTimerSystem * self;
	EntitasWorld* _tmp0_ = NULL;
	EntitasWorld* _tmp1_ = NULL;
	self = (ShmupWarzEntitySpawningTimerSystem*) base;
	g_return_if_fail (world != NULL);
	_tmp0_ = world;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_world);
	self->priv->_world = _tmp1_;
}


static void shmup_warz_entity_spawning_timer_system_real_initialize (EntitasIInitializeSystem* base) {
	ShmupWarzEntitySpawningTimerSystem * self;
	self = (ShmupWarzEntitySpawningTimerSystem*) base;
	self->priv->_timer1 = 2.0;
	self->priv->_timer2 = 6.0;
	self->priv->_timer3 = 12.0;
}


static void shmup_warz_entity_spawning_timer_system_real_execute (EntitasIExecuteSystem* base) {
	ShmupWarzEntitySpawningTimerSystem * self;
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	gdouble _tmp4_ = 0.0;
	gdouble _tmp5_ = 0.0;
	self = (ShmupWarzEntitySpawningTimerSystem*) base;
	_tmp0_ = self->priv->_timer1;
	_tmp1_ = shmup_warz_entity_spawning_timer_system_spawnEnemy (self, _tmp0_, SHMUP_WARZ_ENEMY_Enemy1);
	self->priv->_timer1 = _tmp1_;
	_tmp2_ = self->priv->_timer2;
	_tmp3_ = shmup_warz_entity_spawning_timer_system_spawnEnemy (self, _tmp2_, SHMUP_WARZ_ENEMY_Enemy2);
	self->priv->_timer2 = _tmp3_;
	_tmp4_ = self->priv->_timer3;
	_tmp5_ = shmup_warz_entity_spawning_timer_system_spawnEnemy (self, _tmp4_, SHMUP_WARZ_ENEMY_Enemy3);
	self->priv->_timer3 = _tmp5_;
}


gdouble shmup_warz_entity_spawning_timer_system_spawnEnemy (ShmupWarzEntitySpawningTimerSystem* self, gdouble t, ShmupWarzEnemy enemy) {
	gdouble result = 0.0;
	gdouble delta = 0.0;
	gdouble _tmp0_ = 0.0;
	ShmupWarzGame* _tmp1_ = NULL;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	gdouble _result_ = 0.0;
	gdouble _tmp4_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = t;
	_tmp1_ = self->priv->_game;
	_tmp2_ = bosco_abstract_game_get_delta ((BoscoAbstractGame*) _tmp1_);
	_tmp3_ = _tmp2_;
	delta = _tmp0_ - _tmp3_;
	_tmp4_ = delta;
	if (_tmp4_ < ((gdouble) 0)) {
		ShmupWarzEnemy _tmp5_ = 0;
		_tmp5_ = enemy;
		switch (_tmp5_) {
			case SHMUP_WARZ_ENEMY_Enemy1:
			{
				{
					EntitasEntity* _tmp6_ = NULL;
					EntitasEntity* _tmp7_ = NULL;
					_tmp6_ = shmup_warz_createEnemy1 ();
					_tmp7_ = _tmp6_;
					_g_object_unref0 (_tmp7_);
					_result_ = 2.0;
				}
				break;
			}
			case SHMUP_WARZ_ENEMY_Enemy2:
			{
				{
					EntitasEntity* _tmp8_ = NULL;
					EntitasEntity* _tmp9_ = NULL;
					_tmp8_ = shmup_warz_createEnemy2 ();
					_tmp9_ = _tmp8_;
					_g_object_unref0 (_tmp9_);
					_result_ = 6.0;
				}
				break;
			}
			case SHMUP_WARZ_ENEMY_Enemy3:
			{
				{
					EntitasEntity* _tmp10_ = NULL;
					EntitasEntity* _tmp11_ = NULL;
					_tmp10_ = shmup_warz_createEnemy3 ();
					_tmp11_ = _tmp10_;
					_g_object_unref0 (_tmp11_);
					_result_ = 12.0;
				}
				break;
			}
			default:
			{
				{
					_result_ = (gdouble) 0;
				}
				break;
			}
		}
	} else {
		gdouble _tmp12_ = 0.0;
		_tmp12_ = delta;
		_result_ = _tmp12_;
	}
	result = _result_;
	return result;
}


static void shmup_warz_entity_spawning_timer_system_class_init (ShmupWarzEntitySpawningTimerSystemClass * klass) {
	shmup_warz_entity_spawning_timer_system_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ShmupWarzEntitySpawningTimerSystemPrivate));
	G_OBJECT_CLASS (klass)->finalize = shmup_warz_entity_spawning_timer_system_finalize;
}


static void shmup_warz_entity_spawning_timer_system_entitas_isystem_interface_init (EntitasISystemIface * iface) {
	shmup_warz_entity_spawning_timer_system_entitas_isystem_parent_iface = g_type_interface_peek_parent (iface);
}


static void shmup_warz_entity_spawning_timer_system_entitas_iset_world_interface_init (EntitasISetWorldIface * iface) {
	shmup_warz_entity_spawning_timer_system_entitas_iset_world_parent_iface = g_type_interface_peek_parent (iface);
	iface->setWorld = (void (*)(EntitasISetWorld*, EntitasWorld*)) shmup_warz_entity_spawning_timer_system_real_setWorld;
}


static void shmup_warz_entity_spawning_timer_system_entitas_iinitialize_system_interface_init (EntitasIInitializeSystemIface * iface) {
	shmup_warz_entity_spawning_timer_system_entitas_iinitialize_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->initialize = (void (*)(EntitasIInitializeSystem*)) shmup_warz_entity_spawning_timer_system_real_initialize;
}


static void shmup_warz_entity_spawning_timer_system_entitas_iexecute_system_interface_init (EntitasIExecuteSystemIface * iface) {
	shmup_warz_entity_spawning_timer_system_entitas_iexecute_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->execute = (void (*)(EntitasIExecuteSystem*)) shmup_warz_entity_spawning_timer_system_real_execute;
}


static void shmup_warz_entity_spawning_timer_system_instance_init (ShmupWarzEntitySpawningTimerSystem * self) {
	self->priv = SHMUP_WARZ_ENTITY_SPAWNING_TIMER_SYSTEM_GET_PRIVATE (self);
}


static void shmup_warz_entity_spawning_timer_system_finalize (GObject* obj) {
	ShmupWarzEntitySpawningTimerSystem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHMUP_WARZ_TYPE_ENTITY_SPAWNING_TIMER_SYSTEM, ShmupWarzEntitySpawningTimerSystem);
	_g_object_unref0 (self->priv->_game);
	_g_object_unref0 (self->priv->_world);
	G_OBJECT_CLASS (shmup_warz_entity_spawning_timer_system_parent_class)->finalize (obj);
}


GType shmup_warz_entity_spawning_timer_system_get_type (void) {
	static volatile gsize shmup_warz_entity_spawning_timer_system_type_id__volatile = 0;
	if (g_once_init_enter (&shmup_warz_entity_spawning_timer_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShmupWarzEntitySpawningTimerSystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shmup_warz_entity_spawning_timer_system_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShmupWarzEntitySpawningTimerSystem), 0, (GInstanceInitFunc) shmup_warz_entity_spawning_timer_system_instance_init, NULL };
		static const GInterfaceInfo entitas_isystem_info = { (GInterfaceInitFunc) shmup_warz_entity_spawning_timer_system_entitas_isystem_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iset_world_info = { (GInterfaceInitFunc) shmup_warz_entity_spawning_timer_system_entitas_iset_world_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iinitialize_system_info = { (GInterfaceInitFunc) shmup_warz_entity_spawning_timer_system_entitas_iinitialize_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iexecute_system_info = { (GInterfaceInitFunc) shmup_warz_entity_spawning_timer_system_entitas_iexecute_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType shmup_warz_entity_spawning_timer_system_type_id;
		shmup_warz_entity_spawning_timer_system_type_id = g_type_register_static (G_TYPE_OBJECT, "ShmupWarzEntitySpawningTimerSystem", &g_define_type_info, 0);
		g_type_add_interface_static (shmup_warz_entity_spawning_timer_system_type_id, ENTITAS_TYPE_ISYSTEM, &entitas_isystem_info);
		g_type_add_interface_static (shmup_warz_entity_spawning_timer_system_type_id, ENTITAS_TYPE_ISET_WORLD, &entitas_iset_world_info);
		g_type_add_interface_static (shmup_warz_entity_spawning_timer_system_type_id, ENTITAS_TYPE_IINITIALIZE_SYSTEM, &entitas_iinitialize_system_info);
		g_type_add_interface_static (shmup_warz_entity_spawning_timer_system_type_id, ENTITAS_TYPE_IEXECUTE_SYSTEM, &entitas_iexecute_system_info);
		g_once_init_leave (&shmup_warz_entity_spawning_timer_system_type_id__volatile, shmup_warz_entity_spawning_timer_system_type_id);
	}
	return shmup_warz_entity_spawning_timer_system_type_id__volatile;
}



