/* PlayerInputSystem.c generated by valac 0.34.4, the Vala compiler
 * generated from PlayerInputSystem.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <Entitas.h>
#include <Bosco.h>
#include <float.h>
#include <math.h>
#include <SDL2/SDL_events.h>
#include <SDL2/SDL_keyboard.h>


#define SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM (shmup_warz_player_input_system_get_type ())
#define SHMUP_WARZ_PLAYER_INPUT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM, ShmupWarzPlayerInputSystem))
#define SHMUP_WARZ_PLAYER_INPUT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM, ShmupWarzPlayerInputSystemClass))
#define SHMUP_WARZ_IS_PLAYER_INPUT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM))
#define SHMUP_WARZ_IS_PLAYER_INPUT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM))
#define SHMUP_WARZ_PLAYER_INPUT_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM, ShmupWarzPlayerInputSystemClass))

typedef struct _ShmupWarzPlayerInputSystem ShmupWarzPlayerInputSystem;
typedef struct _ShmupWarzPlayerInputSystemClass ShmupWarzPlayerInputSystemClass;
typedef struct _ShmupWarzPlayerInputSystemPrivate ShmupWarzPlayerInputSystemPrivate;

#define SHMUP_WARZ_TYPE_GAME (shmup_warz_game_get_type ())
#define SHMUP_WARZ_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGame))
#define SHMUP_WARZ_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))
#define SHMUP_WARZ_IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))

typedef struct _ShmupWarzGame ShmupWarzGame;
typedef struct _ShmupWarzGameClass ShmupWarzGameClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define SHMUP_WARZ_TYPE_COMPONENT (shmup_warz_component_get_type ())

#define SHMUP_WARZ_TYPE_POSITION_COMPONENT (shmup_warz_position_component_get_type ())
#define SHMUP_WARZ_POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_POSITION_COMPONENT, ShmupWarzPositionComponent))
#define SHMUP_WARZ_POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_POSITION_COMPONENT, ShmupWarzPositionComponentClass))
#define SHMUP_WARZ_IS_POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_POSITION_COMPONENT))
#define SHMUP_WARZ_IS_POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_POSITION_COMPONENT))
#define SHMUP_WARZ_POSITION_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_POSITION_COMPONENT, ShmupWarzPositionComponentClass))

typedef struct _ShmupWarzPositionComponent ShmupWarzPositionComponent;
typedef struct _ShmupWarzPositionComponentClass ShmupWarzPositionComponentClass;
typedef struct _ShmupWarzPositionComponentPrivate ShmupWarzPositionComponentPrivate;

struct _ShmupWarzPlayerInputSystem {
	GObject parent_instance;
	ShmupWarzPlayerInputSystemPrivate * priv;
};

struct _ShmupWarzPlayerInputSystemClass {
	GObjectClass parent_class;
};

struct _ShmupWarzPlayerInputSystemPrivate {
	EntitasGroup* _group;
	EntitasWorld* _world;
	ShmupWarzGame* _game;
	gboolean _mouseDown;
	gboolean _mouseDefined;
	gdouble _timeToFire;
};

typedef enum  {
	SHMUP_WARZ_COMPONENT_Bounds,
	SHMUP_WARZ_COMPONENT_Bullet,
	SHMUP_WARZ_COMPONENT_ColorTween,
	SHMUP_WARZ_COMPONENT_Destroy,
	SHMUP_WARZ_COMPONENT_Enemy,
	SHMUP_WARZ_COMPONENT_Expires,
	SHMUP_WARZ_COMPONENT_Firing,
	SHMUP_WARZ_COMPONENT_Health,
	SHMUP_WARZ_COMPONENT_Layer,
	SHMUP_WARZ_COMPONENT_Life,
	SHMUP_WARZ_COMPONENT_Mine,
	SHMUP_WARZ_COMPONENT_Mouse,
	SHMUP_WARZ_COMPONENT_Player,
	SHMUP_WARZ_COMPONENT_Position,
	SHMUP_WARZ_COMPONENT_Resource,
	SHMUP_WARZ_COMPONENT_ScaleTween,
	SHMUP_WARZ_COMPONENT_Scale,
	SHMUP_WARZ_COMPONENT_Score,
	SHMUP_WARZ_COMPONENT_SoundEffect,
	SHMUP_WARZ_COMPONENT_Text,
	SHMUP_WARZ_COMPONENT_Tint,
	SHMUP_WARZ_COMPONENT_Velocity,
	SHMUP_WARZ_COMPONENT_ComponentsCount
} ShmupWarzComponent;

struct _ShmupWarzPositionComponent {
	GObject parent_instance;
	ShmupWarzPositionComponentPrivate * priv;
	gdouble x;
	gdouble y;
};

struct _ShmupWarzPositionComponentClass {
	GObjectClass parent_class;
};


static gpointer shmup_warz_player_input_system_parent_class = NULL;
extern gdouble shmup_warz_player_input_system_FireRate;
gdouble shmup_warz_player_input_system_FireRate = 0.1;
static EntitasISystemIface* shmup_warz_player_input_system_entitas_isystem_parent_iface = NULL;
static EntitasISetWorldIface* shmup_warz_player_input_system_entitas_iset_world_parent_iface = NULL;
static EntitasIInitializeSystemIface* shmup_warz_player_input_system_entitas_iinitialize_system_parent_iface = NULL;
static EntitasIExecuteSystemIface* shmup_warz_player_input_system_entitas_iexecute_system_parent_iface = NULL;

GType shmup_warz_player_input_system_get_type (void) G_GNUC_CONST;
GType shmup_warz_game_get_type (void) G_GNUC_CONST;
#define SHMUP_WARZ_PLAYER_INPUT_SYSTEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM, ShmupWarzPlayerInputSystemPrivate))
enum  {
	SHMUP_WARZ_PLAYER_INPUT_SYSTEM_DUMMY_PROPERTY
};
ShmupWarzPlayerInputSystem* shmup_warz_player_input_system_new (ShmupWarzGame* game);
ShmupWarzPlayerInputSystem* shmup_warz_player_input_system_construct (GType object_type, ShmupWarzGame* game);
void shmup_warz_player_input_system_onMouseEvent (ShmupWarzPlayerInputSystem* self, SDL_EventType e, gint x, gint y);
void shmup_warz_player_input_system_moveTo (ShmupWarzPlayerInputSystem* self, gint x, gint y);
static void shmup_warz_player_input_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world);
static void shmup_warz_player_input_system_real_initialize (EntitasIInitializeSystem* base);
GType shmup_warz_component_get_type (void) G_GNUC_CONST;
GType shmup_warz_position_component_get_type (void) G_GNUC_CONST;
ShmupWarzPositionComponent* shmup_warz_getPosition (EntitasEntity* e);
static void shmup_warz_player_input_system_real_execute (EntitasIExecuteSystem* base);
EntitasEntity* shmup_warz_createBullet (gdouble x, gdouble y);
static void shmup_warz_player_input_system_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


ShmupWarzPlayerInputSystem* shmup_warz_player_input_system_construct (GType object_type, ShmupWarzGame* game) {
	ShmupWarzPlayerInputSystem * self = NULL;
	ShmupWarzGame* _tmp0_ = NULL;
	ShmupWarzGame* _tmp1_ = NULL;
	g_return_val_if_fail (game != NULL, NULL);
	self = (ShmupWarzPlayerInputSystem*) g_object_new (object_type, NULL);
	_tmp0_ = game;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_game);
	self->priv->_game = _tmp1_;
	return self;
}


ShmupWarzPlayerInputSystem* shmup_warz_player_input_system_new (ShmupWarzGame* game) {
	return shmup_warz_player_input_system_construct (SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM, game);
}


/**
        * Respond to mouse events
        */
void shmup_warz_player_input_system_onMouseEvent (ShmupWarzPlayerInputSystem* self, SDL_EventType e, gint x, gint y) {
	SDL_EventType _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	self->priv->_mouseDefined = TRUE;
	_tmp0_ = e;
	switch (_tmp0_) {
		case SDL_MOUSEMOTION:
		{
			{
				gint _tmp1_ = 0;
				gint _tmp2_ = 0;
				_tmp1_ = x;
				_tmp2_ = y;
				shmup_warz_player_input_system_moveTo (self, _tmp1_, _tmp2_);
			}
			break;
		}
		case SDL_MOUSEBUTTONDOWN:
		{
			{
				gint _tmp3_ = 0;
				gint _tmp4_ = 0;
				_tmp3_ = x;
				_tmp4_ = y;
				shmup_warz_player_input_system_moveTo (self, _tmp3_, _tmp4_);
				self->priv->_mouseDown = TRUE;
			}
			break;
		}
		case SDL_MOUSEBUTTONUP:
		{
			{
				self->priv->_mouseDown = FALSE;
			}
			break;
		}
		default:
		break;
	}
}


static void shmup_warz_player_input_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world) {
	ShmupWarzPlayerInputSystem * self;
	EntitasWorld* _tmp0_ = NULL;
	EntitasWorld* _tmp1_ = NULL;
	self = (ShmupWarzPlayerInputSystem*) base;
	g_return_if_fail (world != NULL);
	_tmp0_ = world;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_world);
	self->priv->_world = _tmp1_;
}


static void shmup_warz_player_input_system_real_initialize (EntitasIInitializeSystem* base) {
	ShmupWarzPlayerInputSystem * self;
	EntitasWorld* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	EntitasIMatcher* _tmp3_ = NULL;
	EntitasIMatcher* _tmp4_ = NULL;
	EntitasGroup* _tmp5_ = NULL;
	self = (ShmupWarzPlayerInputSystem*) base;
	_tmp0_ = self->priv->_world;
	_tmp1_ = g_new0 (gint, 1);
	_tmp1_[0] = (gint) SHMUP_WARZ_COMPONENT_Player;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = 1;
	_tmp3_ = entitas_matcher_AllOf (_tmp2_, 1);
	_tmp4_ = _tmp3_;
	_tmp5_ = entitas_world_getGroup (_tmp0_, _tmp4_);
	_g_object_unref0 (self->priv->_group);
	self->priv->_group = _tmp5_;
	_g_object_unref0 (_tmp4_);
	_tmp2_ = (g_free (_tmp2_), NULL);
}


/**
        * Move the player
        */
void shmup_warz_player_input_system_moveTo (ShmupWarzPlayerInputSystem* self, gint x, gint y) {
	EntitasEntity* entity = NULL;
	EntitasGroup* _tmp0_ = NULL;
	EntitasEntity* _tmp1_ = NULL;
	EntitasEntity* _tmp2_ = NULL;
	ShmupWarzPositionComponent* pos = NULL;
	ShmupWarzPositionComponent* _tmp3_ = NULL;
	ShmupWarzPositionComponent* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	ShmupWarzPositionComponent* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_group;
	_tmp1_ = entitas_group_getSingleEntity (_tmp0_, &_inner_error_);
	_tmp2_ = _g_object_ref0 (_tmp1_);
	entity = _tmp2_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = shmup_warz_getPosition (entity);
	pos = _tmp3_;
	_tmp4_ = pos;
	_tmp5_ = x;
	_tmp4_->x = (gdouble) _tmp5_;
	_tmp6_ = pos;
	_tmp7_ = y;
	_tmp6_->y = (gdouble) _tmp7_;
	_g_object_unref0 (pos);
	_g_object_unref0 (entity);
}


/**
        * Do the keyboard polling
        */
static void shmup_warz_player_input_system_real_execute (EntitasIExecuteSystem* base) {
	ShmupWarzPlayerInputSystem * self;
	EntitasEntity* entity = NULL;
	EntitasGroup* _tmp0_ = NULL;
	EntitasEntity* _tmp1_ = NULL;
	EntitasEntity* _tmp2_ = NULL;
	ShmupWarzPositionComponent* pos = NULL;
	ShmupWarzPositionComponent* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	gdouble _tmp24_ = 0.0;
	GError * _inner_error_ = NULL;
	self = (ShmupWarzPlayerInputSystem*) base;
	_tmp0_ = self->priv->_group;
	_tmp1_ = entitas_group_getSingleEntity (_tmp0_, &_inner_error_);
	_tmp2_ = _g_object_ref0 (_tmp1_);
	entity = _tmp2_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp3_ = shmup_warz_getPosition (entity);
	pos = _tmp3_;
	_tmp4_ = self->priv->_mouseDefined;
	if (_tmp4_) {
		gboolean _tmp5_ = FALSE;
		gboolean _tmp6_ = FALSE;
		_tmp6_ = self->priv->_mouseDown;
		if (_tmp6_) {
			_tmp5_ = TRUE;
		} else {
			ShmupWarzGame* _tmp7_ = NULL;
			guint8* _tmp8_ = NULL;
			gint _tmp8__length1 = 0;
			guint8 _tmp9_ = 0U;
			_tmp7_ = self->priv->_game;
			_tmp8_ = ((BoscoAbstractGame*) _tmp7_)->keys;
			_tmp8__length1 = ((BoscoAbstractGame*) _tmp7_)->keys_length1;
			_tmp9_ = _tmp8_[SDLK_z];
			_tmp5_ = ((gint) _tmp9_) != 0;
		}
		if (_tmp5_) {
			gdouble _tmp10_ = 0.0;
			_tmp10_ = self->priv->_timeToFire;
			if (_tmp10_ <= ((gdouble) 0)) {
				ShmupWarzPositionComponent* _tmp11_ = NULL;
				gdouble _tmp12_ = 0.0;
				ShmupWarzPositionComponent* _tmp13_ = NULL;
				gdouble _tmp14_ = 0.0;
				EntitasEntity* _tmp15_ = NULL;
				EntitasEntity* _tmp16_ = NULL;
				ShmupWarzPositionComponent* _tmp17_ = NULL;
				gdouble _tmp18_ = 0.0;
				ShmupWarzPositionComponent* _tmp19_ = NULL;
				gdouble _tmp20_ = 0.0;
				EntitasEntity* _tmp21_ = NULL;
				EntitasEntity* _tmp22_ = NULL;
				gdouble _tmp23_ = 0.0;
				_tmp11_ = pos;
				_tmp12_ = _tmp11_->x;
				_tmp13_ = pos;
				_tmp14_ = _tmp13_->y;
				_tmp15_ = shmup_warz_createBullet (_tmp12_ - 27, _tmp14_ + 2);
				_tmp16_ = _tmp15_;
				_g_object_unref0 (_tmp16_);
				_tmp17_ = pos;
				_tmp18_ = _tmp17_->x;
				_tmp19_ = pos;
				_tmp20_ = _tmp19_->y;
				_tmp21_ = shmup_warz_createBullet (_tmp18_ + 27, _tmp20_ + 2);
				_tmp22_ = _tmp21_;
				_g_object_unref0 (_tmp22_);
				_tmp23_ = shmup_warz_player_input_system_FireRate;
				self->priv->_timeToFire = _tmp23_;
			}
		}
	}
	_tmp24_ = self->priv->_timeToFire;
	if (_tmp24_ > ((gdouble) 0)) {
		gdouble _tmp25_ = 0.0;
		ShmupWarzGame* _tmp26_ = NULL;
		gdouble _tmp27_ = 0.0;
		gdouble _tmp28_ = 0.0;
		gdouble _tmp29_ = 0.0;
		_tmp25_ = self->priv->_timeToFire;
		_tmp26_ = self->priv->_game;
		_tmp27_ = bosco_abstract_game_get_delta ((BoscoAbstractGame*) _tmp26_);
		_tmp28_ = _tmp27_;
		self->priv->_timeToFire = _tmp25_ - _tmp28_;
		_tmp29_ = self->priv->_timeToFire;
		if (_tmp29_ < ((gdouble) 0)) {
			self->priv->_timeToFire = (gdouble) 0;
		}
	}
	_g_object_unref0 (pos);
	_g_object_unref0 (entity);
}


static void shmup_warz_player_input_system_class_init (ShmupWarzPlayerInputSystemClass * klass) {
	shmup_warz_player_input_system_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ShmupWarzPlayerInputSystemPrivate));
	G_OBJECT_CLASS (klass)->finalize = shmup_warz_player_input_system_finalize;
}


static void shmup_warz_player_input_system_entitas_isystem_interface_init (EntitasISystemIface * iface) {
	shmup_warz_player_input_system_entitas_isystem_parent_iface = g_type_interface_peek_parent (iface);
}


static void shmup_warz_player_input_system_entitas_iset_world_interface_init (EntitasISetWorldIface * iface) {
	shmup_warz_player_input_system_entitas_iset_world_parent_iface = g_type_interface_peek_parent (iface);
	iface->setWorld = (void (*)(EntitasISetWorld*, EntitasWorld*)) shmup_warz_player_input_system_real_setWorld;
}


static void shmup_warz_player_input_system_entitas_iinitialize_system_interface_init (EntitasIInitializeSystemIface * iface) {
	shmup_warz_player_input_system_entitas_iinitialize_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->initialize = (void (*)(EntitasIInitializeSystem*)) shmup_warz_player_input_system_real_initialize;
}


static void shmup_warz_player_input_system_entitas_iexecute_system_interface_init (EntitasIExecuteSystemIface * iface) {
	shmup_warz_player_input_system_entitas_iexecute_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->execute = (void (*)(EntitasIExecuteSystem*)) shmup_warz_player_input_system_real_execute;
}


static void shmup_warz_player_input_system_instance_init (ShmupWarzPlayerInputSystem * self) {
	self->priv = SHMUP_WARZ_PLAYER_INPUT_SYSTEM_GET_PRIVATE (self);
	self->priv->_mouseDefined = FALSE;
	self->priv->_timeToFire = (gdouble) 0;
}


static void shmup_warz_player_input_system_finalize (GObject* obj) {
	ShmupWarzPlayerInputSystem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHMUP_WARZ_TYPE_PLAYER_INPUT_SYSTEM, ShmupWarzPlayerInputSystem);
	_g_object_unref0 (self->priv->_group);
	_g_object_unref0 (self->priv->_world);
	_g_object_unref0 (self->priv->_game);
	G_OBJECT_CLASS (shmup_warz_player_input_system_parent_class)->finalize (obj);
}


GType shmup_warz_player_input_system_get_type (void) {
	static volatile gsize shmup_warz_player_input_system_type_id__volatile = 0;
	if (g_once_init_enter (&shmup_warz_player_input_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShmupWarzPlayerInputSystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shmup_warz_player_input_system_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShmupWarzPlayerInputSystem), 0, (GInstanceInitFunc) shmup_warz_player_input_system_instance_init, NULL };
		static const GInterfaceInfo entitas_isystem_info = { (GInterfaceInitFunc) shmup_warz_player_input_system_entitas_isystem_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iset_world_info = { (GInterfaceInitFunc) shmup_warz_player_input_system_entitas_iset_world_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iinitialize_system_info = { (GInterfaceInitFunc) shmup_warz_player_input_system_entitas_iinitialize_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iexecute_system_info = { (GInterfaceInitFunc) shmup_warz_player_input_system_entitas_iexecute_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType shmup_warz_player_input_system_type_id;
		shmup_warz_player_input_system_type_id = g_type_register_static (G_TYPE_OBJECT, "ShmupWarzPlayerInputSystem", &g_define_type_info, 0);
		g_type_add_interface_static (shmup_warz_player_input_system_type_id, ENTITAS_TYPE_ISYSTEM, &entitas_isystem_info);
		g_type_add_interface_static (shmup_warz_player_input_system_type_id, ENTITAS_TYPE_ISET_WORLD, &entitas_iset_world_info);
		g_type_add_interface_static (shmup_warz_player_input_system_type_id, ENTITAS_TYPE_IINITIALIZE_SYSTEM, &entitas_iinitialize_system_info);
		g_type_add_interface_static (shmup_warz_player_input_system_type_id, ENTITAS_TYPE_IEXECUTE_SYSTEM, &entitas_iexecute_system_info);
		g_once_init_leave (&shmup_warz_player_input_system_type_id__volatile, shmup_warz_player_input_system_type_id);
	}
	return shmup_warz_player_input_system_type_id__volatile;
}



