/* RemoveOffscreenShipsSystem.c generated by valac 0.34.4, the Vala compiler
 * generated from RemoveOffscreenShipsSystem.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <entitas.h>
#include <bosco.h>
#include <float.h>
#include <math.h>


#define SHMUP_WARZ_TYPE_REMOVE_OFFSCREEN_SHIPS_SYSTEM (shmup_warz_remove_offscreen_ships_system_get_type ())
#define SHMUP_WARZ_REMOVE_OFFSCREEN_SHIPS_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_REMOVE_OFFSCREEN_SHIPS_SYSTEM, ShmupWarzRemoveOffscreenShipsSystem))
#define SHMUP_WARZ_REMOVE_OFFSCREEN_SHIPS_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_REMOVE_OFFSCREEN_SHIPS_SYSTEM, ShmupWarzRemoveOffscreenShipsSystemClass))
#define SHMUP_WARZ_IS_REMOVE_OFFSCREEN_SHIPS_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_REMOVE_OFFSCREEN_SHIPS_SYSTEM))
#define SHMUP_WARZ_IS_REMOVE_OFFSCREEN_SHIPS_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_REMOVE_OFFSCREEN_SHIPS_SYSTEM))
#define SHMUP_WARZ_REMOVE_OFFSCREEN_SHIPS_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_REMOVE_OFFSCREEN_SHIPS_SYSTEM, ShmupWarzRemoveOffscreenShipsSystemClass))

typedef struct _ShmupWarzRemoveOffscreenShipsSystem ShmupWarzRemoveOffscreenShipsSystem;
typedef struct _ShmupWarzRemoveOffscreenShipsSystemClass ShmupWarzRemoveOffscreenShipsSystemClass;
typedef struct _ShmupWarzRemoveOffscreenShipsSystemPrivate ShmupWarzRemoveOffscreenShipsSystemPrivate;

#define SHMUP_WARZ_TYPE_GAME (shmup_warz_game_get_type ())
#define SHMUP_WARZ_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGame))
#define SHMUP_WARZ_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))
#define SHMUP_WARZ_IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))

typedef struct _ShmupWarzGame ShmupWarzGame;
typedef struct _ShmupWarzGameClass ShmupWarzGameClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define SHMUP_WARZ_TYPE_COMPONENT (shmup_warz_component_get_type ())

#define SHMUP_WARZ_TYPE_POSITION_COMPONENT (shmup_warz_position_component_get_type ())
#define SHMUP_WARZ_POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_POSITION_COMPONENT, ShmupWarzPositionComponent))
#define SHMUP_WARZ_POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_POSITION_COMPONENT, ShmupWarzPositionComponentClass))
#define SHMUP_WARZ_IS_POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_POSITION_COMPONENT))
#define SHMUP_WARZ_IS_POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_POSITION_COMPONENT))
#define SHMUP_WARZ_POSITION_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_POSITION_COMPONENT, ShmupWarzPositionComponentClass))

typedef struct _ShmupWarzPositionComponent ShmupWarzPositionComponent;
typedef struct _ShmupWarzPositionComponentClass ShmupWarzPositionComponentClass;
typedef struct _ShmupWarzPositionComponentPrivate ShmupWarzPositionComponentPrivate;

#define SHMUP_WARZ_TYPE_BOUNDS_COMPONENT (shmup_warz_bounds_component_get_type ())
#define SHMUP_WARZ_BOUNDS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_BOUNDS_COMPONENT, ShmupWarzBoundsComponent))
#define SHMUP_WARZ_BOUNDS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_BOUNDS_COMPONENT, ShmupWarzBoundsComponentClass))
#define SHMUP_WARZ_IS_BOUNDS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_BOUNDS_COMPONENT))
#define SHMUP_WARZ_IS_BOUNDS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_BOUNDS_COMPONENT))
#define SHMUP_WARZ_BOUNDS_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_BOUNDS_COMPONENT, ShmupWarzBoundsComponentClass))

typedef struct _ShmupWarzBoundsComponent ShmupWarzBoundsComponent;
typedef struct _ShmupWarzBoundsComponentClass ShmupWarzBoundsComponentClass;
typedef struct _ShmupWarzBoundsComponentPrivate ShmupWarzBoundsComponentPrivate;

struct _ShmupWarzRemoveOffscreenShipsSystem {
	GObject parent_instance;
	ShmupWarzRemoveOffscreenShipsSystemPrivate * priv;
};

struct _ShmupWarzRemoveOffscreenShipsSystemClass {
	GObjectClass parent_class;
};

struct _ShmupWarzRemoveOffscreenShipsSystemPrivate {
	EntitasWorld* _world;
	EntitasGroup* _group;
	ShmupWarzGame* _game;
};

typedef enum  {
	SHMUP_WARZ_COMPONENT_Bounds,
	SHMUP_WARZ_COMPONENT_Bullet,
	SHMUP_WARZ_COMPONENT_ColorTween,
	SHMUP_WARZ_COMPONENT_Destroy,
	SHMUP_WARZ_COMPONENT_Enemy,
	SHMUP_WARZ_COMPONENT_Expires,
	SHMUP_WARZ_COMPONENT_Firing,
	SHMUP_WARZ_COMPONENT_Health,
	SHMUP_WARZ_COMPONENT_Layer,
	SHMUP_WARZ_COMPONENT_Life,
	SHMUP_WARZ_COMPONENT_Mine,
	SHMUP_WARZ_COMPONENT_Mouse,
	SHMUP_WARZ_COMPONENT_Player,
	SHMUP_WARZ_COMPONENT_Position,
	SHMUP_WARZ_COMPONENT_Resource,
	SHMUP_WARZ_COMPONENT_ScaleTween,
	SHMUP_WARZ_COMPONENT_Scale,
	SHMUP_WARZ_COMPONENT_Score,
	SHMUP_WARZ_COMPONENT_SoundEffect,
	SHMUP_WARZ_COMPONENT_Text,
	SHMUP_WARZ_COMPONENT_Tint,
	SHMUP_WARZ_COMPONENT_Velocity,
	SHMUP_WARZ_COMPONENT_ComponentsCount
} ShmupWarzComponent;

struct _ShmupWarzPositionComponent {
	GObject parent_instance;
	ShmupWarzPositionComponentPrivate * priv;
	gdouble x;
	gdouble y;
};

struct _ShmupWarzPositionComponentClass {
	GObjectClass parent_class;
};

struct _ShmupWarzBoundsComponent {
	GObject parent_instance;
	ShmupWarzBoundsComponentPrivate * priv;
	gdouble radius;
};

struct _ShmupWarzBoundsComponentClass {
	GObjectClass parent_class;
};


static gpointer shmup_warz_remove_offscreen_ships_system_parent_class = NULL;
static EntitasISystemIface* shmup_warz_remove_offscreen_ships_system_entitas_isystem_parent_iface = NULL;
static EntitasISetWorldIface* shmup_warz_remove_offscreen_ships_system_entitas_iset_world_parent_iface = NULL;
static EntitasIInitializeSystemIface* shmup_warz_remove_offscreen_ships_system_entitas_iinitialize_system_parent_iface = NULL;
static EntitasIExecuteSystemIface* shmup_warz_remove_offscreen_ships_system_entitas_iexecute_system_parent_iface = NULL;

GType shmup_warz_remove_offscreen_ships_system_get_type (void) G_GNUC_CONST;
GType shmup_warz_game_get_type (void) G_GNUC_CONST;
#define SHMUP_WARZ_REMOVE_OFFSCREEN_SHIPS_SYSTEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SHMUP_WARZ_TYPE_REMOVE_OFFSCREEN_SHIPS_SYSTEM, ShmupWarzRemoveOffscreenShipsSystemPrivate))
enum  {
	SHMUP_WARZ_REMOVE_OFFSCREEN_SHIPS_SYSTEM_DUMMY_PROPERTY
};
ShmupWarzRemoveOffscreenShipsSystem* shmup_warz_remove_offscreen_ships_system_new (ShmupWarzGame* game);
ShmupWarzRemoveOffscreenShipsSystem* shmup_warz_remove_offscreen_ships_system_construct (GType object_type, ShmupWarzGame* game);
static void shmup_warz_remove_offscreen_ships_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world);
static void shmup_warz_remove_offscreen_ships_system_real_initialize (EntitasIInitializeSystem* base);
GType shmup_warz_component_get_type (void) G_GNUC_CONST;
static void shmup_warz_remove_offscreen_ships_system_real_execute (EntitasIExecuteSystem* base);
gboolean shmup_warz_hasPosition (EntitasEntity* e);
GType shmup_warz_position_component_get_type (void) G_GNUC_CONST;
ShmupWarzPositionComponent* shmup_warz_getPosition (EntitasEntity* e);
GType shmup_warz_bounds_component_get_type (void) G_GNUC_CONST;
ShmupWarzBoundsComponent* shmup_warz_getBounds (EntitasEntity* e);
gboolean shmup_warz_isPlayer (EntitasEntity* e);
EntitasEntity* shmup_warz_setDestroy (EntitasEntity* e, gboolean value);
static void shmup_warz_remove_offscreen_ships_system_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


ShmupWarzRemoveOffscreenShipsSystem* shmup_warz_remove_offscreen_ships_system_construct (GType object_type, ShmupWarzGame* game) {
	ShmupWarzRemoveOffscreenShipsSystem * self = NULL;
	ShmupWarzGame* _tmp0_ = NULL;
	ShmupWarzGame* _tmp1_ = NULL;
	g_return_val_if_fail (game != NULL, NULL);
	self = (ShmupWarzRemoveOffscreenShipsSystem*) g_object_new (object_type, NULL);
	_tmp0_ = game;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_game);
	self->priv->_game = _tmp1_;
	return self;
}


ShmupWarzRemoveOffscreenShipsSystem* shmup_warz_remove_offscreen_ships_system_new (ShmupWarzGame* game) {
	return shmup_warz_remove_offscreen_ships_system_construct (SHMUP_WARZ_TYPE_REMOVE_OFFSCREEN_SHIPS_SYSTEM, game);
}


static void shmup_warz_remove_offscreen_ships_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world) {
	ShmupWarzRemoveOffscreenShipsSystem * self;
	EntitasWorld* _tmp0_ = NULL;
	EntitasWorld* _tmp1_ = NULL;
	self = (ShmupWarzRemoveOffscreenShipsSystem*) base;
	g_return_if_fail (world != NULL);
	_tmp0_ = world;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_world);
	self->priv->_world = _tmp1_;
}


static void shmup_warz_remove_offscreen_ships_system_real_initialize (EntitasIInitializeSystem* base) {
	ShmupWarzRemoveOffscreenShipsSystem * self;
	EntitasWorld* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	EntitasIMatcher* _tmp3_ = NULL;
	EntitasIMatcher* _tmp4_ = NULL;
	EntitasGroup* _tmp5_ = NULL;
	self = (ShmupWarzRemoveOffscreenShipsSystem*) base;
	_tmp0_ = self->priv->_world;
	_tmp1_ = g_new0 (gint, 2);
	_tmp1_[0] = (gint) SHMUP_WARZ_COMPONENT_Position;
	_tmp1_[1] = (gint) SHMUP_WARZ_COMPONENT_Bounds;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = 2;
	_tmp3_ = entitas_matcher_AllOf (_tmp2_, 2);
	_tmp4_ = _tmp3_;
	_tmp5_ = entitas_world_getGroup (_tmp0_, _tmp4_);
	_g_object_unref0 (self->priv->_group);
	self->priv->_group = _tmp5_;
	_g_object_unref0 (_tmp4_);
	_tmp2_ = (g_free (_tmp2_), NULL);
}


static void shmup_warz_remove_offscreen_ships_system_real_execute (EntitasIExecuteSystem* base) {
	ShmupWarzRemoveOffscreenShipsSystem * self;
	EntitasGroup* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	EntitasEntity** _tmp2_ = NULL;
	self = (ShmupWarzRemoveOffscreenShipsSystem*) base;
	_tmp0_ = self->priv->_group;
	_tmp2_ = entitas_group_getEntities (_tmp0_, &_tmp1_);
	{
		EntitasEntity** entity_collection = NULL;
		gint entity_collection_length1 = 0;
		gint _entity_collection_size_ = 0;
		gint entity_it = 0;
		entity_collection = _tmp2_;
		entity_collection_length1 = _tmp1_;
		for (entity_it = 0; entity_it < _tmp1_; entity_it = entity_it + 1) {
			EntitasEntity* _tmp3_ = NULL;
			EntitasEntity* entity = NULL;
			_tmp3_ = _g_object_ref0 (entity_collection[entity_it]);
			entity = _tmp3_;
			{
				EntitasEntity* _tmp4_ = NULL;
				gboolean _tmp5_ = FALSE;
				_tmp4_ = entity;
				_tmp5_ = shmup_warz_hasPosition (_tmp4_);
				if (_tmp5_) {
					EntitasEntity* _tmp6_ = NULL;
					ShmupWarzPositionComponent* _tmp7_ = NULL;
					ShmupWarzPositionComponent* _tmp8_ = NULL;
					gdouble _tmp9_ = 0.0;
					ShmupWarzGame* _tmp10_ = NULL;
					gint _tmp11_ = 0;
					EntitasEntity* _tmp12_ = NULL;
					ShmupWarzBoundsComponent* _tmp13_ = NULL;
					ShmupWarzBoundsComponent* _tmp14_ = NULL;
					gdouble _tmp15_ = 0.0;
					gboolean _tmp16_ = FALSE;
					_tmp6_ = entity;
					_tmp7_ = shmup_warz_getPosition (_tmp6_);
					_tmp8_ = _tmp7_;
					_tmp9_ = _tmp8_->y;
					_tmp10_ = self->priv->_game;
					_tmp11_ = ((BoscoAbstractGame*) _tmp10_)->height;
					_tmp12_ = entity;
					_tmp13_ = shmup_warz_getBounds (_tmp12_);
					_tmp14_ = _tmp13_;
					_tmp15_ = _tmp14_->radius;
					_tmp16_ = _tmp9_ > (_tmp11_ - _tmp15_);
					_g_object_unref0 (_tmp14_);
					_g_object_unref0 (_tmp8_);
					if (_tmp16_) {
						EntitasEntity* _tmp17_ = NULL;
						gboolean _tmp18_ = FALSE;
						_tmp17_ = entity;
						_tmp18_ = shmup_warz_isPlayer (_tmp17_);
						if (!_tmp18_) {
							EntitasEntity* _tmp19_ = NULL;
							EntitasEntity* _tmp20_ = NULL;
							EntitasEntity* _tmp21_ = NULL;
							_tmp19_ = entity;
							_tmp20_ = shmup_warz_setDestroy (_tmp19_, TRUE);
							_tmp21_ = _tmp20_;
							_g_object_unref0 (_tmp21_);
						}
					}
				}
				_g_object_unref0 (entity);
			}
		}
		entity_collection = (_vala_array_free (entity_collection, entity_collection_length1, (GDestroyNotify) g_object_unref), NULL);
	}
}


static void shmup_warz_remove_offscreen_ships_system_class_init (ShmupWarzRemoveOffscreenShipsSystemClass * klass) {
	shmup_warz_remove_offscreen_ships_system_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ShmupWarzRemoveOffscreenShipsSystemPrivate));
	G_OBJECT_CLASS (klass)->finalize = shmup_warz_remove_offscreen_ships_system_finalize;
}


static void shmup_warz_remove_offscreen_ships_system_entitas_isystem_interface_init (EntitasISystemIface * iface) {
	shmup_warz_remove_offscreen_ships_system_entitas_isystem_parent_iface = g_type_interface_peek_parent (iface);
}


static void shmup_warz_remove_offscreen_ships_system_entitas_iset_world_interface_init (EntitasISetWorldIface * iface) {
	shmup_warz_remove_offscreen_ships_system_entitas_iset_world_parent_iface = g_type_interface_peek_parent (iface);
	iface->setWorld = (void (*)(EntitasISetWorld*, EntitasWorld*)) shmup_warz_remove_offscreen_ships_system_real_setWorld;
}


static void shmup_warz_remove_offscreen_ships_system_entitas_iinitialize_system_interface_init (EntitasIInitializeSystemIface * iface) {
	shmup_warz_remove_offscreen_ships_system_entitas_iinitialize_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->initialize = (void (*)(EntitasIInitializeSystem*)) shmup_warz_remove_offscreen_ships_system_real_initialize;
}


static void shmup_warz_remove_offscreen_ships_system_entitas_iexecute_system_interface_init (EntitasIExecuteSystemIface * iface) {
	shmup_warz_remove_offscreen_ships_system_entitas_iexecute_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->execute = (void (*)(EntitasIExecuteSystem*)) shmup_warz_remove_offscreen_ships_system_real_execute;
}


static void shmup_warz_remove_offscreen_ships_system_instance_init (ShmupWarzRemoveOffscreenShipsSystem * self) {
	self->priv = SHMUP_WARZ_REMOVE_OFFSCREEN_SHIPS_SYSTEM_GET_PRIVATE (self);
}


static void shmup_warz_remove_offscreen_ships_system_finalize (GObject* obj) {
	ShmupWarzRemoveOffscreenShipsSystem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHMUP_WARZ_TYPE_REMOVE_OFFSCREEN_SHIPS_SYSTEM, ShmupWarzRemoveOffscreenShipsSystem);
	_g_object_unref0 (self->priv->_world);
	_g_object_unref0 (self->priv->_group);
	_g_object_unref0 (self->priv->_game);
	G_OBJECT_CLASS (shmup_warz_remove_offscreen_ships_system_parent_class)->finalize (obj);
}


GType shmup_warz_remove_offscreen_ships_system_get_type (void) {
	static volatile gsize shmup_warz_remove_offscreen_ships_system_type_id__volatile = 0;
	if (g_once_init_enter (&shmup_warz_remove_offscreen_ships_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShmupWarzRemoveOffscreenShipsSystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shmup_warz_remove_offscreen_ships_system_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShmupWarzRemoveOffscreenShipsSystem), 0, (GInstanceInitFunc) shmup_warz_remove_offscreen_ships_system_instance_init, NULL };
		static const GInterfaceInfo entitas_isystem_info = { (GInterfaceInitFunc) shmup_warz_remove_offscreen_ships_system_entitas_isystem_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iset_world_info = { (GInterfaceInitFunc) shmup_warz_remove_offscreen_ships_system_entitas_iset_world_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iinitialize_system_info = { (GInterfaceInitFunc) shmup_warz_remove_offscreen_ships_system_entitas_iinitialize_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iexecute_system_info = { (GInterfaceInitFunc) shmup_warz_remove_offscreen_ships_system_entitas_iexecute_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType shmup_warz_remove_offscreen_ships_system_type_id;
		shmup_warz_remove_offscreen_ships_system_type_id = g_type_register_static (G_TYPE_OBJECT, "ShmupWarzRemoveOffscreenShipsSystem", &g_define_type_info, 0);
		g_type_add_interface_static (shmup_warz_remove_offscreen_ships_system_type_id, ENTITAS_TYPE_ISYSTEM, &entitas_isystem_info);
		g_type_add_interface_static (shmup_warz_remove_offscreen_ships_system_type_id, ENTITAS_TYPE_ISET_WORLD, &entitas_iset_world_info);
		g_type_add_interface_static (shmup_warz_remove_offscreen_ships_system_type_id, ENTITAS_TYPE_IINITIALIZE_SYSTEM, &entitas_iinitialize_system_info);
		g_type_add_interface_static (shmup_warz_remove_offscreen_ships_system_type_id, ENTITAS_TYPE_IEXECUTE_SYSTEM, &entitas_iexecute_system_info);
		g_once_init_leave (&shmup_warz_remove_offscreen_ships_system_type_id__volatile, shmup_warz_remove_offscreen_ships_system_type_id);
	}
	return shmup_warz_remove_offscreen_ships_system_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



