/* RenderPositionSystem.c generated by valac 0.34.4, the Vala compiler
 * generated from RenderPositionSystem.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <entitas.h>
#include <SDL2/SDL_render.h>
#include <bosco.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define SHMUP_WARZ_TYPE_RENDER_POSITION_SYSTEM (shmup_warz_render_position_system_get_type ())
#define SHMUP_WARZ_RENDER_POSITION_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_RENDER_POSITION_SYSTEM, ShmupWarzRenderPositionSystem))
#define SHMUP_WARZ_RENDER_POSITION_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_RENDER_POSITION_SYSTEM, ShmupWarzRenderPositionSystemClass))
#define SHMUP_WARZ_IS_RENDER_POSITION_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_RENDER_POSITION_SYSTEM))
#define SHMUP_WARZ_IS_RENDER_POSITION_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_RENDER_POSITION_SYSTEM))
#define SHMUP_WARZ_RENDER_POSITION_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_RENDER_POSITION_SYSTEM, ShmupWarzRenderPositionSystemClass))

typedef struct _ShmupWarzRenderPositionSystem ShmupWarzRenderPositionSystem;
typedef struct _ShmupWarzRenderPositionSystemClass ShmupWarzRenderPositionSystemClass;
typedef struct _ShmupWarzRenderPositionSystemPrivate ShmupWarzRenderPositionSystemPrivate;

#define SHMUP_WARZ_TYPE_GAME (shmup_warz_game_get_type ())
#define SHMUP_WARZ_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGame))
#define SHMUP_WARZ_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))
#define SHMUP_WARZ_IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))

typedef struct _ShmupWarzGame ShmupWarzGame;
typedef struct _ShmupWarzGameClass ShmupWarzGameClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_ptr_array_unref0(var) ((var == NULL) ? NULL : (var = (g_ptr_array_unref (var), NULL)))

#define SHMUP_WARZ_TYPE_COMPONENT (shmup_warz_component_get_type ())

#define SHMUP_WARZ_TYPE_RESOURCE_COMPONENT (shmup_warz_resource_component_get_type ())
#define SHMUP_WARZ_RESOURCE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_RESOURCE_COMPONENT, ShmupWarzResourceComponent))
#define SHMUP_WARZ_RESOURCE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_RESOURCE_COMPONENT, ShmupWarzResourceComponentClass))
#define SHMUP_WARZ_IS_RESOURCE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_RESOURCE_COMPONENT))
#define SHMUP_WARZ_IS_RESOURCE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_RESOURCE_COMPONENT))
#define SHMUP_WARZ_RESOURCE_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_RESOURCE_COMPONENT, ShmupWarzResourceComponentClass))

typedef struct _ShmupWarzResourceComponent ShmupWarzResourceComponent;
typedef struct _ShmupWarzResourceComponentClass ShmupWarzResourceComponentClass;

#define SHMUP_WARZ_TYPE_POSITION_COMPONENT (shmup_warz_position_component_get_type ())
#define SHMUP_WARZ_POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_POSITION_COMPONENT, ShmupWarzPositionComponent))
#define SHMUP_WARZ_POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_POSITION_COMPONENT, ShmupWarzPositionComponentClass))
#define SHMUP_WARZ_IS_POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_POSITION_COMPONENT))
#define SHMUP_WARZ_IS_POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_POSITION_COMPONENT))
#define SHMUP_WARZ_POSITION_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_POSITION_COMPONENT, ShmupWarzPositionComponentClass))

typedef struct _ShmupWarzPositionComponent ShmupWarzPositionComponent;
typedef struct _ShmupWarzPositionComponentClass ShmupWarzPositionComponentClass;
typedef struct _ShmupWarzResourceComponentPrivate ShmupWarzResourceComponentPrivate;
typedef struct _ShmupWarzPositionComponentPrivate ShmupWarzPositionComponentPrivate;

struct _ShmupWarzRenderPositionSystem {
	GObject parent_instance;
	ShmupWarzRenderPositionSystemPrivate * priv;
};

struct _ShmupWarzRenderPositionSystemClass {
	GObjectClass parent_class;
};

struct _ShmupWarzRenderPositionSystemPrivate {
	SDL_Renderer* _renderer;
	EntitasGroup* _group;
	ShmupWarzGame* _game;
	GPtrArray* _sprites;
};

typedef enum  {
	SHMUP_WARZ_COMPONENT_Bounds,
	SHMUP_WARZ_COMPONENT_Bullet,
	SHMUP_WARZ_COMPONENT_ColorTween,
	SHMUP_WARZ_COMPONENT_Destroy,
	SHMUP_WARZ_COMPONENT_Enemy,
	SHMUP_WARZ_COMPONENT_Expires,
	SHMUP_WARZ_COMPONENT_Firing,
	SHMUP_WARZ_COMPONENT_Health,
	SHMUP_WARZ_COMPONENT_Layer,
	SHMUP_WARZ_COMPONENT_Life,
	SHMUP_WARZ_COMPONENT_Mine,
	SHMUP_WARZ_COMPONENT_Mouse,
	SHMUP_WARZ_COMPONENT_Player,
	SHMUP_WARZ_COMPONENT_Position,
	SHMUP_WARZ_COMPONENT_Resource,
	SHMUP_WARZ_COMPONENT_ScaleTween,
	SHMUP_WARZ_COMPONENT_Scale,
	SHMUP_WARZ_COMPONENT_Score,
	SHMUP_WARZ_COMPONENT_SoundEffect,
	SHMUP_WARZ_COMPONENT_Text,
	SHMUP_WARZ_COMPONENT_Tint,
	SHMUP_WARZ_COMPONENT_Velocity,
	SHMUP_WARZ_COMPONENT_ComponentsCount
} ShmupWarzComponent;

struct _ShmupWarzResourceComponent {
	GObject parent_instance;
	ShmupWarzResourceComponentPrivate * priv;
	gchar* path;
	GObject* sprite;
	gboolean bgd;
};

struct _ShmupWarzResourceComponentClass {
	GObjectClass parent_class;
};

struct _ShmupWarzPositionComponent {
	GObject parent_instance;
	ShmupWarzPositionComponentPrivate * priv;
	gdouble x;
	gdouble y;
};

struct _ShmupWarzPositionComponentClass {
	GObjectClass parent_class;
};


static gpointer shmup_warz_render_position_system_parent_class = NULL;
static EntitasISystemIface* shmup_warz_render_position_system_entitas_isystem_parent_iface = NULL;
static EntitasISetWorldIface* shmup_warz_render_position_system_entitas_iset_world_parent_iface = NULL;
static EntitasIInitializeSystemIface* shmup_warz_render_position_system_entitas_iinitialize_system_parent_iface = NULL;
static EntitasIExecuteSystemIface* shmup_warz_render_position_system_entitas_iexecute_system_parent_iface = NULL;

GType shmup_warz_render_position_system_get_type (void) G_GNUC_CONST;
GType shmup_warz_game_get_type (void) G_GNUC_CONST;
#define SHMUP_WARZ_RENDER_POSITION_SYSTEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SHMUP_WARZ_TYPE_RENDER_POSITION_SYSTEM, ShmupWarzRenderPositionSystemPrivate))
enum  {
	SHMUP_WARZ_RENDER_POSITION_SYSTEM_DUMMY_PROPERTY
};
ShmupWarzRenderPositionSystem* shmup_warz_render_position_system_new (ShmupWarzGame* game);
ShmupWarzRenderPositionSystem* shmup_warz_render_position_system_construct (GType object_type, ShmupWarzGame* game);
static void shmup_warz_render_position_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world);
GType shmup_warz_component_get_type (void) G_GNUC_CONST;
static void shmup_warz_render_position_system_real_initialize (EntitasIInitializeSystem* base);
static void shmup_warz_render_position_system_real_execute (EntitasIExecuteSystem* base);
GType shmup_warz_resource_component_get_type (void) G_GNUC_CONST;
ShmupWarzResourceComponent* shmup_warz_getResource (EntitasEntity* e);
GType shmup_warz_position_component_get_type (void) G_GNUC_CONST;
ShmupWarzPositionComponent* shmup_warz_getPosition (EntitasEntity* e);
static void shmup_warz_render_position_system_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


ShmupWarzRenderPositionSystem* shmup_warz_render_position_system_construct (GType object_type, ShmupWarzGame* game) {
	ShmupWarzRenderPositionSystem * self = NULL;
	ShmupWarzGame* _tmp0_ = NULL;
	ShmupWarzGame* _tmp1_ = NULL;
	ShmupWarzGame* _tmp2_ = NULL;
	SDL_Renderer* _tmp3_ = NULL;
	g_return_val_if_fail (game != NULL, NULL);
	self = (ShmupWarzRenderPositionSystem*) g_object_new (object_type, NULL);
	_tmp0_ = game;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_game);
	self->priv->_game = _tmp1_;
	_tmp2_ = self->priv->_game;
	_tmp3_ = ((BoscoAbstractGame*) _tmp2_)->renderer;
	self->priv->_renderer = _tmp3_;
	return self;
}


ShmupWarzRenderPositionSystem* shmup_warz_render_position_system_new (ShmupWarzGame* game) {
	return shmup_warz_render_position_system_construct (SHMUP_WARZ_TYPE_RENDER_POSITION_SYSTEM, game);
}


static void shmup_warz_render_position_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world) {
	ShmupWarzRenderPositionSystem * self;
	EntitasWorld* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	EntitasIMatcher* _tmp3_ = NULL;
	EntitasIMatcher* _tmp4_ = NULL;
	EntitasGroup* _tmp5_ = NULL;
	self = (ShmupWarzRenderPositionSystem*) base;
	g_return_if_fail (world != NULL);
	_tmp0_ = world;
	_tmp1_ = g_new0 (gint, 2);
	_tmp1_[0] = (gint) SHMUP_WARZ_COMPONENT_Resource;
	_tmp1_[1] = (gint) SHMUP_WARZ_COMPONENT_Position;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = 2;
	_tmp3_ = entitas_matcher_AllOf (_tmp2_, 2);
	_tmp4_ = _tmp3_;
	_tmp5_ = entitas_world_getGroup (_tmp0_, _tmp4_);
	_g_object_unref0 (self->priv->_group);
	self->priv->_group = _tmp5_;
	_g_object_unref0 (_tmp4_);
	_tmp2_ = (g_free (_tmp2_), NULL);
}


static gpointer _g_ptr_array_ref0 (gpointer self) {
	return self ? g_ptr_array_ref (self) : NULL;
}


static void shmup_warz_render_position_system_real_initialize (EntitasIInitializeSystem* base) {
	ShmupWarzRenderPositionSystem * self;
	ShmupWarzGame* _tmp0_ = NULL;
	GPtrArray* _tmp1_ = NULL;
	GPtrArray* _tmp2_ = NULL;
	self = (ShmupWarzRenderPositionSystem*) base;
	_tmp0_ = self->priv->_game;
	_tmp1_ = ((BoscoAbstractGame*) _tmp0_)->sprites;
	_tmp2_ = _g_ptr_array_ref0 (_tmp1_);
	_g_ptr_array_unref0 (self->priv->_sprites);
	self->priv->_sprites = _tmp2_;
}


static void shmup_warz_render_position_system_real_execute (EntitasIExecuteSystem* base) {
	ShmupWarzRenderPositionSystem * self;
	EntitasGroup* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	EntitasEntity** _tmp2_ = NULL;
	self = (ShmupWarzRenderPositionSystem*) base;
	_tmp0_ = self->priv->_group;
	_tmp2_ = entitas_group_getEntities (_tmp0_, &_tmp1_);
	{
		EntitasEntity** entity_collection = NULL;
		gint entity_collection_length1 = 0;
		gint _entity_collection_size_ = 0;
		gint entity_it = 0;
		entity_collection = _tmp2_;
		entity_collection_length1 = _tmp1_;
		for (entity_it = 0; entity_it < _tmp1_; entity_it = entity_it + 1) {
			EntitasEntity* _tmp3_ = NULL;
			EntitasEntity* entity = NULL;
			_tmp3_ = _g_object_ref0 (entity_collection[entity_it]);
			entity = _tmp3_;
			{
				ShmupWarzResourceComponent* res = NULL;
				EntitasEntity* _tmp4_ = NULL;
				ShmupWarzResourceComponent* _tmp5_ = NULL;
				ShmupWarzPositionComponent* pos = NULL;
				EntitasEntity* _tmp6_ = NULL;
				ShmupWarzPositionComponent* _tmp7_ = NULL;
				BoscoSprite* sprite = NULL;
				ShmupWarzResourceComponent* _tmp8_ = NULL;
				GObject* _tmp9_ = NULL;
				BoscoSprite* _tmp10_ = NULL;
				BoscoSprite* _tmp11_ = NULL;
				ShmupWarzPositionComponent* _tmp12_ = NULL;
				gdouble _tmp13_ = 0.0;
				BoscoSprite* _tmp14_ = NULL;
				ShmupWarzPositionComponent* _tmp15_ = NULL;
				gdouble _tmp16_ = 0.0;
				_tmp4_ = entity;
				_tmp5_ = shmup_warz_getResource (_tmp4_);
				res = _tmp5_;
				_tmp6_ = entity;
				_tmp7_ = shmup_warz_getPosition (_tmp6_);
				pos = _tmp7_;
				_tmp8_ = res;
				_tmp9_ = _tmp8_->sprite;
				_tmp10_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp9_, BOSCO_TYPE_SPRITE, BoscoSprite));
				sprite = _tmp10_;
				_tmp11_ = sprite;
				_tmp12_ = pos;
				_tmp13_ = _tmp12_->x;
				_tmp11_->x = (gint) _tmp13_;
				_tmp14_ = sprite;
				_tmp15_ = pos;
				_tmp16_ = _tmp15_->y;
				_tmp14_->y = (gint) _tmp16_;
				_g_object_unref0 (sprite);
				_g_object_unref0 (pos);
				_g_object_unref0 (res);
				_g_object_unref0 (entity);
			}
		}
		entity_collection = (_vala_array_free (entity_collection, entity_collection_length1, (GDestroyNotify) g_object_unref), NULL);
	}
}


static void shmup_warz_render_position_system_class_init (ShmupWarzRenderPositionSystemClass * klass) {
	shmup_warz_render_position_system_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ShmupWarzRenderPositionSystemPrivate));
	G_OBJECT_CLASS (klass)->finalize = shmup_warz_render_position_system_finalize;
}


static void shmup_warz_render_position_system_entitas_isystem_interface_init (EntitasISystemIface * iface) {
	shmup_warz_render_position_system_entitas_isystem_parent_iface = g_type_interface_peek_parent (iface);
}


static void shmup_warz_render_position_system_entitas_iset_world_interface_init (EntitasISetWorldIface * iface) {
	shmup_warz_render_position_system_entitas_iset_world_parent_iface = g_type_interface_peek_parent (iface);
	iface->setWorld = (void (*)(EntitasISetWorld*, EntitasWorld*)) shmup_warz_render_position_system_real_setWorld;
}


static void shmup_warz_render_position_system_entitas_iinitialize_system_interface_init (EntitasIInitializeSystemIface * iface) {
	shmup_warz_render_position_system_entitas_iinitialize_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->initialize = (void (*)(EntitasIInitializeSystem*)) shmup_warz_render_position_system_real_initialize;
}


static void shmup_warz_render_position_system_entitas_iexecute_system_interface_init (EntitasIExecuteSystemIface * iface) {
	shmup_warz_render_position_system_entitas_iexecute_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->execute = (void (*)(EntitasIExecuteSystem*)) shmup_warz_render_position_system_real_execute;
}


static void shmup_warz_render_position_system_instance_init (ShmupWarzRenderPositionSystem * self) {
	self->priv = SHMUP_WARZ_RENDER_POSITION_SYSTEM_GET_PRIVATE (self);
}


static void shmup_warz_render_position_system_finalize (GObject* obj) {
	ShmupWarzRenderPositionSystem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHMUP_WARZ_TYPE_RENDER_POSITION_SYSTEM, ShmupWarzRenderPositionSystem);
	_g_object_unref0 (self->priv->_group);
	_g_object_unref0 (self->priv->_game);
	_g_ptr_array_unref0 (self->priv->_sprites);
	G_OBJECT_CLASS (shmup_warz_render_position_system_parent_class)->finalize (obj);
}


GType shmup_warz_render_position_system_get_type (void) {
	static volatile gsize shmup_warz_render_position_system_type_id__volatile = 0;
	if (g_once_init_enter (&shmup_warz_render_position_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShmupWarzRenderPositionSystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shmup_warz_render_position_system_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShmupWarzRenderPositionSystem), 0, (GInstanceInitFunc) shmup_warz_render_position_system_instance_init, NULL };
		static const GInterfaceInfo entitas_isystem_info = { (GInterfaceInitFunc) shmup_warz_render_position_system_entitas_isystem_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iset_world_info = { (GInterfaceInitFunc) shmup_warz_render_position_system_entitas_iset_world_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iinitialize_system_info = { (GInterfaceInitFunc) shmup_warz_render_position_system_entitas_iinitialize_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iexecute_system_info = { (GInterfaceInitFunc) shmup_warz_render_position_system_entitas_iexecute_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType shmup_warz_render_position_system_type_id;
		shmup_warz_render_position_system_type_id = g_type_register_static (G_TYPE_OBJECT, "ShmupWarzRenderPositionSystem", &g_define_type_info, 0);
		g_type_add_interface_static (shmup_warz_render_position_system_type_id, ENTITAS_TYPE_ISYSTEM, &entitas_isystem_info);
		g_type_add_interface_static (shmup_warz_render_position_system_type_id, ENTITAS_TYPE_ISET_WORLD, &entitas_iset_world_info);
		g_type_add_interface_static (shmup_warz_render_position_system_type_id, ENTITAS_TYPE_IINITIALIZE_SYSTEM, &entitas_iinitialize_system_info);
		g_type_add_interface_static (shmup_warz_render_position_system_type_id, ENTITAS_TYPE_IEXECUTE_SYSTEM, &entitas_iexecute_system_info);
		g_once_init_leave (&shmup_warz_render_position_system_type_id__volatile, shmup_warz_render_position_system_type_id);
	}
	return shmup_warz_render_position_system_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



