/* ScaleTweenSystem.c generated by valac 0.34.4, the Vala compiler
 * generated from ScaleTweenSystem.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <entitas.h>
#include <bosco.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>


#define SHMUP_WARZ_TYPE_SCALE_TWEEN_SYSTEM (shmup_warz_scale_tween_system_get_type ())
#define SHMUP_WARZ_SCALE_TWEEN_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_SCALE_TWEEN_SYSTEM, ShmupWarzScaleTweenSystem))
#define SHMUP_WARZ_SCALE_TWEEN_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_SCALE_TWEEN_SYSTEM, ShmupWarzScaleTweenSystemClass))
#define SHMUP_WARZ_IS_SCALE_TWEEN_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_SCALE_TWEEN_SYSTEM))
#define SHMUP_WARZ_IS_SCALE_TWEEN_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_SCALE_TWEEN_SYSTEM))
#define SHMUP_WARZ_SCALE_TWEEN_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_SCALE_TWEEN_SYSTEM, ShmupWarzScaleTweenSystemClass))

typedef struct _ShmupWarzScaleTweenSystem ShmupWarzScaleTweenSystem;
typedef struct _ShmupWarzScaleTweenSystemClass ShmupWarzScaleTweenSystemClass;
typedef struct _ShmupWarzScaleTweenSystemPrivate ShmupWarzScaleTweenSystemPrivate;

#define SHMUP_WARZ_TYPE_GAME (shmup_warz_game_get_type ())
#define SHMUP_WARZ_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGame))
#define SHMUP_WARZ_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))
#define SHMUP_WARZ_IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))

typedef struct _ShmupWarzGame ShmupWarzGame;
typedef struct _ShmupWarzGameClass ShmupWarzGameClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define SHMUP_WARZ_TYPE_COMPONENT (shmup_warz_component_get_type ())

#define SHMUP_WARZ_TYPE_SCALE_TWEEN_COMPONENT (shmup_warz_scale_tween_component_get_type ())
#define SHMUP_WARZ_SCALE_TWEEN_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_SCALE_TWEEN_COMPONENT, ShmupWarzScaleTweenComponent))
#define SHMUP_WARZ_SCALE_TWEEN_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_SCALE_TWEEN_COMPONENT, ShmupWarzScaleTweenComponentClass))
#define SHMUP_WARZ_IS_SCALE_TWEEN_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_SCALE_TWEEN_COMPONENT))
#define SHMUP_WARZ_IS_SCALE_TWEEN_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_SCALE_TWEEN_COMPONENT))
#define SHMUP_WARZ_SCALE_TWEEN_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_SCALE_TWEEN_COMPONENT, ShmupWarzScaleTweenComponentClass))

typedef struct _ShmupWarzScaleTweenComponent ShmupWarzScaleTweenComponent;
typedef struct _ShmupWarzScaleTweenComponentClass ShmupWarzScaleTweenComponentClass;
typedef struct _ShmupWarzScaleTweenComponentPrivate ShmupWarzScaleTweenComponentPrivate;

#define SHMUP_WARZ_TYPE_RESOURCE_COMPONENT (shmup_warz_resource_component_get_type ())
#define SHMUP_WARZ_RESOURCE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_RESOURCE_COMPONENT, ShmupWarzResourceComponent))
#define SHMUP_WARZ_RESOURCE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_RESOURCE_COMPONENT, ShmupWarzResourceComponentClass))
#define SHMUP_WARZ_IS_RESOURCE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_RESOURCE_COMPONENT))
#define SHMUP_WARZ_IS_RESOURCE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_RESOURCE_COMPONENT))
#define SHMUP_WARZ_RESOURCE_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_RESOURCE_COMPONENT, ShmupWarzResourceComponentClass))

typedef struct _ShmupWarzResourceComponent ShmupWarzResourceComponent;
typedef struct _ShmupWarzResourceComponentClass ShmupWarzResourceComponentClass;
typedef struct _ShmupWarzResourceComponentPrivate ShmupWarzResourceComponentPrivate;

struct _ShmupWarzScaleTweenSystem {
	GObject parent_instance;
	ShmupWarzScaleTweenSystemPrivate * priv;
};

struct _ShmupWarzScaleTweenSystemClass {
	GObjectClass parent_class;
};

struct _ShmupWarzScaleTweenSystemPrivate {
	EntitasWorld* _world;
	EntitasGroup* _group;
	ShmupWarzGame* _game;
};

typedef enum  {
	SHMUP_WARZ_COMPONENT_Bounds,
	SHMUP_WARZ_COMPONENT_Bullet,
	SHMUP_WARZ_COMPONENT_ColorTween,
	SHMUP_WARZ_COMPONENT_Destroy,
	SHMUP_WARZ_COMPONENT_Enemy,
	SHMUP_WARZ_COMPONENT_Expires,
	SHMUP_WARZ_COMPONENT_Firing,
	SHMUP_WARZ_COMPONENT_Health,
	SHMUP_WARZ_COMPONENT_Layer,
	SHMUP_WARZ_COMPONENT_Life,
	SHMUP_WARZ_COMPONENT_Mine,
	SHMUP_WARZ_COMPONENT_Mouse,
	SHMUP_WARZ_COMPONENT_Player,
	SHMUP_WARZ_COMPONENT_Position,
	SHMUP_WARZ_COMPONENT_Resource,
	SHMUP_WARZ_COMPONENT_ScaleTween,
	SHMUP_WARZ_COMPONENT_Scale,
	SHMUP_WARZ_COMPONENT_Score,
	SHMUP_WARZ_COMPONENT_SoundEffect,
	SHMUP_WARZ_COMPONENT_Text,
	SHMUP_WARZ_COMPONENT_Tint,
	SHMUP_WARZ_COMPONENT_Velocity,
	SHMUP_WARZ_COMPONENT_ComponentsCount
} ShmupWarzComponent;

struct _ShmupWarzScaleTweenComponent {
	GObject parent_instance;
	ShmupWarzScaleTweenComponentPrivate * priv;
	gdouble min;
	gdouble max;
	gdouble speed;
	gboolean repeat;
	gboolean active;
};

struct _ShmupWarzScaleTweenComponentClass {
	GObjectClass parent_class;
};

struct _ShmupWarzResourceComponent {
	GObject parent_instance;
	ShmupWarzResourceComponentPrivate * priv;
	gchar* path;
	GObject* sprite;
	gboolean bgd;
};

struct _ShmupWarzResourceComponentClass {
	GObjectClass parent_class;
};


static gpointer shmup_warz_scale_tween_system_parent_class = NULL;
static EntitasISystemIface* shmup_warz_scale_tween_system_entitas_isystem_parent_iface = NULL;
static EntitasISetWorldIface* shmup_warz_scale_tween_system_entitas_iset_world_parent_iface = NULL;
static EntitasIInitializeSystemIface* shmup_warz_scale_tween_system_entitas_iinitialize_system_parent_iface = NULL;
static EntitasIExecuteSystemIface* shmup_warz_scale_tween_system_entitas_iexecute_system_parent_iface = NULL;

GType shmup_warz_scale_tween_system_get_type (void) G_GNUC_CONST;
GType shmup_warz_game_get_type (void) G_GNUC_CONST;
#define SHMUP_WARZ_SCALE_TWEEN_SYSTEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SHMUP_WARZ_TYPE_SCALE_TWEEN_SYSTEM, ShmupWarzScaleTweenSystemPrivate))
enum  {
	SHMUP_WARZ_SCALE_TWEEN_SYSTEM_DUMMY_PROPERTY
};
ShmupWarzScaleTweenSystem* shmup_warz_scale_tween_system_new (ShmupWarzGame* game);
ShmupWarzScaleTweenSystem* shmup_warz_scale_tween_system_construct (GType object_type, ShmupWarzGame* game);
static void shmup_warz_scale_tween_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world);
static void shmup_warz_scale_tween_system_real_initialize (EntitasIInitializeSystem* base);
GType shmup_warz_component_get_type (void) G_GNUC_CONST;
static void shmup_warz_scale_tween_system_real_execute (EntitasIExecuteSystem* base);
GType shmup_warz_scale_tween_component_get_type (void) G_GNUC_CONST;
ShmupWarzScaleTweenComponent* shmup_warz_getScaleTween (EntitasEntity* e);
GType shmup_warz_resource_component_get_type (void) G_GNUC_CONST;
ShmupWarzResourceComponent* shmup_warz_getResource (EntitasEntity* e);
static void shmup_warz_scale_tween_system_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


ShmupWarzScaleTweenSystem* shmup_warz_scale_tween_system_construct (GType object_type, ShmupWarzGame* game) {
	ShmupWarzScaleTweenSystem * self = NULL;
	ShmupWarzGame* _tmp0_ = NULL;
	ShmupWarzGame* _tmp1_ = NULL;
	g_return_val_if_fail (game != NULL, NULL);
	self = (ShmupWarzScaleTweenSystem*) g_object_new (object_type, NULL);
	_tmp0_ = game;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_game);
	self->priv->_game = _tmp1_;
	return self;
}


ShmupWarzScaleTweenSystem* shmup_warz_scale_tween_system_new (ShmupWarzGame* game) {
	return shmup_warz_scale_tween_system_construct (SHMUP_WARZ_TYPE_SCALE_TWEEN_SYSTEM, game);
}


static void shmup_warz_scale_tween_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world) {
	ShmupWarzScaleTweenSystem * self;
	EntitasWorld* _tmp0_ = NULL;
	EntitasWorld* _tmp1_ = NULL;
	self = (ShmupWarzScaleTweenSystem*) base;
	g_return_if_fail (world != NULL);
	_tmp0_ = world;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_world);
	self->priv->_world = _tmp1_;
}


static void shmup_warz_scale_tween_system_real_initialize (EntitasIInitializeSystem* base) {
	ShmupWarzScaleTweenSystem * self;
	EntitasWorld* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	EntitasIMatcher* _tmp3_ = NULL;
	EntitasIMatcher* _tmp4_ = NULL;
	EntitasGroup* _tmp5_ = NULL;
	self = (ShmupWarzScaleTweenSystem*) base;
	_tmp0_ = self->priv->_world;
	_tmp1_ = g_new0 (gint, 2);
	_tmp1_[0] = (gint) SHMUP_WARZ_COMPONENT_ScaleTween;
	_tmp1_[1] = (gint) SHMUP_WARZ_COMPONENT_Resource;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = 2;
	_tmp3_ = entitas_matcher_AllOf (_tmp2_, 2);
	_tmp4_ = _tmp3_;
	_tmp5_ = entitas_world_getGroup (_tmp0_, _tmp4_);
	_g_object_unref0 (self->priv->_group);
	self->priv->_group = _tmp5_;
	_g_object_unref0 (_tmp4_);
	_tmp2_ = (g_free (_tmp2_), NULL);
}


static void shmup_warz_scale_tween_system_real_execute (EntitasIExecuteSystem* base) {
	ShmupWarzScaleTweenSystem * self;
	EntitasGroup* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	EntitasEntity** _tmp2_ = NULL;
	self = (ShmupWarzScaleTweenSystem*) base;
	_tmp0_ = self->priv->_group;
	_tmp2_ = entitas_group_getEntities (_tmp0_, &_tmp1_);
	{
		EntitasEntity** entity_collection = NULL;
		gint entity_collection_length1 = 0;
		gint _entity_collection_size_ = 0;
		gint entity_it = 0;
		entity_collection = _tmp2_;
		entity_collection_length1 = _tmp1_;
		for (entity_it = 0; entity_it < _tmp1_; entity_it = entity_it + 1) {
			EntitasEntity* _tmp3_ = NULL;
			EntitasEntity* entity = NULL;
			_tmp3_ = _g_object_ref0 (entity_collection[entity_it]);
			entity = _tmp3_;
			{
				ShmupWarzScaleTweenComponent* scaleTween = NULL;
				EntitasEntity* _tmp4_ = NULL;
				ShmupWarzScaleTweenComponent* _tmp5_ = NULL;
				ShmupWarzScaleTweenComponent* _tmp6_ = NULL;
				gboolean _tmp7_ = FALSE;
				_tmp4_ = entity;
				_tmp5_ = shmup_warz_getScaleTween (_tmp4_);
				scaleTween = _tmp5_;
				_tmp6_ = scaleTween;
				_tmp7_ = _tmp6_->active;
				if (_tmp7_) {
					ShmupWarzResourceComponent* res = NULL;
					EntitasEntity* _tmp8_ = NULL;
					ShmupWarzResourceComponent* _tmp9_ = NULL;
					BoscoSprite* sprite = NULL;
					ShmupWarzResourceComponent* _tmp10_ = NULL;
					GObject* _tmp11_ = NULL;
					BoscoSprite* _tmp12_ = NULL;
					BoscoScale scale = {0};
					BoscoSprite* _tmp13_ = NULL;
					BoscoScale _tmp14_ = {0};
					BoscoSprite* _tmp15_ = NULL;
					BoscoSprite* _tmp16_ = NULL;
					gdouble _tmp17_ = 0.0;
					ShmupWarzScaleTweenComponent* _tmp18_ = NULL;
					gdouble _tmp19_ = 0.0;
					ShmupWarzGame* _tmp20_ = NULL;
					gdouble _tmp21_ = 0.0;
					gdouble _tmp22_ = 0.0;
					BoscoSprite* _tmp23_ = NULL;
					BoscoSprite* _tmp24_ = NULL;
					gdouble _tmp25_ = 0.0;
					ShmupWarzScaleTweenComponent* _tmp26_ = NULL;
					gdouble _tmp27_ = 0.0;
					ShmupWarzGame* _tmp28_ = NULL;
					gdouble _tmp29_ = 0.0;
					gdouble _tmp30_ = 0.0;
					BoscoScale _tmp31_ = {0};
					gdouble _tmp32_ = 0.0;
					ShmupWarzScaleTweenComponent* _tmp33_ = NULL;
					gdouble _tmp34_ = 0.0;
					_tmp8_ = entity;
					_tmp9_ = shmup_warz_getResource (_tmp8_);
					res = _tmp9_;
					_tmp10_ = res;
					_tmp11_ = _tmp10_->sprite;
					_tmp12_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp11_, BOSCO_TYPE_SPRITE, BoscoSprite));
					sprite = _tmp12_;
					_tmp13_ = sprite;
					_tmp14_ = _tmp13_->scale;
					scale = _tmp14_;
					_tmp15_ = sprite;
					_tmp16_ = sprite;
					_tmp17_ = _tmp16_->scale.x;
					_tmp18_ = scaleTween;
					_tmp19_ = _tmp18_->speed;
					_tmp20_ = self->priv->_game;
					_tmp21_ = bosco_abstract_game_get_delta ((BoscoAbstractGame*) _tmp20_);
					_tmp22_ = _tmp21_;
					_tmp16_->scale.x = _tmp17_ + (_tmp19_ * _tmp22_);
					_tmp23_ = sprite;
					_tmp24_ = sprite;
					_tmp25_ = _tmp24_->scale.y;
					_tmp26_ = scaleTween;
					_tmp27_ = _tmp26_->speed;
					_tmp28_ = self->priv->_game;
					_tmp29_ = bosco_abstract_game_get_delta ((BoscoAbstractGame*) _tmp28_);
					_tmp30_ = _tmp29_;
					_tmp24_->scale.y = _tmp25_ + (_tmp27_ * _tmp30_);
					_tmp31_ = scale;
					_tmp32_ = _tmp31_.x;
					_tmp33_ = scaleTween;
					_tmp34_ = _tmp33_->max;
					if (_tmp32_ > _tmp34_) {
						BoscoSprite* _tmp35_ = NULL;
						ShmupWarzScaleTweenComponent* _tmp36_ = NULL;
						gdouble _tmp37_ = 0.0;
						BoscoSprite* _tmp38_ = NULL;
						ShmupWarzScaleTweenComponent* _tmp39_ = NULL;
						gdouble _tmp40_ = 0.0;
						ShmupWarzScaleTweenComponent* _tmp41_ = NULL;
						_tmp35_ = sprite;
						_tmp36_ = scaleTween;
						_tmp37_ = _tmp36_->max;
						_tmp35_->scale.x = _tmp37_;
						_tmp38_ = sprite;
						_tmp39_ = scaleTween;
						_tmp40_ = _tmp39_->max;
						_tmp38_->scale.y = _tmp40_;
						_tmp41_ = scaleTween;
						_tmp41_->active = FALSE;
					} else {
						BoscoScale _tmp42_ = {0};
						gdouble _tmp43_ = 0.0;
						ShmupWarzScaleTweenComponent* _tmp44_ = NULL;
						gdouble _tmp45_ = 0.0;
						_tmp42_ = scale;
						_tmp43_ = _tmp42_.x;
						_tmp44_ = scaleTween;
						_tmp45_ = _tmp44_->min;
						if (_tmp43_ < _tmp45_) {
							BoscoSprite* _tmp46_ = NULL;
							ShmupWarzScaleTweenComponent* _tmp47_ = NULL;
							gdouble _tmp48_ = 0.0;
							BoscoSprite* _tmp49_ = NULL;
							ShmupWarzScaleTweenComponent* _tmp50_ = NULL;
							gdouble _tmp51_ = 0.0;
							ShmupWarzScaleTweenComponent* _tmp52_ = NULL;
							_tmp46_ = sprite;
							_tmp47_ = scaleTween;
							_tmp48_ = _tmp47_->min;
							_tmp46_->scale.x = _tmp48_;
							_tmp49_ = sprite;
							_tmp50_ = scaleTween;
							_tmp51_ = _tmp50_->min;
							_tmp49_->scale.y = _tmp51_;
							_tmp52_ = scaleTween;
							_tmp52_->active = FALSE;
						}
					}
					_g_object_unref0 (sprite);
					_g_object_unref0 (res);
				}
				_g_object_unref0 (scaleTween);
				_g_object_unref0 (entity);
			}
		}
		entity_collection = (_vala_array_free (entity_collection, entity_collection_length1, (GDestroyNotify) g_object_unref), NULL);
	}
}


static void shmup_warz_scale_tween_system_class_init (ShmupWarzScaleTweenSystemClass * klass) {
	shmup_warz_scale_tween_system_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ShmupWarzScaleTweenSystemPrivate));
	G_OBJECT_CLASS (klass)->finalize = shmup_warz_scale_tween_system_finalize;
}


static void shmup_warz_scale_tween_system_entitas_isystem_interface_init (EntitasISystemIface * iface) {
	shmup_warz_scale_tween_system_entitas_isystem_parent_iface = g_type_interface_peek_parent (iface);
}


static void shmup_warz_scale_tween_system_entitas_iset_world_interface_init (EntitasISetWorldIface * iface) {
	shmup_warz_scale_tween_system_entitas_iset_world_parent_iface = g_type_interface_peek_parent (iface);
	iface->setWorld = (void (*)(EntitasISetWorld*, EntitasWorld*)) shmup_warz_scale_tween_system_real_setWorld;
}


static void shmup_warz_scale_tween_system_entitas_iinitialize_system_interface_init (EntitasIInitializeSystemIface * iface) {
	shmup_warz_scale_tween_system_entitas_iinitialize_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->initialize = (void (*)(EntitasIInitializeSystem*)) shmup_warz_scale_tween_system_real_initialize;
}


static void shmup_warz_scale_tween_system_entitas_iexecute_system_interface_init (EntitasIExecuteSystemIface * iface) {
	shmup_warz_scale_tween_system_entitas_iexecute_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->execute = (void (*)(EntitasIExecuteSystem*)) shmup_warz_scale_tween_system_real_execute;
}


static void shmup_warz_scale_tween_system_instance_init (ShmupWarzScaleTweenSystem * self) {
	self->priv = SHMUP_WARZ_SCALE_TWEEN_SYSTEM_GET_PRIVATE (self);
}


static void shmup_warz_scale_tween_system_finalize (GObject* obj) {
	ShmupWarzScaleTweenSystem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHMUP_WARZ_TYPE_SCALE_TWEEN_SYSTEM, ShmupWarzScaleTweenSystem);
	_g_object_unref0 (self->priv->_world);
	_g_object_unref0 (self->priv->_group);
	_g_object_unref0 (self->priv->_game);
	G_OBJECT_CLASS (shmup_warz_scale_tween_system_parent_class)->finalize (obj);
}


GType shmup_warz_scale_tween_system_get_type (void) {
	static volatile gsize shmup_warz_scale_tween_system_type_id__volatile = 0;
	if (g_once_init_enter (&shmup_warz_scale_tween_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShmupWarzScaleTweenSystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shmup_warz_scale_tween_system_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShmupWarzScaleTweenSystem), 0, (GInstanceInitFunc) shmup_warz_scale_tween_system_instance_init, NULL };
		static const GInterfaceInfo entitas_isystem_info = { (GInterfaceInitFunc) shmup_warz_scale_tween_system_entitas_isystem_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iset_world_info = { (GInterfaceInitFunc) shmup_warz_scale_tween_system_entitas_iset_world_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iinitialize_system_info = { (GInterfaceInitFunc) shmup_warz_scale_tween_system_entitas_iinitialize_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iexecute_system_info = { (GInterfaceInitFunc) shmup_warz_scale_tween_system_entitas_iexecute_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType shmup_warz_scale_tween_system_type_id;
		shmup_warz_scale_tween_system_type_id = g_type_register_static (G_TYPE_OBJECT, "ShmupWarzScaleTweenSystem", &g_define_type_info, 0);
		g_type_add_interface_static (shmup_warz_scale_tween_system_type_id, ENTITAS_TYPE_ISYSTEM, &entitas_isystem_info);
		g_type_add_interface_static (shmup_warz_scale_tween_system_type_id, ENTITAS_TYPE_ISET_WORLD, &entitas_iset_world_info);
		g_type_add_interface_static (shmup_warz_scale_tween_system_type_id, ENTITAS_TYPE_IINITIALIZE_SYSTEM, &entitas_iinitialize_system_info);
		g_type_add_interface_static (shmup_warz_scale_tween_system_type_id, ENTITAS_TYPE_IEXECUTE_SYSTEM, &entitas_iexecute_system_info);
		g_once_init_leave (&shmup_warz_scale_tween_system_type_id__volatile, shmup_warz_scale_tween_system_type_id);
	}
	return shmup_warz_scale_tween_system_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



