/* SoundEffectSystem.c generated by valac 0.34.4, the Vala compiler
 * generated from SoundEffectSystem.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <Entitas.h>
#include <Bosco.h>
#include <SDL2/SDL_mixer.h>
#include <stdlib.h>
#include <string.h>


#define SHMUP_WARZ_TYPE_SOUND_EFFECT_SYSTEM (shmup_warz_sound_effect_system_get_type ())
#define SHMUP_WARZ_SOUND_EFFECT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_SOUND_EFFECT_SYSTEM, ShmupWarzSoundEffectSystem))
#define SHMUP_WARZ_SOUND_EFFECT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_SOUND_EFFECT_SYSTEM, ShmupWarzSoundEffectSystemClass))
#define SHMUP_WARZ_IS_SOUND_EFFECT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_SOUND_EFFECT_SYSTEM))
#define SHMUP_WARZ_IS_SOUND_EFFECT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_SOUND_EFFECT_SYSTEM))
#define SHMUP_WARZ_SOUND_EFFECT_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_SOUND_EFFECT_SYSTEM, ShmupWarzSoundEffectSystemClass))

typedef struct _ShmupWarzSoundEffectSystem ShmupWarzSoundEffectSystem;
typedef struct _ShmupWarzSoundEffectSystemClass ShmupWarzSoundEffectSystemClass;
typedef struct _ShmupWarzSoundEffectSystemPrivate ShmupWarzSoundEffectSystemPrivate;

#define SHMUP_WARZ_TYPE_GAME (shmup_warz_game_get_type ())
#define SHMUP_WARZ_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGame))
#define SHMUP_WARZ_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))
#define SHMUP_WARZ_IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))

typedef struct _ShmupWarzGame ShmupWarzGame;
typedef struct _ShmupWarzGameClass ShmupWarzGameClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _Mix_FreeChunk0(var) ((var == NULL) ? NULL : (var = (Mix_FreeChunk (var), NULL)))

#define SHMUP_WARZ_TYPE_COMPONENT (shmup_warz_component_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))

#define SHMUP_WARZ_TYPE_SOUND_EFFECT_COMPONENT (shmup_warz_sound_effect_component_get_type ())
#define SHMUP_WARZ_SOUND_EFFECT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_SOUND_EFFECT_COMPONENT, ShmupWarzSoundEffectComponent))
#define SHMUP_WARZ_SOUND_EFFECT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_SOUND_EFFECT_COMPONENT, ShmupWarzSoundEffectComponentClass))
#define SHMUP_WARZ_IS_SOUND_EFFECT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_SOUND_EFFECT_COMPONENT))
#define SHMUP_WARZ_IS_SOUND_EFFECT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_SOUND_EFFECT_COMPONENT))
#define SHMUP_WARZ_SOUND_EFFECT_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_SOUND_EFFECT_COMPONENT, ShmupWarzSoundEffectComponentClass))

typedef struct _ShmupWarzSoundEffectComponent ShmupWarzSoundEffectComponent;
typedef struct _ShmupWarzSoundEffectComponentClass ShmupWarzSoundEffectComponentClass;
typedef struct _ShmupWarzSoundEffectComponentPrivate ShmupWarzSoundEffectComponentPrivate;

struct _ShmupWarzSoundEffectSystem {
	GObject parent_instance;
	ShmupWarzSoundEffectSystemPrivate * priv;
};

struct _ShmupWarzSoundEffectSystemClass {
	GObjectClass parent_class;
};

struct _ShmupWarzSoundEffectSystemPrivate {
	EntitasGroup* _group;
	ShmupWarzGame* _game;
	Mix_Chunk* _pew;
	Mix_Chunk* _asplode;
	Mix_Chunk* _smallasplode;
};

typedef enum  {
	SHMUP_WARZ_COMPONENT_Bounds,
	SHMUP_WARZ_COMPONENT_Bullet,
	SHMUP_WARZ_COMPONENT_ColorTween,
	SHMUP_WARZ_COMPONENT_Destroy,
	SHMUP_WARZ_COMPONENT_Enemy,
	SHMUP_WARZ_COMPONENT_Expires,
	SHMUP_WARZ_COMPONENT_Firing,
	SHMUP_WARZ_COMPONENT_Health,
	SHMUP_WARZ_COMPONENT_Layer,
	SHMUP_WARZ_COMPONENT_Life,
	SHMUP_WARZ_COMPONENT_Mine,
	SHMUP_WARZ_COMPONENT_Mouse,
	SHMUP_WARZ_COMPONENT_Player,
	SHMUP_WARZ_COMPONENT_Position,
	SHMUP_WARZ_COMPONENT_Resource,
	SHMUP_WARZ_COMPONENT_ScaleTween,
	SHMUP_WARZ_COMPONENT_Scale,
	SHMUP_WARZ_COMPONENT_Score,
	SHMUP_WARZ_COMPONENT_SoundEffect,
	SHMUP_WARZ_COMPONENT_Text,
	SHMUP_WARZ_COMPONENT_Tint,
	SHMUP_WARZ_COMPONENT_Velocity,
	SHMUP_WARZ_COMPONENT_ComponentsCount
} ShmupWarzComponent;

struct _ShmupWarzSoundEffectComponent {
	GObject parent_instance;
	ShmupWarzSoundEffectComponentPrivate * priv;
	gint effect;
};

struct _ShmupWarzSoundEffectComponentClass {
	GObjectClass parent_class;
};


static gpointer shmup_warz_sound_effect_system_parent_class = NULL;
static EntitasISystemIface* shmup_warz_sound_effect_system_entitas_isystem_parent_iface = NULL;
static EntitasISetWorldIface* shmup_warz_sound_effect_system_entitas_iset_world_parent_iface = NULL;
static EntitasIInitializeSystemIface* shmup_warz_sound_effect_system_entitas_iinitialize_system_parent_iface = NULL;
static EntitasIExecuteSystemIface* shmup_warz_sound_effect_system_entitas_iexecute_system_parent_iface = NULL;

GType shmup_warz_sound_effect_system_get_type (void) G_GNUC_CONST;
GType shmup_warz_game_get_type (void) G_GNUC_CONST;
#define SHMUP_WARZ_SOUND_EFFECT_SYSTEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SHMUP_WARZ_TYPE_SOUND_EFFECT_SYSTEM, ShmupWarzSoundEffectSystemPrivate))
enum  {
	SHMUP_WARZ_SOUND_EFFECT_SYSTEM_DUMMY_PROPERTY
};
ShmupWarzSoundEffectSystem* shmup_warz_sound_effect_system_new (ShmupWarzGame* game);
ShmupWarzSoundEffectSystem* shmup_warz_sound_effect_system_construct (GType object_type, ShmupWarzGame* game);
static void shmup_warz_sound_effect_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world);
GType shmup_warz_component_get_type (void) G_GNUC_CONST;
static void shmup_warz_sound_effect_system_real_initialize (EntitasIInitializeSystem* base);
#define SHMUP_WARZ_RES "/usr/local/share/shmupwarz"
static void shmup_warz_sound_effect_system_real_execute (EntitasIExecuteSystem* base);
GType shmup_warz_sound_effect_component_get_type (void) G_GNUC_CONST;
ShmupWarzSoundEffectComponent* shmup_warz_getSoundEffect (EntitasEntity* e);
static void shmup_warz_sound_effect_system_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


ShmupWarzSoundEffectSystem* shmup_warz_sound_effect_system_construct (GType object_type, ShmupWarzGame* game) {
	ShmupWarzSoundEffectSystem * self = NULL;
	ShmupWarzGame* _tmp0_ = NULL;
	ShmupWarzGame* _tmp1_ = NULL;
	g_return_val_if_fail (game != NULL, NULL);
	self = (ShmupWarzSoundEffectSystem*) g_object_new (object_type, NULL);
	_tmp0_ = game;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_game);
	self->priv->_game = _tmp1_;
	return self;
}


ShmupWarzSoundEffectSystem* shmup_warz_sound_effect_system_new (ShmupWarzGame* game) {
	return shmup_warz_sound_effect_system_construct (SHMUP_WARZ_TYPE_SOUND_EFFECT_SYSTEM, game);
}


static void shmup_warz_sound_effect_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world) {
	ShmupWarzSoundEffectSystem * self;
	EntitasWorld* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	EntitasIMatcher* _tmp3_ = NULL;
	EntitasIMatcher* _tmp4_ = NULL;
	EntitasGroup* _tmp5_ = NULL;
	self = (ShmupWarzSoundEffectSystem*) base;
	g_return_if_fail (world != NULL);
	_tmp0_ = world;
	_tmp1_ = g_new0 (gint, 1);
	_tmp1_[0] = (gint) SHMUP_WARZ_COMPONENT_SoundEffect;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = 1;
	_tmp3_ = entitas_matcher_AllOf (_tmp2_, 1);
	_tmp4_ = _tmp3_;
	_tmp5_ = entitas_world_getGroup (_tmp0_, _tmp4_);
	_g_object_unref0 (self->priv->_group);
	self->priv->_group = _tmp5_;
	_g_object_unref0 (_tmp4_);
	_tmp2_ = (g_free (_tmp2_), NULL);
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static void shmup_warz_sound_effect_system_real_initialize (EntitasIInitializeSystem* base) {
	ShmupWarzSoundEffectSystem * self;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	Mix_Chunk* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	Mix_Chunk* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	Mix_Chunk* _tmp11_ = NULL;
	self = (ShmupWarzSoundEffectSystem*) base;
	_tmp0_ = string_to_string (SHMUP_WARZ_RES);
	_tmp1_ = g_strconcat (_tmp0_, "/sounds/pew.wav", NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = Mix_LoadWAV (_tmp2_);
	_Mix_FreeChunk0 (self->priv->_pew);
	self->priv->_pew = _tmp3_;
	_g_free0 (_tmp2_);
	_tmp4_ = string_to_string (SHMUP_WARZ_RES);
	_tmp5_ = g_strconcat (_tmp4_, "/sounds/asplode.wav", NULL);
	_tmp6_ = _tmp5_;
	_tmp7_ = Mix_LoadWAV (_tmp6_);
	_Mix_FreeChunk0 (self->priv->_asplode);
	self->priv->_asplode = _tmp7_;
	_g_free0 (_tmp6_);
	_tmp8_ = string_to_string (SHMUP_WARZ_RES);
	_tmp9_ = g_strconcat (_tmp8_, "/sounds/smallasplode.wav", NULL);
	_tmp10_ = _tmp9_;
	_tmp11_ = Mix_LoadWAV (_tmp10_);
	_Mix_FreeChunk0 (self->priv->_smallasplode);
	self->priv->_smallasplode = _tmp11_;
	_g_free0 (_tmp10_);
}


static void shmup_warz_sound_effect_system_real_execute (EntitasIExecuteSystem* base) {
	ShmupWarzSoundEffectSystem * self;
	EntitasGroup* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	EntitasEntity** _tmp2_ = NULL;
	self = (ShmupWarzSoundEffectSystem*) base;
	_tmp0_ = self->priv->_group;
	_tmp2_ = entitas_group_getEntities (_tmp0_, &_tmp1_);
	{
		EntitasEntity** entity_collection = NULL;
		gint entity_collection_length1 = 0;
		gint _entity_collection_size_ = 0;
		gint entity_it = 0;
		entity_collection = _tmp2_;
		entity_collection_length1 = _tmp1_;
		for (entity_it = 0; entity_it < _tmp1_; entity_it = entity_it + 1) {
			EntitasEntity* _tmp3_ = NULL;
			EntitasEntity* entity = NULL;
			_tmp3_ = _g_object_ref0 (entity_collection[entity_it]);
			entity = _tmp3_;
			{
				EntitasEntity* _tmp4_ = NULL;
				ShmupWarzSoundEffectComponent* _tmp5_ = NULL;
				ShmupWarzSoundEffectComponent* _tmp6_ = NULL;
				gint _tmp7_ = 0;
				gint _tmp8_ = 0;
				_tmp4_ = entity;
				_tmp5_ = shmup_warz_getSoundEffect (_tmp4_);
				_tmp6_ = _tmp5_;
				_tmp7_ = _tmp6_->effect;
				_tmp8_ = _tmp7_;
				_g_object_unref0 (_tmp6_);
				switch (_tmp8_) {
					case 0:
					{
						{
							Mix_Chunk* _tmp9_ = NULL;
							_tmp9_ = self->priv->_pew;
							Mix_PlayChannel (-1, _tmp9_, 0);
						}
						break;
					}
					case 1:
					{
						{
							Mix_Chunk* _tmp10_ = NULL;
							_tmp10_ = self->priv->_asplode;
							Mix_PlayChannel (-1, _tmp10_, 0);
						}
						break;
					}
					case 2:
					{
						{
							Mix_Chunk* _tmp11_ = NULL;
							_tmp11_ = self->priv->_smallasplode;
							Mix_PlayChannel (-1, _tmp11_, 0);
						}
						break;
					}
					default:
					break;
				}
				_g_object_unref0 (entity);
			}
		}
		entity_collection = (_vala_array_free (entity_collection, entity_collection_length1, (GDestroyNotify) g_object_unref), NULL);
	}
}


static void shmup_warz_sound_effect_system_class_init (ShmupWarzSoundEffectSystemClass * klass) {
	shmup_warz_sound_effect_system_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ShmupWarzSoundEffectSystemPrivate));
	G_OBJECT_CLASS (klass)->finalize = shmup_warz_sound_effect_system_finalize;
}


static void shmup_warz_sound_effect_system_entitas_isystem_interface_init (EntitasISystemIface * iface) {
	shmup_warz_sound_effect_system_entitas_isystem_parent_iface = g_type_interface_peek_parent (iface);
}


static void shmup_warz_sound_effect_system_entitas_iset_world_interface_init (EntitasISetWorldIface * iface) {
	shmup_warz_sound_effect_system_entitas_iset_world_parent_iface = g_type_interface_peek_parent (iface);
	iface->setWorld = (void (*)(EntitasISetWorld*, EntitasWorld*)) shmup_warz_sound_effect_system_real_setWorld;
}


static void shmup_warz_sound_effect_system_entitas_iinitialize_system_interface_init (EntitasIInitializeSystemIface * iface) {
	shmup_warz_sound_effect_system_entitas_iinitialize_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->initialize = (void (*)(EntitasIInitializeSystem*)) shmup_warz_sound_effect_system_real_initialize;
}


static void shmup_warz_sound_effect_system_entitas_iexecute_system_interface_init (EntitasIExecuteSystemIface * iface) {
	shmup_warz_sound_effect_system_entitas_iexecute_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->execute = (void (*)(EntitasIExecuteSystem*)) shmup_warz_sound_effect_system_real_execute;
}


static void shmup_warz_sound_effect_system_instance_init (ShmupWarzSoundEffectSystem * self) {
	self->priv = SHMUP_WARZ_SOUND_EFFECT_SYSTEM_GET_PRIVATE (self);
}


static void shmup_warz_sound_effect_system_finalize (GObject* obj) {
	ShmupWarzSoundEffectSystem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHMUP_WARZ_TYPE_SOUND_EFFECT_SYSTEM, ShmupWarzSoundEffectSystem);
	_g_object_unref0 (self->priv->_group);
	_g_object_unref0 (self->priv->_game);
	_Mix_FreeChunk0 (self->priv->_pew);
	_Mix_FreeChunk0 (self->priv->_asplode);
	_Mix_FreeChunk0 (self->priv->_smallasplode);
	G_OBJECT_CLASS (shmup_warz_sound_effect_system_parent_class)->finalize (obj);
}


GType shmup_warz_sound_effect_system_get_type (void) {
	static volatile gsize shmup_warz_sound_effect_system_type_id__volatile = 0;
	if (g_once_init_enter (&shmup_warz_sound_effect_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShmupWarzSoundEffectSystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shmup_warz_sound_effect_system_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShmupWarzSoundEffectSystem), 0, (GInstanceInitFunc) shmup_warz_sound_effect_system_instance_init, NULL };
		static const GInterfaceInfo entitas_isystem_info = { (GInterfaceInitFunc) shmup_warz_sound_effect_system_entitas_isystem_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iset_world_info = { (GInterfaceInitFunc) shmup_warz_sound_effect_system_entitas_iset_world_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iinitialize_system_info = { (GInterfaceInitFunc) shmup_warz_sound_effect_system_entitas_iinitialize_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iexecute_system_info = { (GInterfaceInitFunc) shmup_warz_sound_effect_system_entitas_iexecute_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType shmup_warz_sound_effect_system_type_id;
		shmup_warz_sound_effect_system_type_id = g_type_register_static (G_TYPE_OBJECT, "ShmupWarzSoundEffectSystem", &g_define_type_info, 0);
		g_type_add_interface_static (shmup_warz_sound_effect_system_type_id, ENTITAS_TYPE_ISYSTEM, &entitas_isystem_info);
		g_type_add_interface_static (shmup_warz_sound_effect_system_type_id, ENTITAS_TYPE_ISET_WORLD, &entitas_iset_world_info);
		g_type_add_interface_static (shmup_warz_sound_effect_system_type_id, ENTITAS_TYPE_IINITIALIZE_SYSTEM, &entitas_iinitialize_system_info);
		g_type_add_interface_static (shmup_warz_sound_effect_system_type_id, ENTITAS_TYPE_IEXECUTE_SYSTEM, &entitas_iexecute_system_info);
		g_once_init_leave (&shmup_warz_sound_effect_system_type_id__volatile, shmup_warz_sound_effect_system_type_id);
	}
	return shmup_warz_sound_effect_system_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



