/* ViewManagerSystem.c generated by valac 0.34.4, the Vala compiler
 * generated from ViewManagerSystem.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <entitas.h>
#include <SDL2/SDL_render.h>
#include <bosco.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define SHMUP_WARZ_TYPE_VIEW_MANAGER_SYSTEM (shmup_warz_view_manager_system_get_type ())
#define SHMUP_WARZ_VIEW_MANAGER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_VIEW_MANAGER_SYSTEM, ShmupWarzViewManagerSystem))
#define SHMUP_WARZ_VIEW_MANAGER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_VIEW_MANAGER_SYSTEM, ShmupWarzViewManagerSystemClass))
#define SHMUP_WARZ_IS_VIEW_MANAGER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_VIEW_MANAGER_SYSTEM))
#define SHMUP_WARZ_IS_VIEW_MANAGER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_VIEW_MANAGER_SYSTEM))
#define SHMUP_WARZ_VIEW_MANAGER_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_VIEW_MANAGER_SYSTEM, ShmupWarzViewManagerSystemClass))

typedef struct _ShmupWarzViewManagerSystem ShmupWarzViewManagerSystem;
typedef struct _ShmupWarzViewManagerSystemClass ShmupWarzViewManagerSystemClass;
typedef struct _ShmupWarzViewManagerSystemPrivate ShmupWarzViewManagerSystemPrivate;

#define SHMUP_WARZ_TYPE_GAME (shmup_warz_game_get_type ())
#define SHMUP_WARZ_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGame))
#define SHMUP_WARZ_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))
#define SHMUP_WARZ_IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_GAME))
#define SHMUP_WARZ_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_GAME, ShmupWarzGameClass))

typedef struct _ShmupWarzGame ShmupWarzGame;
typedef struct _ShmupWarzGameClass ShmupWarzGameClass;
#define _g_ptr_array_unref0(var) ((var == NULL) ? NULL : (var = (g_ptr_array_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define SHMUP_WARZ_TYPE_COMPONENT (shmup_warz_component_get_type ())

#define SHMUP_WARZ_TYPE_SCALE_COMPONENT (shmup_warz_scale_component_get_type ())
#define SHMUP_WARZ_SCALE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_SCALE_COMPONENT, ShmupWarzScaleComponent))
#define SHMUP_WARZ_SCALE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_SCALE_COMPONENT, ShmupWarzScaleComponentClass))
#define SHMUP_WARZ_IS_SCALE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_SCALE_COMPONENT))
#define SHMUP_WARZ_IS_SCALE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_SCALE_COMPONENT))
#define SHMUP_WARZ_SCALE_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_SCALE_COMPONENT, ShmupWarzScaleComponentClass))

typedef struct _ShmupWarzScaleComponent ShmupWarzScaleComponent;
typedef struct _ShmupWarzScaleComponentClass ShmupWarzScaleComponentClass;

#define SHMUP_WARZ_TYPE_LAYER_COMPONENT (shmup_warz_layer_component_get_type ())
#define SHMUP_WARZ_LAYER_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_LAYER_COMPONENT, ShmupWarzLayerComponent))
#define SHMUP_WARZ_LAYER_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_LAYER_COMPONENT, ShmupWarzLayerComponentClass))
#define SHMUP_WARZ_IS_LAYER_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_LAYER_COMPONENT))
#define SHMUP_WARZ_IS_LAYER_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_LAYER_COMPONENT))
#define SHMUP_WARZ_LAYER_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_LAYER_COMPONENT, ShmupWarzLayerComponentClass))

typedef struct _ShmupWarzLayerComponent ShmupWarzLayerComponent;
typedef struct _ShmupWarzLayerComponentClass ShmupWarzLayerComponentClass;

#define SHMUP_WARZ_TYPE_RESOURCE_COMPONENT (shmup_warz_resource_component_get_type ())
#define SHMUP_WARZ_RESOURCE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_RESOURCE_COMPONENT, ShmupWarzResourceComponent))
#define SHMUP_WARZ_RESOURCE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_RESOURCE_COMPONENT, ShmupWarzResourceComponentClass))
#define SHMUP_WARZ_IS_RESOURCE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_RESOURCE_COMPONENT))
#define SHMUP_WARZ_IS_RESOURCE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_RESOURCE_COMPONENT))
#define SHMUP_WARZ_RESOURCE_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_RESOURCE_COMPONENT, ShmupWarzResourceComponentClass))

typedef struct _ShmupWarzResourceComponent ShmupWarzResourceComponent;
typedef struct _ShmupWarzResourceComponentClass ShmupWarzResourceComponentClass;
typedef struct _ShmupWarzResourceComponentPrivate ShmupWarzResourceComponentPrivate;
typedef struct _ShmupWarzScaleComponentPrivate ShmupWarzScaleComponentPrivate;
typedef struct _ShmupWarzLayerComponentPrivate ShmupWarzLayerComponentPrivate;

#define SHMUP_WARZ_TYPE_TINT_COMPONENT (shmup_warz_tint_component_get_type ())
#define SHMUP_WARZ_TINT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHMUP_WARZ_TYPE_TINT_COMPONENT, ShmupWarzTintComponent))
#define SHMUP_WARZ_TINT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHMUP_WARZ_TYPE_TINT_COMPONENT, ShmupWarzTintComponentClass))
#define SHMUP_WARZ_IS_TINT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHMUP_WARZ_TYPE_TINT_COMPONENT))
#define SHMUP_WARZ_IS_TINT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHMUP_WARZ_TYPE_TINT_COMPONENT))
#define SHMUP_WARZ_TINT_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SHMUP_WARZ_TYPE_TINT_COMPONENT, ShmupWarzTintComponentClass))

typedef struct _ShmupWarzTintComponent ShmupWarzTintComponent;
typedef struct _ShmupWarzTintComponentClass ShmupWarzTintComponentClass;
typedef struct _ShmupWarzTintComponentPrivate ShmupWarzTintComponentPrivate;

struct _ShmupWarzViewManagerSystem {
	GObject parent_instance;
	ShmupWarzViewManagerSystemPrivate * priv;
};

struct _ShmupWarzViewManagerSystemClass {
	GObjectClass parent_class;
};

struct _ShmupWarzViewManagerSystemPrivate {
	SDL_Renderer* _renderer;
	GPtrArray* _sprites;
	EntitasGroup* _group;
	EntitasWorld* _world;
	ShmupWarzGame* _game;
};

typedef enum  {
	SHMUP_WARZ_COMPONENT_Bounds,
	SHMUP_WARZ_COMPONENT_Bullet,
	SHMUP_WARZ_COMPONENT_ColorTween,
	SHMUP_WARZ_COMPONENT_Destroy,
	SHMUP_WARZ_COMPONENT_Enemy,
	SHMUP_WARZ_COMPONENT_Expires,
	SHMUP_WARZ_COMPONENT_Firing,
	SHMUP_WARZ_COMPONENT_Health,
	SHMUP_WARZ_COMPONENT_Layer,
	SHMUP_WARZ_COMPONENT_Life,
	SHMUP_WARZ_COMPONENT_Mine,
	SHMUP_WARZ_COMPONENT_Mouse,
	SHMUP_WARZ_COMPONENT_Player,
	SHMUP_WARZ_COMPONENT_Position,
	SHMUP_WARZ_COMPONENT_Resource,
	SHMUP_WARZ_COMPONENT_ScaleTween,
	SHMUP_WARZ_COMPONENT_Scale,
	SHMUP_WARZ_COMPONENT_Score,
	SHMUP_WARZ_COMPONENT_SoundEffect,
	SHMUP_WARZ_COMPONENT_Text,
	SHMUP_WARZ_COMPONENT_Tint,
	SHMUP_WARZ_COMPONENT_Velocity,
	SHMUP_WARZ_COMPONENT_ComponentsCount
} ShmupWarzComponent;

struct _ShmupWarzResourceComponent {
	GObject parent_instance;
	ShmupWarzResourceComponentPrivate * priv;
	gchar* path;
	GObject* sprite;
	gboolean bgd;
};

struct _ShmupWarzResourceComponentClass {
	GObjectClass parent_class;
};

struct _ShmupWarzScaleComponent {
	GObject parent_instance;
	ShmupWarzScaleComponentPrivate * priv;
	gdouble x;
	gdouble y;
};

struct _ShmupWarzScaleComponentClass {
	GObjectClass parent_class;
};

struct _ShmupWarzLayerComponent {
	GObject parent_instance;
	ShmupWarzLayerComponentPrivate * priv;
	gint ordinal;
};

struct _ShmupWarzLayerComponentClass {
	GObjectClass parent_class;
};

struct _ShmupWarzTintComponent {
	GObject parent_instance;
	ShmupWarzTintComponentPrivate * priv;
	gint r;
	gint g;
	gint b;
	gint a;
};

struct _ShmupWarzTintComponentClass {
	GObjectClass parent_class;
};


static gpointer shmup_warz_view_manager_system_parent_class = NULL;
static EntitasISystemIface* shmup_warz_view_manager_system_entitas_isystem_parent_iface = NULL;
static EntitasIInitializeSystemIface* shmup_warz_view_manager_system_entitas_iinitialize_system_parent_iface = NULL;
static EntitasISetWorldIface* shmup_warz_view_manager_system_entitas_iset_world_parent_iface = NULL;

GType shmup_warz_view_manager_system_get_type (void) G_GNUC_CONST;
GType shmup_warz_game_get_type (void) G_GNUC_CONST;
#define SHMUP_WARZ_VIEW_MANAGER_SYSTEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SHMUP_WARZ_TYPE_VIEW_MANAGER_SYSTEM, ShmupWarzViewManagerSystemPrivate))
enum  {
	SHMUP_WARZ_VIEW_MANAGER_SYSTEM_DUMMY_PROPERTY
};
ShmupWarzViewManagerSystem* shmup_warz_view_manager_system_new (ShmupWarzGame* game);
ShmupWarzViewManagerSystem* shmup_warz_view_manager_system_construct (GType object_type, ShmupWarzGame* game);
static void shmup_warz_view_manager_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world);
static void shmup_warz_view_manager_system_real_initialize (EntitasIInitializeSystem* base);
GType shmup_warz_component_get_type (void) G_GNUC_CONST;
void shmup_warz_view_manager_system_onEntityAdded (ShmupWarzViewManagerSystem* self, EntitasGroup* g, EntitasEntity* e, gint ix, EntitasIComponent* c);
static void _shmup_warz_view_manager_system_onEntityAdded_entitas_on_group_changed (EntitasGroup* g, EntitasEntity* e, gint i, EntitasIComponent* c, gpointer self);
static void _g_object_unref0_ (gpointer var);
GType shmup_warz_scale_component_get_type (void) G_GNUC_CONST;
GType shmup_warz_layer_component_get_type (void) G_GNUC_CONST;
GType shmup_warz_resource_component_get_type (void) G_GNUC_CONST;
gboolean shmup_warz_hasScale (EntitasEntity* e);
ShmupWarzScaleComponent* shmup_warz_getScale (EntitasEntity* e);
gboolean shmup_warz_hasLayer (EntitasEntity* e);
ShmupWarzLayerComponent* shmup_warz_getLayer (EntitasEntity* e);
gboolean shmup_warz_hasTint (EntitasEntity* e);
GType shmup_warz_tint_component_get_type (void) G_GNUC_CONST;
ShmupWarzTintComponent* shmup_warz_getTint (EntitasEntity* e);
static void shmup_warz_view_manager_system_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


ShmupWarzViewManagerSystem* shmup_warz_view_manager_system_construct (GType object_type, ShmupWarzGame* game) {
	ShmupWarzViewManagerSystem * self = NULL;
	ShmupWarzGame* _tmp0_ = NULL;
	ShmupWarzGame* _tmp1_ = NULL;
	ShmupWarzGame* _tmp2_ = NULL;
	SDL_Renderer* _tmp3_ = NULL;
	g_return_val_if_fail (game != NULL, NULL);
	self = (ShmupWarzViewManagerSystem*) g_object_new (object_type, NULL);
	_tmp0_ = game;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_game);
	self->priv->_game = _tmp1_;
	_tmp2_ = self->priv->_game;
	_tmp3_ = ((BoscoAbstractGame*) _tmp2_)->renderer;
	self->priv->_renderer = _tmp3_;
	return self;
}


ShmupWarzViewManagerSystem* shmup_warz_view_manager_system_new (ShmupWarzGame* game) {
	return shmup_warz_view_manager_system_construct (SHMUP_WARZ_TYPE_VIEW_MANAGER_SYSTEM, game);
}


static void shmup_warz_view_manager_system_real_setWorld (EntitasISetWorld* base, EntitasWorld* world) {
	ShmupWarzViewManagerSystem * self;
	EntitasWorld* _tmp0_ = NULL;
	EntitasWorld* _tmp1_ = NULL;
	self = (ShmupWarzViewManagerSystem*) base;
	g_return_if_fail (world != NULL);
	_tmp0_ = world;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_world);
	self->priv->_world = _tmp1_;
}


/**
        * Listen for resources to be added
        * and then load them in from the file
        */
static void _shmup_warz_view_manager_system_onEntityAdded_entitas_on_group_changed (EntitasGroup* g, EntitasEntity* e, gint i, EntitasIComponent* c, gpointer self) {
	shmup_warz_view_manager_system_onEntityAdded ((ShmupWarzViewManagerSystem*) self, g, e, i, c);
}


static void _g_object_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


static gpointer _g_ptr_array_ref0 (gpointer self) {
	return self ? g_ptr_array_ref (self) : NULL;
}


static void shmup_warz_view_manager_system_real_initialize (EntitasIInitializeSystem* base) {
	ShmupWarzViewManagerSystem * self;
	EntitasWorld* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	EntitasIMatcher* _tmp3_ = NULL;
	EntitasIMatcher* _tmp4_ = NULL;
	EntitasGroup* _tmp5_ = NULL;
	EntitasGroup* _tmp6_ = NULL;
	EntitasGroupChanged* _tmp7_ = NULL;
	EntitasGroupChanged* _tmp8_ = NULL;
	ShmupWarzGame* _tmp9_ = NULL;
	GPtrArray* _tmp10_ = NULL;
	ShmupWarzGame* _tmp11_ = NULL;
	GPtrArray* _tmp12_ = NULL;
	GPtrArray* _tmp13_ = NULL;
	self = (ShmupWarzViewManagerSystem*) base;
	_tmp0_ = self->priv->_world;
	_tmp1_ = g_new0 (gint, 1);
	_tmp1_[0] = (gint) SHMUP_WARZ_COMPONENT_Resource;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = 1;
	_tmp3_ = entitas_matcher_AllOf (_tmp2_, 1);
	_tmp4_ = _tmp3_;
	_tmp5_ = entitas_world_getGroup (_tmp0_, _tmp4_);
	_g_object_unref0 (self->priv->_group);
	self->priv->_group = _tmp5_;
	_g_object_unref0 (_tmp4_);
	_tmp2_ = (g_free (_tmp2_), NULL);
	_tmp6_ = self->priv->_group;
	_tmp7_ = entitas_group_get_onEntityAdded (_tmp6_);
	_tmp8_ = _tmp7_;
	entitas_group_changed_add (_tmp8_, _shmup_warz_view_manager_system_onEntityAdded_entitas_on_group_changed, self);
	_tmp9_ = self->priv->_game;
	_tmp10_ = g_ptr_array_new_full ((guint) 0, _g_object_unref0_);
	_g_ptr_array_unref0 (((BoscoAbstractGame*) _tmp9_)->sprites);
	((BoscoAbstractGame*) _tmp9_)->sprites = _tmp10_;
	_tmp11_ = self->priv->_game;
	_tmp12_ = ((BoscoAbstractGame*) _tmp11_)->sprites;
	_tmp13_ = _g_ptr_array_ref0 (_tmp12_);
	_g_ptr_array_unref0 (self->priv->_sprites);
	self->priv->_sprites = _tmp13_;
}


/**
        *  OnEntityAdded event:
        */
static gint g_ptr_array_get_length (GPtrArray* self) {
	gint result;
	guint _tmp0_ = 0U;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->len;
	result = (gint) _tmp0_;
	return result;
}


static void g_ptr_array_set_length (GPtrArray* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	g_ptr_array_set_size (self, _tmp0_);
}


void shmup_warz_view_manager_system_onEntityAdded (ShmupWarzViewManagerSystem* self, EntitasGroup* g, EntitasEntity* e, gint ix, EntitasIComponent* c) {
	ShmupWarzScaleComponent* scale = NULL;
	ShmupWarzLayerComponent* layer = NULL;
	gint ordinal = 0;
	ShmupWarzResourceComponent* res = NULL;
	EntitasIComponent* _tmp0_ = NULL;
	ShmupWarzResourceComponent* _tmp1_ = NULL;
	ShmupWarzResourceComponent* _tmp2_ = NULL;
	SDL_Renderer* _tmp3_ = NULL;
	ShmupWarzResourceComponent* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	BoscoSprite* _tmp6_ = NULL;
	BoscoSprite* sprite = NULL;
	ShmupWarzResourceComponent* _tmp7_ = NULL;
	GObject* _tmp8_ = NULL;
	BoscoSprite* _tmp9_ = NULL;
	BoscoSprite* _tmp10_ = NULL;
	EntitasEntity* _tmp13_ = NULL;
	gboolean _tmp14_ = FALSE;
	EntitasEntity* _tmp25_ = NULL;
	gboolean _tmp26_ = FALSE;
	EntitasEntity* _tmp36_ = NULL;
	gboolean _tmp37_ = FALSE;
	ShmupWarzResourceComponent* _tmp53_ = NULL;
	gboolean _tmp54_ = FALSE;
	GPtrArray* _tmp56_ = NULL;
	gint _tmp57_ = 0;
	gint _tmp58_ = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (g != NULL);
	g_return_if_fail (e != NULL);
	g_return_if_fail (c != NULL);
	ordinal = 0;
	_tmp0_ = c;
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, SHMUP_WARZ_TYPE_RESOURCE_COMPONENT, ShmupWarzResourceComponent));
	res = _tmp1_;
	_tmp2_ = res;
	_tmp3_ = self->priv->_renderer;
	_tmp4_ = res;
	_tmp5_ = _tmp4_->path;
	_tmp6_ = bosco_sprite_fromFile (_tmp3_, _tmp5_);
	_g_object_unref0 (_tmp2_->sprite);
	_tmp2_->sprite = (GObject*) _tmp6_;
	_tmp7_ = res;
	_tmp8_ = _tmp7_->sprite;
	_tmp9_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, BOSCO_TYPE_SPRITE, BoscoSprite));
	sprite = _tmp9_;
	_tmp10_ = sprite;
	if (_tmp10_ == NULL) {
		ShmupWarzResourceComponent* _tmp11_ = NULL;
		const gchar* _tmp12_ = NULL;
		_tmp11_ = res;
		_tmp12_ = _tmp11_->path;
		g_print ("Failed to load %s\n", _tmp12_);
		_g_object_unref0 (sprite);
		_g_object_unref0 (res);
		_g_object_unref0 (layer);
		_g_object_unref0 (scale);
		return;
	}
	_tmp13_ = e;
	_tmp14_ = shmup_warz_hasScale (_tmp13_);
	if (_tmp14_) {
		BoscoSprite* _tmp15_ = NULL;
		EntitasEntity* _tmp16_ = NULL;
		ShmupWarzScaleComponent* _tmp17_ = NULL;
		ShmupWarzScaleComponent* _tmp18_ = NULL;
		gdouble _tmp19_ = 0.0;
		BoscoSprite* _tmp20_ = NULL;
		EntitasEntity* _tmp21_ = NULL;
		ShmupWarzScaleComponent* _tmp22_ = NULL;
		ShmupWarzScaleComponent* _tmp23_ = NULL;
		gdouble _tmp24_ = 0.0;
		_tmp15_ = sprite;
		_tmp16_ = e;
		_tmp17_ = shmup_warz_getScale (_tmp16_);
		_tmp18_ = _tmp17_;
		_tmp19_ = _tmp18_->x;
		_tmp15_->scale.x = _tmp19_;
		_g_object_unref0 (_tmp18_);
		_tmp20_ = sprite;
		_tmp21_ = e;
		_tmp22_ = shmup_warz_getScale (_tmp21_);
		_tmp23_ = _tmp22_;
		_tmp24_ = _tmp23_->y;
		_tmp20_->scale.y = _tmp24_;
		_g_object_unref0 (_tmp23_);
	}
	_tmp25_ = e;
	_tmp26_ = shmup_warz_hasLayer (_tmp25_);
	if (_tmp26_) {
		BoscoSprite* _tmp27_ = NULL;
		EntitasEntity* _tmp28_ = NULL;
		ShmupWarzLayerComponent* _tmp29_ = NULL;
		ShmupWarzLayerComponent* _tmp30_ = NULL;
		gint _tmp31_ = 0;
		EntitasEntity* _tmp32_ = NULL;
		ShmupWarzLayerComponent* _tmp33_ = NULL;
		ShmupWarzLayerComponent* _tmp34_ = NULL;
		gint _tmp35_ = 0;
		_tmp27_ = sprite;
		_tmp28_ = e;
		_tmp29_ = shmup_warz_getLayer (_tmp28_);
		_tmp30_ = _tmp29_;
		_tmp31_ = _tmp30_->ordinal;
		_tmp27_->layer = _tmp31_;
		_g_object_unref0 (_tmp30_);
		_tmp32_ = e;
		_tmp33_ = shmup_warz_getLayer (_tmp32_);
		_tmp34_ = _tmp33_;
		_tmp35_ = _tmp34_->ordinal;
		ordinal = _tmp35_;
		_g_object_unref0 (_tmp34_);
	}
	_tmp36_ = e;
	_tmp37_ = shmup_warz_hasTint (_tmp36_);
	if (_tmp37_) {
		BoscoSprite* _tmp38_ = NULL;
		EntitasEntity* _tmp39_ = NULL;
		ShmupWarzTintComponent* _tmp40_ = NULL;
		ShmupWarzTintComponent* _tmp41_ = NULL;
		gint _tmp42_ = 0;
		BoscoSprite* _tmp43_ = NULL;
		EntitasEntity* _tmp44_ = NULL;
		ShmupWarzTintComponent* _tmp45_ = NULL;
		ShmupWarzTintComponent* _tmp46_ = NULL;
		gint _tmp47_ = 0;
		BoscoSprite* _tmp48_ = NULL;
		EntitasEntity* _tmp49_ = NULL;
		ShmupWarzTintComponent* _tmp50_ = NULL;
		ShmupWarzTintComponent* _tmp51_ = NULL;
		gint _tmp52_ = 0;
		_tmp38_ = sprite;
		_tmp39_ = e;
		_tmp40_ = shmup_warz_getTint (_tmp39_);
		_tmp41_ = _tmp40_;
		_tmp42_ = _tmp41_->r;
		_tmp38_->color.r = (guint8) _tmp42_;
		_g_object_unref0 (_tmp41_);
		_tmp43_ = sprite;
		_tmp44_ = e;
		_tmp45_ = shmup_warz_getTint (_tmp44_);
		_tmp46_ = _tmp45_;
		_tmp47_ = _tmp46_->g;
		_tmp43_->color.g = (guint8) _tmp47_;
		_g_object_unref0 (_tmp46_);
		_tmp48_ = sprite;
		_tmp49_ = e;
		_tmp50_ = shmup_warz_getTint (_tmp49_);
		_tmp51_ = _tmp50_;
		_tmp52_ = _tmp51_->b;
		_tmp48_->color.b = (guint8) _tmp52_;
		_g_object_unref0 (_tmp51_);
	}
	_tmp53_ = res;
	_tmp54_ = _tmp53_->bgd;
	if (_tmp54_) {
		BoscoSprite* _tmp55_ = NULL;
		_tmp55_ = sprite;
		_tmp55_->centered = FALSE;
	}
	_tmp56_ = self->priv->_sprites;
	_tmp57_ = g_ptr_array_get_length (_tmp56_);
	_tmp58_ = _tmp57_;
	if (_tmp58_ == 0) {
		GPtrArray* _tmp59_ = NULL;
		BoscoSprite* _tmp60_ = NULL;
		BoscoSprite* _tmp61_ = NULL;
		_tmp59_ = self->priv->_sprites;
		_tmp60_ = sprite;
		_tmp61_ = _g_object_ref0 (_tmp60_);
		g_ptr_array_add (_tmp59_, _tmp61_);
	} else {
		GPtrArray* _tmp76_ = NULL;
		BoscoSprite* _tmp77_ = NULL;
		BoscoSprite* _tmp78_ = NULL;
		{
			gint i = 0;
			i = 0;
			{
				gboolean _tmp62_ = FALSE;
				_tmp62_ = TRUE;
				while (TRUE) {
					GPtrArray* _tmp64_ = NULL;
					gint _tmp65_ = 0;
					gint _tmp66_ = 0;
					gint _tmp67_ = 0;
					GPtrArray* _tmp68_ = NULL;
					gint _tmp69_ = 0;
					gconstpointer _tmp70_ = NULL;
					gint _tmp71_ = 0;
					if (!_tmp62_) {
						gint _tmp63_ = 0;
						_tmp63_ = i;
						i = _tmp63_ + 1;
					}
					_tmp62_ = FALSE;
					_tmp64_ = self->priv->_sprites;
					_tmp65_ = g_ptr_array_get_length (_tmp64_);
					_tmp66_ = _tmp65_;
					if (!(i <= (_tmp66_ - 1))) {
						break;
					}
					_tmp67_ = ordinal;
					_tmp68_ = self->priv->_sprites;
					_tmp69_ = i;
					_tmp70_ = g_ptr_array_index (_tmp68_, (guint) _tmp69_);
					_tmp71_ = ((BoscoSprite*) _tmp70_)->layer;
					if (_tmp67_ <= _tmp71_) {
						GPtrArray* _tmp72_ = NULL;
						gint _tmp73_ = 0;
						BoscoSprite* _tmp74_ = NULL;
						BoscoSprite* _tmp75_ = NULL;
						_tmp72_ = self->priv->_sprites;
						_tmp73_ = i;
						_tmp74_ = sprite;
						_tmp75_ = _g_object_ref0 (_tmp74_);
						g_ptr_array_insert (_tmp72_, _tmp73_, _tmp75_);
						_g_object_unref0 (sprite);
						_g_object_unref0 (res);
						_g_object_unref0 (layer);
						_g_object_unref0 (scale);
						return;
					}
				}
			}
		}
		_tmp76_ = self->priv->_sprites;
		_tmp77_ = sprite;
		_tmp78_ = _g_object_ref0 (_tmp77_);
		g_ptr_array_add (_tmp76_, _tmp78_);
	}
	_g_object_unref0 (sprite);
	_g_object_unref0 (res);
	_g_object_unref0 (layer);
	_g_object_unref0 (scale);
}


static void shmup_warz_view_manager_system_class_init (ShmupWarzViewManagerSystemClass * klass) {
	shmup_warz_view_manager_system_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ShmupWarzViewManagerSystemPrivate));
	G_OBJECT_CLASS (klass)->finalize = shmup_warz_view_manager_system_finalize;
}


static void shmup_warz_view_manager_system_entitas_isystem_interface_init (EntitasISystemIface * iface) {
	shmup_warz_view_manager_system_entitas_isystem_parent_iface = g_type_interface_peek_parent (iface);
}


static void shmup_warz_view_manager_system_entitas_iinitialize_system_interface_init (EntitasIInitializeSystemIface * iface) {
	shmup_warz_view_manager_system_entitas_iinitialize_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->initialize = (void (*)(EntitasIInitializeSystem*)) shmup_warz_view_manager_system_real_initialize;
}


static void shmup_warz_view_manager_system_entitas_iset_world_interface_init (EntitasISetWorldIface * iface) {
	shmup_warz_view_manager_system_entitas_iset_world_parent_iface = g_type_interface_peek_parent (iface);
	iface->setWorld = (void (*)(EntitasISetWorld*, EntitasWorld*)) shmup_warz_view_manager_system_real_setWorld;
}


static void shmup_warz_view_manager_system_instance_init (ShmupWarzViewManagerSystem * self) {
	self->priv = SHMUP_WARZ_VIEW_MANAGER_SYSTEM_GET_PRIVATE (self);
}


static void shmup_warz_view_manager_system_finalize (GObject* obj) {
	ShmupWarzViewManagerSystem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SHMUP_WARZ_TYPE_VIEW_MANAGER_SYSTEM, ShmupWarzViewManagerSystem);
	_g_ptr_array_unref0 (self->priv->_sprites);
	_g_object_unref0 (self->priv->_group);
	_g_object_unref0 (self->priv->_world);
	_g_object_unref0 (self->priv->_game);
	G_OBJECT_CLASS (shmup_warz_view_manager_system_parent_class)->finalize (obj);
}


GType shmup_warz_view_manager_system_get_type (void) {
	static volatile gsize shmup_warz_view_manager_system_type_id__volatile = 0;
	if (g_once_init_enter (&shmup_warz_view_manager_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShmupWarzViewManagerSystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shmup_warz_view_manager_system_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShmupWarzViewManagerSystem), 0, (GInstanceInitFunc) shmup_warz_view_manager_system_instance_init, NULL };
		static const GInterfaceInfo entitas_isystem_info = { (GInterfaceInitFunc) shmup_warz_view_manager_system_entitas_isystem_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iinitialize_system_info = { (GInterfaceInitFunc) shmup_warz_view_manager_system_entitas_iinitialize_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iset_world_info = { (GInterfaceInitFunc) shmup_warz_view_manager_system_entitas_iset_world_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType shmup_warz_view_manager_system_type_id;
		shmup_warz_view_manager_system_type_id = g_type_register_static (G_TYPE_OBJECT, "ShmupWarzViewManagerSystem", &g_define_type_info, 0);
		g_type_add_interface_static (shmup_warz_view_manager_system_type_id, ENTITAS_TYPE_ISYSTEM, &entitas_isystem_info);
		g_type_add_interface_static (shmup_warz_view_manager_system_type_id, ENTITAS_TYPE_IINITIALIZE_SYSTEM, &entitas_iinitialize_system_info);
		g_type_add_interface_static (shmup_warz_view_manager_system_type_id, ENTITAS_TYPE_ISET_WORLD, &entitas_iset_world_info);
		g_once_init_leave (&shmup_warz_view_manager_system_type_id__volatile, shmup_warz_view_manager_system_type_id);
	}
	return shmup_warz_view_manager_system_type_id__volatile;
}



